-- =====================================================================
-- Fórum Mundial de Enfermagem — Setup do Supabase
-- Arquivo para colar no SQL Editor do Supabase (Dashboard → SQL Editor → New query)
-- Idempotente: pode rodar quantas vezes quiser sem quebrar nada.
-- =====================================================================

-- Garante a extensão pgcrypto (gen_random_uuid)
create extension if not exists pgcrypto;

-- =====================================================================
-- 1. TABELA posts (base do feed + respostas)
-- =====================================================================
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  nome_usuario text not null,
  conteudo text not null,
  titulo text,
  imagem_url text,
  created_at timestamptz not null default now(),
  parent_id bigint references public.posts(id) on delete cascade
);

-- 1.1 Colunas novas (País / Profissão / Área / Idioma) usadas pelo frontend.
--     Se não existirem, o frontend faz fallback e perde esses dados.
alter table public.posts add column if not exists pais_codigo text;
alter table public.posts add column if not exists pais_nome text;
alter table public.posts add column if not exists profissao text;
alter table public.posts add column if not exists area text;
alter table public.posts add column if not exists local_trabalho text;
alter table public.posts add column if not exists original_language text;
-- parent_id é usado pelas RESPOSTAS (sem ele, responder falha). Usa bigint
-- sem FK aqui para casar com o tipo real de posts.id (integer/bigint) já existente.
alter table public.posts add column if not exists parent_id bigint;

-- =====================================================================
-- 2. RLS + políticas da tabela posts
--    IMPORTANTE: o frontend atual usa a ANON KEY, sem login.
--    Estas políticas permissivas são o mínimo para o fórum funcionar hoje.
--    Quando ativar Supabase Auth, troque pelas políticas restritas da
--    documentação (FORUM-MUNDIAL-ENFERMAGEM.md, seção 4).
-- =====================================================================
alter table public.posts enable row level security;

drop policy if exists "posts_public_read" on public.posts;
create policy "posts_public_read" on public.posts
  for select using (true);

drop policy if exists "posts_public_insert" on public.posts;
create policy "posts_public_insert" on public.posts
  for insert with check (true);

-- =====================================================================
-- 3. TABELA reports (botão "Denunciar")
-- =====================================================================
create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  post_id bigint,
  reason text,
  status text not null default 'open',
  created_at timestamptz not null default now()
);

alter table public.reports enable row level security;

drop policy if exists "reports_public_insert" on public.reports;
create policy "reports_public_insert" on public.reports
  for insert with check (true);

-- =====================================================================
-- 4. STORAGE — bucket de imagens do fórum
--    Cria o bucket público e as políticas de upload/leitura.
-- =====================================================================
insert into storage.buckets (id, name, public)
values ('forum-imagens-enfermagem', 'forum-imagens-enfermagem', true)
on conflict (id) do update set public = true;

drop policy if exists "forum_images_insert" on storage.objects;
create policy "forum_images_insert" on storage.objects
  for insert with check (bucket_id = 'forum-imagens-enfermagem');

drop policy if exists "forum_images_public_read" on storage.objects;
create policy "forum_images_public_read" on storage.objects
  for select using (bucket_id = 'forum-imagens-enfermagem');

-- =====================================================================
-- FIM DO MÍNIMO NECESSÁRIO.
-- Com as seções 1 a 4 executadas, o fórum já salva e exibe posts
-- para todos os idiomas (uma única mensagem, interface traduzida no cliente).
-- =====================================================================


-- =====================================================================
-- 5. ÁLBUM DE FOTOS (album_enfermagem.html)
--    Tabela pública de fotos: SELECT + INSERT apenas (sem UPDATE/DELETE).
--    Frontend usa a anon key, sem Auth e sem colunas de ownership.
-- =====================================================================
create table if not exists public.album_fotos (
  id uuid primary key default gen_random_uuid(),
  titulo text not null,
  descricao text,
  ano text,
  instituicao text,
  localizacao text,
  imagem_url text,
  data_upload timestamptz not null default now()
);

alter table public.album_fotos enable row level security;

drop policy if exists "album_fotos_public_read" on public.album_fotos;
create policy "album_fotos_public_read" on public.album_fotos
  for select using (true);

drop policy if exists "album_fotos_public_insert" on public.album_fotos;
create policy "album_fotos_public_insert" on public.album_fotos
  for insert with check (true);

-- O álbum grava imagens no MESMO bucket do fórum (forum-imagens-enfermagem),
-- na pasta album/... As políticas de storage da seção 4 já cobrem o bucket
-- inteiro por bucket_id, então não é preciso criar política nova para album/.


-- =====================================================================
-- 6. TRADUÇÕES (cache da Edge Function translate-forum-message)
--    Acesso SOMENTE pelo backend (service_role). O frontend NÃO acessa
--    esta tabela diretamente — ele chama a Edge Function.
--    Com RLS habilitado e SEM políticas, anon/authenticated ficam
--    bloqueados; o service_role (usado pela Edge Function) ignora RLS.
-- =====================================================================
create table if not exists public.translations (
  id uuid primary key default gen_random_uuid(),
  message_id bigint not null,
  source_language text,
  target_language text,
  source_hash text not null,
  translated_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists translations_unique
  on public.translations (message_id, source_hash, target_language);

alter table public.translations enable row level security;
-- (sem políticas para anon/authenticated por padrão)


-- =====================================================================
-- 7. OPCIONAL — Supabase Auth + perfis + moderação (quando quiser login real)
--    Descomente e rode somente quando for ativar o login.
-- =====================================================================
/*
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  country_code text,
  country_name text,
  profession text,
  specialty text,
  workplace text,
  bio text,
  language text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

-- Políticas RESTRITAS para quando o Auth estiver ativo (substituem as permissivas acima):
--   drop policy if exists "posts_public_read" on public.posts;
--   drop policy if exists "posts_public_insert" on public.posts;
--   create policy "posts_public_read" on public.posts
--     for select using (status = 'published' and deleted_at is null);
--   create policy "posts_insert_auth" on public.posts
--     for insert with check (auth.uid() = author_id);
*/
