-- Curtidas do álbum (coração nas fotos)
create table if not exists public.album_likes (
  id bigint generated by default as identity primary key,
  foto_id integer not null references public.album_fotos(id) on delete cascade,
  author_key text not null,
  author_name text,
  created_at timestamptz not null default now(),
  unique (foto_id, author_key)
);

alter table public.album_likes enable row level security;

drop policy if exists "album_likes_public_read" on public.album_likes;
create policy "album_likes_public_read" on public.album_likes
  for select using (true);

drop policy if exists "album_likes_public_insert" on public.album_likes;
create policy "album_likes_public_insert" on public.album_likes
  for insert with check (true);

drop policy if exists "album_likes_public_delete" on public.album_likes;
create policy "album_likes_public_delete" on public.album_likes
  for delete using (
    author_key = current_setting('request.headers', true)::json->>'x-author-key'
  );

-- Comentários do álbum (postits ao lado das fotos)
create table if not exists public.album_comentarios (
  id bigint generated by default as identity primary key,
  foto_id integer not null references public.album_fotos(id) on delete cascade,
  author_key text not null,
  author_name text,
  comentario text not null,
  localizacao text,
  created_at timestamptz not null default now()
);

alter table public.album_comentarios enable row level security;

drop policy if exists "album_comentarios_public_read" on public.album_comentarios;
create policy "album_comentarios_public_read" on public.album_comentarios
  for select using (true);

drop policy if exists "album_comentarios_public_insert" on public.album_comentarios;
create policy "album_comentarios_public_insert" on public.album_comentarios
  for insert with check (true);
