(function (global) {
  "use strict";

  var STORAGE_KEY = "conta.language";
  var DEFAULT_LANGUAGE = "pt-BR";
  var LANGUAGE_ALIASES = { pt: "pt-BR", "pt-br": "pt-BR", en: "en", es: "es", fr: "fr", de: "de", it: "it", ja: "ja", zh: "zh", "zh-cn": "zh", hi: "hi", ar: "ar", ru: "ru", tr: "tr", ko: "ko", nl: "nl", pl: "pl", sv: "sv", id: "id", vi: "vi", uk: "uk" };
  var LANGUAGE_PREFIXES = { en: 1, es: 1, fr: 1, de: 1, it: 1, ja: 1, zh: 1, hi: 1, ar: 1, ru: 1, tr: 1, ko: 1, nl: 1, pl: 1, sv: 1, id: 1, vi: 1, uk: 1 };
  var languages = [
    ["pt-BR", "Português (Brasil)", "/bandeira-brasil-calculadoras-de-enfermagem.webp"], ["en", "English", "/bandeira-eua-calculadoras-de-enfermagem.webp"],
    ["es", "Español", "/bandeira-espanha-calculadoras-de-enfermagem.webp"], ["fr", "Français", "/bandeira-franca-calculadoras-de-enfermagem.webp"],
    ["de", "Deutsch", "/bandeira-alemanha-calculadoras-de-enfermagem.webp"], ["it", "Italiano", "/bandeira-italia-calculadoras-de-enfermagem.webp"],
    ["ja", "日本語", "/bandeira-japao-calculadoras-de-enfermagem.webp"], ["zh", "中文", "/bandeira-china-calculadoras-de-enfermagem.webp"],
    ["hi", "हिन्दी", "/bandeira-india-calculadoras-de-enfermagem.webp"], ["ar", "العربية", "/bandeira-arabia-calculadoras-de-enfermagem.webp"],
    ["ru", "Русский", "/bandeira-russia-calculadoras-de-enfermagem.webp"], ["tr", "Türkçe", "/bandeira-turquia-calculadoras-de-enfermagem.webp"],
    ["ko", "한국어", "/bandeira-coreia-calculadoras-de-enfermagem.webp"], ["nl", "Nederlands", "/bandeira-holanda-calculadoras-de-enfermagem.webp"],
    ["pl", "Polski", "/bandeira-polonia-calculadoras-de-enfermagem.webp"], ["sv", "Svenska", "/bandeira-suecia-calculadoras-de-enfermagem.webp"],
    ["id", "Bahasa Indonesia", "/bandeira-indonesia-calculadoras-de-enfermagem.webp"], ["vi", "Tiếng Việt", "/bandeira-vietna-calculadoras-de-enfermagem.webp"],
    ["uk", "Українська", "/bandeira-ucrania-calculadoras-de-enfermagem.webp"]
  ].map(function (item) { return { code: item[0], label: item[1], flag: item[2], dir: item[0] === "ar" ? "rtl" : "ltr" }; });

  var pt = {
    accountSystem: "SISTEMA DE CONTAS", myAccount: "Minha Conta", accountHero: "Acesse sua conta para salvar favoritos, acompanhar seu histórico e desbloquear recursos exclusivos.",
    signInAccount: "Entrar na sua conta", google: "Continuar com Google", microsoft: "Continuar com Microsoft", apple: "Continuar com Apple", or: "ou",
    emailSignIn: "Entrar com E-mail", fullName: "Nome completo", fullNamePlaceholder: "Seu nome completo", email: "E-mail", password: "Senha", passwordPlaceholder: "Sua senha",
    forgotPassword: "Esqueceu a senha?", createAccount: "Criar conta", backToLogin: "Voltar ao login", signIn: "Entrar", register: "Cadastrar", createYourAccount: "Criar sua conta",
    resetPassword: "Recuperar senha", sendResetLink: "Enviar link de recuperação", invalidEmail: "Informe um e-mail válido.", requiredFields: "Preencha todos os campos obrigatórios.",
    shortPassword: "A senha deve ter pelo menos 6 caracteres.", authSuccess: "Autenticação realizada com sucesso.", resetSent: "Enviamos as instruções de recuperação para seu e-mail.",
    profile: "Meu Perfil", profileHero: "Gerencie suas informações pessoais e preferências de conta.", loadingProfile: "Carregando seu perfil…", displayName: "Nome de exibição", saveName: "Salvar nome", settings: "Configurações", signOut: "Sair da conta",
    settingsHero: "Ajuste suas preferências de conta, notificações e privacidade.", preferences: "Preferências", siteLanguage: "Idioma do site", light: "Claro", dark: "Escuro", fontSize: "Tamanho da fonte", savePreferences: "Salvar preferências",
    favorites: "Favoritos", favoritesHero: "Acesse rapidamente suas calculadoras, escalas e materiais favoritos.", myFavorites: "Meus Favoritos", searchFavorites: "Pesquisar favoritos…",
    history: "Histórico", historyHero: "Consulte e acesse novamente todos os seus cálculos e laudos anteriores.", myHistory: "Meu Histórico", searchHistory: "Pesquisar histórico…", deleteHistory: "Excluir histórico", previous: "← Anterior", next: "Próxima →",
    allCategories: "Todas as categorias", allTypes: "Todos os tipos", allLanguages: "Todos os idiomas", all: "Todos", filterCategory: "Filtrar por categoria", filterType: "Filtrar por tipo", filterLanguage: "Filtrar por idioma", sort: "Ordenar favoritos",
    subscription: "Assinatura Premium", subscriptionHero: "Escolha o plano ideal: Gratuito, Júnior, Pleno ou Sênior.", choosePlan: "Escolha seu plano", yourSubscription: "Sua assinatura", plan: "Plano:", status: "Status:", activate: "Ativar (simular pagamento)", pause: "Pausar", cancel: "Cancelar", resume: "Retomar", cancelConfirm: "Cancelar assinatura?",
    checkout: "Finalizar assinatura", checkoutHero: "Confira o plano escolhido e realize o pagamento.", payment: "Pagamento", page: "Página", of: "de", records: "registro(s)",
    clearHistoryConfirm: "Excluir todo o histórico? Essa ação não pode ser desfeita.", tryAgain: "tente novamente.", saveError: "Erro ao salvar:", loadError: "Erro ao carregar:", deleteError: "Erro ao excluir:"
  };

  var dynamicPt = {
    plansEyebrow: "PLANOS", plansAndSubscription: "Planos e Assinatura", loading: "Carregando...", startFree: "Começar grátis", subscribeAction: "Assinar", perMonth: "/mês", paymentEyebrow: "PAGAMENTO", planWithLabel: "Plano {label}",
    benefitCalculators: "Calculadoras e escalas gratuitas", benefitFavorites: "Favoritos ilimitados", benefitHistory: "Histórico de navegação", benefitAds: "Exibição de anúncios", benefitNoAds: "Navegação sem anúncios", benefitAllScales: "Todas as escalas e calculadoras", benefitAllQuizzes: "Todos os simulados", benefitAllPleno: "Tudo do plano Pleno", benefitBlankForms: "Formulários de escalas em branco para imprimir e preencher", benefitExcelSchedules: "Escalas de folga e férias semiautomáticas em Excel", benefitExcelScales: "Fugulin, Braden, Morse e Dimensionamento semiautomáticas em Excel", benefitHandouts: "Apostilas e mapa cirúrgico", benefitApk: "Aplicativos APK para assistência",
    planFree: "Gratuito", planJunior: "Júnior", planPleno: "Pleno", planSenior: "Sênior", freePrice: "Grátis",
    statusPending: "Pendente", statusTrial: "Período de teste", statusActive: "Ativa", statusGrace: "Período de carência", statusPaused: "Pausada", statusCancelRequested: "Cancelamento solicitado", statusCancelled: "Cancelada", statusExpired: "Expirada", statusBlocked: "Bloqueada", statusFailed: "Falha",
    paymentUnavailable: "A integração de pagamento (cartão de crédito, PIX e boleto) ainda não está disponível. Esta tela de cobrança é um placeholder e será finalizada na próxima fase do projeto.",
    nurseIllustration: "Ilustração de enfermeira", plansDocumentTitle: "Planos e Assinatura - Calculadoras de Enfermagem", paymentDocumentTitle: "Pagamento - Calculadoras de Enfermagem"
  };
  Object.keys(dynamicPt).forEach(function (key) { pt[key] = dynamicPt[key]; });

  /* Catálogo compacto: a ordem deve acompanhar Object.keys(pt). */
  var keys = Object.keys(pt);
  var translations = {
    en: ["ACCOUNT SYSTEM","My Account","Access your account to save favorites, track your history, and unlock exclusive features.","Sign in to your account","Continue with Google","Continue with Microsoft","Continue with Apple","or","Sign in with email","Full name","Your full name","Email","Password","Your password","Forgot your password?","Create account","Back to sign in","Sign in","Register","Create your account","Reset password","Send recovery link","Enter a valid email.","Complete all required fields.","Password must be at least 6 characters.","Authentication successful.","Recovery instructions were sent to your email.","My Profile","Manage your personal information and account preferences.","Loading your profile…","Display name","Save name","Settings","Sign out","Adjust your account, notification, and privacy preferences.","Preferences","Site language","Light","Dark","Font size","Save preferences","Favorites","Quickly access your favorite calculators, scales, and materials.","My Favorites","Search favorites…","History","Review and reopen your previous calculations and reports.","My History","Search history…","Delete history","← Previous","Next →","All categories","All types","All languages","All","Filter by category","Filter by type","Filter by language","Sort favorites","Premium Subscription","Choose the ideal plan: Free, Junior, Mid-level, or Senior.","Choose your plan","Your subscription","Plan:","Status:","Activate (simulate payment)","Pause","Cancel","Resume","Cancel subscription?","Complete subscription","Review the selected plan and make the payment.","Payment","Page","of","record(s)","Delete all history? This action cannot be undone.","try again.","Error saving:","Error loading:","Error deleting:"],
    es: ["SISTEMA DE CUENTAS","Mi cuenta","Accede a tu cuenta para guardar favoritos, consultar tu historial y desbloquear recursos exclusivos.","Inicia sesión en tu cuenta","Continuar con Google","Continuar con Microsoft","Continuar con Apple","o","Iniciar sesión con correo","Nombre completo","Tu nombre completo","Correo electrónico","Contraseña","Tu contraseña","¿Olvidaste tu contraseña?","Crear cuenta","Volver al inicio","Entrar","Registrarse","Crea tu cuenta","Recuperar contraseña","Enviar enlace de recuperación","Introduce un correo válido.","Completa todos los campos obligatorios.","La contraseña debe tener al menos 6 caracteres.","Autenticación realizada correctamente.","Enviamos las instrucciones de recuperación a tu correo.","Mi perfil","Gestiona tu información personal y preferencias de cuenta.","Cargando tu perfil…","Nombre para mostrar","Guardar nombre","Configuración","Cerrar sesión","Ajusta tus preferencias de cuenta, notificaciones y privacidad.","Preferencias","Idioma del sitio","Claro","Oscuro","Tamaño de fuente","Guardar preferencias","Favoritos","Accede rápidamente a tus calculadoras, escalas y materiales favoritos.","Mis favoritos","Buscar favoritos…","Historial","Consulta y vuelve a abrir tus cálculos e informes anteriores.","Mi historial","Buscar historial…","Eliminar historial","← Anterior","Siguiente →","Todas las categorías","Todos los tipos","Todos los idiomas","Todos","Filtrar por categoría","Filtrar por tipo","Filtrar por idioma","Ordenar favoritos","Suscripción Premium","Elige el plan ideal: Gratuito, Júnior, Pleno o Sénior.","Elige tu plan","Tu suscripción","Plan:","Estado:","Activar (simular pago)","Pausar","Cancelar","Reanudar","¿Cancelar suscripción?","Finalizar suscripción","Revisa el plan elegido y realiza el pago.","Pago","Página","de","registro(s)","¿Eliminar todo el historial? Esta acción no se puede deshacer.","inténtalo de nuevo.","Error al guardar:","Error al cargar:","Error al eliminar:"],
    fr: ["SYSTÈME DE COMPTE","Mon compte","Accédez à votre compte pour enregistrer vos favoris, consulter votre historique et débloquer des fonctions exclusives.","Connectez-vous à votre compte","Continuer avec Google","Continuer avec Microsoft","Continuer avec Apple","ou","Connexion par e-mail","Nom complet","Votre nom complet","E-mail","Mot de passe","Votre mot de passe","Mot de passe oublié ?","Créer un compte","Retour à la connexion","Se connecter","S’inscrire","Créez votre compte","Réinitialiser le mot de passe","Envoyer le lien de récupération","Saisissez un e-mail valide.","Remplissez tous les champs obligatoires.","Le mot de passe doit contenir au moins 6 caractères.","Authentification réussie.","Les instructions ont été envoyées à votre e-mail.","Mon profil","Gérez vos informations personnelles et vos préférences.","Chargement de votre profil…","Nom affiché","Enregistrer le nom","Paramètres","Se déconnecter","Réglez vos préférences de compte, de notification et de confidentialité.","Préférences","Langue du site","Clair","Sombre","Taille de police","Enregistrer les préférences","Favoris","Accédez rapidement à vos calculateurs, échelles et documents favoris.","Mes favoris","Rechercher dans les favoris…","Historique","Consultez et rouvrez vos calculs et rapports précédents.","Mon historique","Rechercher dans l’historique…","Supprimer l’historique","← Précédent","Suivant →","Toutes les catégories","Tous les types","Toutes les langues","Tous","Filtrer par catégorie","Filtrer par type","Filtrer par langue","Trier les favoris","Abonnement Premium","Choisissez la formule idéale : Gratuite, Junior, Intermédiaire ou Senior.","Choisissez votre formule","Votre abonnement","Formule :","Statut :","Activer (simuler le paiement)","Suspendre","Annuler","Reprendre","Annuler l’abonnement ?","Finaliser l’abonnement","Vérifiez la formule choisie et effectuez le paiement.","Paiement","Page","sur","entrée(s)","Supprimer tout l’historique ? Cette action est irréversible.","réessayez.","Erreur d’enregistrement :","Erreur de chargement :","Erreur de suppression :"]
  };

  /* Catálogos próprios dos demais idiomas; nenhuma entrada reutiliza o inglês. */
  var auth = {
    de:["KONTOSYSTEM","Mein Konto","Melden Sie sich an, um Favoriten und Verlauf zu speichern und exklusive Funktionen freizuschalten.","Bei Ihrem Konto anmelden","Weiter mit Google","Weiter mit Microsoft","Weiter mit Apple","oder","Mit E-Mail anmelden","Vollständiger Name","Ihr vollständiger Name","E-Mail","Passwort","Ihr Passwort","Passwort vergessen?","Konto erstellen","Zurück zur Anmeldung","Anmelden","Registrieren","Erstellen Sie Ihr Konto","Passwort zurücksetzen","Wiederherstellungslink senden"],
    it:["SISTEMA ACCOUNT","Il mio account","Accedi per salvare preferiti e cronologia e sbloccare funzioni esclusive.","Accedi al tuo account","Continua con Google","Continua con Microsoft","Continua con Apple","oppure","Accedi con e-mail","Nome completo","Il tuo nome completo","E-mail","Password","La tua password","Password dimenticata?","Crea account","Torna all’accesso","Accedi","Registrati","Crea il tuo account","Recupera password","Invia link di recupero"],
    ja:["アカウントシステム","マイアカウント","ログインしてお気に入りや履歴を保存し、限定機能をご利用ください。","アカウントにログイン","Googleで続ける","Microsoftで続ける","Appleで続ける","または","メールでログイン","氏名","氏名を入力","メールアドレス","パスワード","パスワードを入力","パスワードを忘れた場合","アカウント作成","ログインに戻る","ログイン","登録","アカウントを作成","パスワードを再設定","再設定リンクを送信"],
    zh:["账户系统","我的账户","登录以保存收藏和历史记录并解锁专属功能。","登录您的账户","使用 Google 继续","使用 Microsoft 继续","使用 Apple 继续","或","使用电子邮件登录","姓名","请输入姓名","电子邮件","密码","请输入密码","忘记密码？","创建账户","返回登录","登录","注册","创建您的账户","重置密码","发送恢复链接"],
    hi:["खाता प्रणाली","मेरा खाता","पसंदीदा और इतिहास सहेजने तथा विशेष सुविधाएँ पाने के लिए लॉग इन करें।","अपने खाते में लॉग इन करें","Google से जारी रखें","Microsoft से जारी रखें","Apple से जारी रखें","या","ईमेल से लॉग इन करें","पूरा नाम","आपका पूरा नाम","ईमेल","पासवर्ड","आपका पासवर्ड","पासवर्ड भूल गए?","खाता बनाएँ","लॉगिन पर वापस जाएँ","लॉग इन करें","पंजीकरण करें","अपना खाता बनाएँ","पासवर्ड रीसेट करें","रिकवरी लिंक भेजें"],
    ar:["نظام الحسابات","حسابي","سجّل الدخول لحفظ المفضلة والسجل وفتح الميزات الحصرية.","تسجيل الدخول إلى حسابك","المتابعة باستخدام Google","المتابعة باستخدام Microsoft","المتابعة باستخدام Apple","أو","تسجيل الدخول بالبريد الإلكتروني","الاسم الكامل","اسمك الكامل","البريد الإلكتروني","كلمة المرور","كلمة المرور الخاصة بك","هل نسيت كلمة المرور؟","إنشاء حساب","العودة لتسجيل الدخول","تسجيل الدخول","التسجيل","أنشئ حسابك","إعادة تعيين كلمة المرور","إرسال رابط الاسترداد"],
    ru:["СИСТЕМА УЧЁТНЫХ ЗАПИСЕЙ","Моя учётная запись","Войдите, чтобы сохранять избранное и историю и открыть эксклюзивные функции.","Войти в учётную запись","Продолжить с Google","Продолжить с Microsoft","Продолжить с Apple","или","Войти по электронной почте","Полное имя","Ваше полное имя","Эл. почта","Пароль","Ваш пароль","Забыли пароль?","Создать учётную запись","Вернуться ко входу","Войти","Зарегистрироваться","Создайте учётную запись","Сбросить пароль","Отправить ссылку восстановления"],
    tr:["HESAP SİSTEMİ","Hesabım","Favorileri ve geçmişi kaydetmek, özel özelliklere erişmek için giriş yapın.","Hesabınıza giriş yapın","Google ile devam et","Microsoft ile devam et","Apple ile devam et","veya","E-posta ile giriş yap","Ad soyad","Adınız ve soyadınız","E-posta","Şifre","Şifreniz","Şifrenizi mi unuttunuz?","Hesap oluştur","Girişe dön","Giriş yap","Kaydol","Hesabınızı oluşturun","Şifreyi sıfırla","Kurtarma bağlantısı gönder"],
    ko:["계정 시스템","내 계정","로그인하여 즐겨찾기와 기록을 저장하고 전용 기능을 이용하세요.","계정에 로그인","Google로 계속","Microsoft로 계속","Apple로 계속","또는","이메일로 로그인","이름","이름 입력","이메일","비밀번호","비밀번호 입력","비밀번호를 잊으셨나요?","계정 만들기","로그인으로 돌아가기","로그인","가입","계정 만들기","비밀번호 재설정","복구 링크 보내기"],
    nl:["ACCOUNTSYSTEEM","Mijn account","Log in om favorieten en geschiedenis op te slaan en exclusieve functies te ontgrendelen.","Log in op uw account","Doorgaan met Google","Doorgaan met Microsoft","Doorgaan met Apple","of","Inloggen met e-mail","Volledige naam","Uw volledige naam","E-mail","Wachtwoord","Uw wachtwoord","Wachtwoord vergeten?","Account maken","Terug naar inloggen","Inloggen","Registreren","Maak uw account","Wachtwoord herstellen","Herstellink verzenden"],
    pl:["SYSTEM KONTA","Moje konto","Zaloguj się, aby zapisywać ulubione i historię oraz odblokować wyjątkowe funkcje.","Zaloguj się na konto","Kontynuuj z Google","Kontynuuj z Microsoft","Kontynuuj z Apple","lub","Zaloguj się przez e-mail","Imię i nazwisko","Twoje imię i nazwisko","E-mail","Hasło","Twoje hasło","Nie pamiętasz hasła?","Utwórz konto","Wróć do logowania","Zaloguj się","Zarejestruj się","Utwórz konto","Zresetuj hasło","Wyślij link odzyskiwania"],
    sv:["KONTOSYSTEM","Mitt konto","Logga in för att spara favoriter och historik och låsa upp exklusiva funktioner.","Logga in på ditt konto","Fortsätt med Google","Fortsätt med Microsoft","Fortsätt med Apple","eller","Logga in med e-post","Fullständigt namn","Ditt fullständiga namn","E-post","Lösenord","Ditt lösenord","Glömt lösenordet?","Skapa konto","Tillbaka till inloggning","Logga in","Registrera","Skapa ditt konto","Återställ lösenord","Skicka återställningslänk"],
    id:["SISTEM AKUN","Akun Saya","Masuk untuk menyimpan favorit dan riwayat serta membuka fitur eksklusif.","Masuk ke akun Anda","Lanjutkan dengan Google","Lanjutkan dengan Microsoft","Lanjutkan dengan Apple","atau","Masuk dengan email","Nama lengkap","Nama lengkap Anda","Email","Kata sandi","Kata sandi Anda","Lupa kata sandi?","Buat akun","Kembali ke masuk","Masuk","Daftar","Buat akun Anda","Atur ulang kata sandi","Kirim tautan pemulihan"],
    vi:["HỆ THỐNG TÀI KHOẢN","Tài khoản của tôi","Đăng nhập để lưu mục yêu thích, lịch sử và mở khóa tính năng độc quyền.","Đăng nhập vào tài khoản","Tiếp tục với Google","Tiếp tục với Microsoft","Tiếp tục với Apple","hoặc","Đăng nhập bằng email","Họ và tên","Họ và tên của bạn","Email","Mật khẩu","Mật khẩu của bạn","Quên mật khẩu?","Tạo tài khoản","Quay lại đăng nhập","Đăng nhập","Đăng ký","Tạo tài khoản","Đặt lại mật khẩu","Gửi liên kết khôi phục"],
    uk:["СИСТЕМА ОБЛІКОВИХ ЗАПИСІВ","Мій обліковий запис","Увійдіть, щоб зберігати обране й історію та відкрити ексклюзивні функції.","Увійти до облікового запису","Продовжити з Google","Продовжити з Microsoft","Продовжити з Apple","або","Увійти через електронну пошту","Повне ім’я","Ваше повне ім’я","Ел. пошта","Пароль","Ваш пароль","Забули пароль?","Створити обліковий запис","Повернутися до входу","Увійти","Зареєструватися","Створіть обліковий запис","Скинути пароль","Надіслати посилання відновлення"]
  };
  var secondaryTranslations = {
    de: ["Bitte geben Sie eine gültige E-Mail-Adresse ein.","Bitte füllen Sie alle Pflichtfelder aus.","Das Passwort muss mindestens 6 Zeichen lang sein.","Authentifizierung erfolgreich.","Wir haben die Anweisungen zur Wiederherstellung an Ihre E-Mail-Adresse gesendet.","Mein Profil","Verwalten Sie Ihre persönlichen Daten und Kontoeinstellungen.","Profil wird geladen…","Anzeigename","Namen speichern","Einstellungen","Abmelden","Passen Sie Ihre Kontoeinstellungen, Benachrichtigungen und Datenschutzeinstellungen an.","Einstellungen","Sprache der Website","Hell","Dunkel","Schriftgröße","Einstellungen speichern","Favoriten","Greifen Sie schnell auf Ihre bevorzugten Rechner, Skalen und Materialien zu.","Meine Favoriten","Favoriten durchsuchen…","Verlauf","Sehen Sie alle Ihre früheren Berechnungen und Berichte ein und rufen Sie sie erneut auf.","Mein Verlauf","Verlauf durchsuchen…","Verlauf löschen","← Zurück","Weiter →","Alle Kategorien","Alle Typen","Alle Sprachen","Alle","Nach Kategorie filtern","Nach Typ filtern","Nach Sprache filtern","Favoriten sortieren","Premium-Abo","Wählen Sie den idealen Plan: Kostenlos, Junior, Voll oder Senior.","Wählen Sie Ihren Plan","Ihr Abo","Plan:","Status:","Aktivieren (Zahlung simulieren)","Pausieren","Kündigen","Fortsetzen","Abo kündigen?","Abo abschließen","Überprüfen Sie den gewählten Plan und führen Sie die Zahlung durch.","Zahlung","Seite","von","Datensatz/Datensätze","Gesamten Verlauf löschen? Diese Aktion kann nicht rückgängig gemacht werden.","Bitte versuchen Sie es erneut.","Fehler beim Speichern:","Fehler beim Laden:","Fehler beim Löschen:"],
    it: ["Inserisci un'email valida.","Compila tutti i campi obbligatori.","La password deve avere almeno 6 caratteri.","Autenticazione riuscita.","Abbiamo inviato le istruzioni di recupero alla tua email.","Il mio profilo","Gestisci le tue informazioni personali e le preferenze dell'account.","Caricamento del profilo…","Nome visualizzato","Salva nome","Impostazioni","Esci dall'account","Regola le preferenze di account, notifiche e privacy.","Preferenze","Lingua del sito","Chiaro","Scuro","Dimensione del carattere","Salva preferenze","Preferiti","Accedi rapidamente a calcolatrici, scale e materiali preferiti.","I miei preferiti","Cerca nei preferiti…","Cronologia","Consulta e accedi di nuovo a tutti i tuoi calcoli e referti precedenti.","La mia cronologia","Cerca nella cronologia…","Elimina cronologia","← Precedente","Successiva →","Tutte le categorie","Tutti i tipi","Tutte le lingue","Tutti","Filtra per categoria","Filtra per tipo","Filtra per lingua","Ordina preferiti","Abbonamento Premium","Scegli il piano ideale: Gratuito, Junior, Pleno o Senior.","Scegli il tuo piano","Il tuo abbonamento","Piano:","Stato:","Attiva (simula pagamento)","Pausa","Annulla","Riprendi","Annullare l'abbonamento?","Completa l'abbonamento","Controlla il piano scelto e effettua il pagamento.","Pagamento","Pagina","di","record","Eliminare tutta la cronologia? Questa azione non può essere annullata.","riprova.","Errore durante il salvataggio:","Errore durante il caricamento:","Errore durante l'eliminazione:"],
    ja: ["有効なメールアドレスを入力してください。","必須項目をすべて入力してください。","パスワードは6文字以上である必要があります。","認証に成功しました。","回復手順をメールで送信しました。","マイプロフィール","個人情報とアカウント設定を管理します。","プロフィールを読み込んでいます…","表示名","名前を保存","設定","ログアウト","アカウント、通知、プライバシーの設定を調整します。","環境設定","サイトの言語","ライト","ダーク","フォントサイズ","環境設定を保存","お気に入り","お気に入りの計算機、スケール、資料にすばやくアクセスします。","マイお気に入り","お気に入りを検索…","履歴","過去の計算やレポートを確認して再度アクセスします。","マイ履歴","履歴を検索…","履歴を削除","← 前へ","次へ →","すべてのカテゴリ","すべてのタイプ","すべての言語","すべて","カテゴリで絞り込み","タイプで絞り込み","言語で絞り込み","お気に入りを並べ替え","プレミアムサブスクリプション","無料、ジュニア、プレノ、シニアのプランから選択してください。","プランを選択","あなたのサブスクリプション","プラン：","ステータス：","アクティブ化（支払いをシミュレート）","一時停止","キャンセル","再開","サブスクリプションをキャンセルしますか？","サブスクリプションを完了","選択したプランを確認し、支払いを行います。","支払い","ページ","/","件","履歴をすべて削除しますか？この操作は元に戻せません。","もう一度お試しください。","保存エラー：","読み込みエラー：","削除エラー："],
    zh: ["请输入有效的电子邮件地址。","请填写所有必填字段。","密码至少需要6个字符。","身份验证成功。","我们已将恢复说明发送到您的电子邮件。","我的个人资料","管理您的个人信息和账户偏好。","正在加载您的个人资料…","显示名称","保存名称","设置","退出账户","调整您的账户、通知和隐私偏好。","偏好设置","网站语言","浅色","深色","字体大小","保存偏好设置","收藏","快速访问您收藏的计算器、量表和材料。","我的收藏","搜索收藏…","历史记录","查看并重新访问您之前的所有计算和报告。","我的历史记录","搜索历史记录…","删除历史记录","← 上一页","下一页 →","所有类别","所有类型","所有语言","全部","按类别筛选","按类型筛选","按语言筛选","排序收藏","高级订阅","选择理想方案：免费、初级、中级或高级。","选择您的方案","您的订阅","方案：","状态：","激活（模拟支付）","暂停","取消","恢复","取消订阅？","完成订阅","确认所选方案并完成支付。","支付","页","共","条记录","删除所有历史记录？此操作无法撤销。","请重试。","保存错误：","加载错误：","删除错误："],
    hi: ["कृपया एक मान्य ईमेल दर्ज करें।","कृपया सभी आवश्यक फ़ील्ड भरें।","पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।","प्रमाणीकरण सफलतापूर्वक पूरा हुआ।","हमने आपके ईमेल पर पुनर्प्राप्ति निर्देश भेज दिए हैं।","मेरी प्रोफ़ाइल","अपनी व्यक्तिगत जानकारी और खाता प्राथमिकताएँ प्रबंधित करें।","आपकी प्रोफ़ाइल लोड हो रही है…","प्रदर्शन नाम","नाम सहेजें","सेटिंग्स","साइन आउट करें","अपनी खाता, सूचना और गोपनीयता प्राथमिकताएँ समायोजित करें।","प्राथमिकताएँ","साइट की भाषा","हल्का","गहरा","फ़ॉन्ट आकार","प्राथमिकताएँ सहेजें","पसंदीदा","अपने पसंदीदा कैलकुलेटर, स्केल और सामग्री तक त्वरित पहुँच प्राप्त करें।","मेरे पसंदीदा","पसंदीदा खोजें…","इतिहास","अपने पिछले सभी गणनाओं और रिपोर्टों को देखें और फिर से एक्सेस करें।","मेरा इतिहास","इतिहास खोजें…","इतिहास हटाएँ","← पिछला","अगला →","सभी श्रेणियाँ","सभी प्रकार","सभी भाषाएँ","सभी","श्रेणी द्वारा फ़िल्टर करें","प्रकार द्वारा फ़िल्टर करें","भाषा द्वारा फ़िल्टर करें","पसंदीदा क्रमबद्ध करें","प्रीमियम सदस्यता","आदर्श योजना चुनें: निःशुल्क, जूनियर, प्लेनो या सीनियर।","अपनी योजना चुनें","आपकी सदस्यता","योजना:","स्थिति:","सक्रिय करें (भुगतान अनुकरण करें)","रोकें","रद्द करें","फिर से शुरू करें","सदस्यता रद्द करें?","सदस्यता पूर्ण करें","चुनी गई योजना की जाँच करें और भुगतान करें।","भुगतान","पृष्ठ","का","रिकॉर्ड","पूरा इतिहास हटाएँ? यह क्रिया पूर्ववत नहीं की जा सकती।","पुनः प्रयास करें।","सहेजने में त्रुटि:","लोड करने में त्रुटि:","हटाने में त्रुटि:"],
    ar: ["يرجى إدخال بريد إلكتروني صالح.","يرجى ملء جميع الحقول المطلوبة.","يجب أن تتكون كلمة المرور من 6 أحرف على الأقل.","تم تسجيل الدخول بنجاح.","لقد أرسلنا تعليمات الاسترداد إلى بريدك الإلكتروني.","ملفي الشخصي","إدارة معلوماتك الشخصية وتفضيلات الحساب.","جارٍ تحميل ملفك الشخصي…","الاسم المعروض","حفظ الاسم","الإعدادات","تسجيل الخروج","اضبط تفضيلات حسابك والإشعارات والخصوصية.","التفضيلات","لغة الموقع","فاتح","داكن","حجم الخط","حفظ التفضيلات","المفضلة","الوصول السريع إلى الآلات الحاسبة والمقاييس والمواد المفضلة لديك.","مفضلتي","البحث في المفضلة…","السجل","عرض وإعادة الوصول إلى جميع حساباتك وتقاريرك السابقة.","سجلي","البحث في السجل…","حذف السجل","→ السابق","التالي ←","جميع الفئات","جميع الأنواع","جميع اللغات","الكل","تصفية حسب الفئة","تصفية حسب النوع","تصفية حسب اللغة","ترتيب المفضلة","الاشتراك المميز","اختر الخطة المثالية: مجاني، مبتدئ، محترف، أو خبير.","اختر خطتك","اشتراكك","الخطة:","الحالة:","تفعيل (محاكاة الدفع)","إيقاف مؤقت","إلغاء","استئناف","إلغاء الاشتراك؟","إتمام الاشتراك","راجع الخطة المختارة وقم بالدفع.","الدفع","صفحة","من","سجل(ات)","حذف كل السجل؟ لا يمكن التراجع عن هذا الإجراء.","حاول مرة أخرى.","خطأ في الحفظ:","خطأ في التحميل:","خطأ في الحذف:"],
    ru: ["Укажите действительный адрес электронной почты.","Заполните все обязательные поля.","Пароль должен содержать не менее 6 символов.","Аутентификация прошла успешно.","Мы отправили инструкции по восстановлению на вашу электронную почту.","Мой профиль","Управляйте своей личной информацией и настройками учетной записи.","Загрузка профиля…","Отображаемое имя","Сохранить имя","Настройки","Выйти из аккаунта","Настройте параметры учетной записи, уведомления и конфиденциальность.","Предпочтения","Язык сайта","Светлая","Темная","Размер шрифта","Сохранить предпочтения","Избранное","Быстрый доступ к вашим избранным калькуляторам, шкалам и материалам.","Мое избранное","Поиск в избранном…","История","Просматривайте и повторно открывайте все свои предыдущие расчеты и отчеты.","Моя история","Поиск в истории…","Удалить историю","← Назад","Вперед →","Все категории","Все типы","Все языки","Все","Фильтр по категории","Фильтр по типу","Фильтр по языку","Сортировать избранное","Премиум-подписка","Выберите подходящий план: Бесплатный, Младший, Полный или Старший.","Выберите свой план","Ваша подписка","План:","Статус:","Активировать (имитировать оплату)","Приостановить","Отменить","Возобновить","Отменить подписку?","Оформить подписку","Проверьте выбранный план и произведите оплату.","Оплата","Страница","из","записей(и)","Удалить всю историю? Это действие необратимо.","попробуйте снова.","Ошибка при сохранении:","Ошибка при загрузке:","Ошибка при удалении:"],
    tr: ["Geçerli bir e-posta adresi girin.","Lütfen tüm zorunlu alanları doldurun.","Şifre en az 6 karakter olmalıdır.","Kimlik doğrulama başarıyla gerçekleştirildi.","Kurtarma talimatlarını e-postanıza gönderdik.","Profilim","Kişisel bilgilerinizi ve hesap tercihlerinizi yönetin.","Profiliniz yükleniyor…","Görünen ad","Adı kaydet","Ayarlar","Oturumu kapat","Hesap tercihlerinizi, bildirimlerinizi ve gizliliğinizi ayarlayın.","Tercihler","Site dili","Açık","Koyu","Yazı boyutu","Tercihleri kaydet","Favoriler","Favori hesaplayıcılarınıza, ölçeklerinize ve materyallerinize hızlıca erişin.","Favorilerim","Favorilerde ara…","Geçmiş","Önceki tüm hesaplamalarınızı ve raporlarınızı görüntüleyin ve tekrar erişin.","Geçmişim","Geçmişte ara…","Geçmişi sil","← Önceki","Sonraki →","Tüm kategoriler","Tüm türler","Tüm diller","Tümü","Kategoriye göre filtrele","Türe göre filtrele","Dile göre filtrele","Favorileri sırala","Premium Abonelik","İdeal planı seçin: Ücretsiz, Junior, Senior veya Uzman.","Planınızı seçin","Aboneliğiniz","Plan:","Durum:","Etkinleştir (ödeme simülasyonu)","Duraklat","İptal et","Sürdür","Abonelik iptal edilsin mi?","Aboneliği tamamla","Seçilen planı kontrol edin ve ödemeyi gerçekleştirin.","Ödeme","Sayfa","/","kayıt","Tüm geçmiş silinsin mi? Bu işlem geri alınamaz.","tekrar deneyin.","Kaydedilirken hata oluştu:","Yüklenirken hata oluştu:","Silinirken hata oluştu:"],
    ko: ["유효한 이메일을 입력하세요.","모든 필수 항목을 입력하세요.","비밀번호는 최소 6자 이상이어야 합니다.","인증에 성공했습니다.","복구 지침을 이메일로 보냈습니다.","내 프로필","개인 정보 및 계정 기본 설정을 관리하세요.","프로필을 불러오는 중…","표시 이름","이름 저장","설정","로그아웃","계정, 알림 및 개인정보 기본 설정을 조정하세요.","기본 설정","사이트 언어","라이트","다크","글꼴 크기","기본 설정 저장","즐겨찾기","즐겨찾는 계산기, 척도 및 자료에 빠르게 접근하세요.","내 즐겨찾기","즐겨찾기 검색…","기록","이전의 모든 계산 및 보고서를 확인하고 다시 접근하세요.","내 기록","기록 검색…","기록 삭제","← 이전","다음 →","모든 카테고리","모든 유형","모든 언어","모두","카테고리로 필터링","유형으로 필터링","언어로 필터링","즐겨찾기 정렬","프리미엄 구독","무료, 주니어, 플레노 또는 시니어 중에서 선택하세요.","플랜 선택","내 구독","플랜:","상태:","활성화 (결제 시뮬레이션)","일시 중지","취소","재개","구독을 취소하시겠습니까?","구독 완료","선택한 플랜을 확인하고 결제를 진행하세요.","결제","페이지","/","건","전체 기록을 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.","다시 시도하세요.","저장 오류:","불러오기 오류:","삭제 오류:"],
    nl: ["Geef een geldig e-mailadres op.","Vul alle verplichte velden in.","Het wachtwoord moet minimaal 6 tekens bevatten.","Authenticatie succesvol uitgevoerd.","We hebben de herstel instructies naar uw e-mail gestuurd.","Mijn profiel","Beheer uw persoonlijke gegevens en accountvoorkeuren.","Uw profiel laden…","Weergavenaam","Naam opslaan","Instellingen","Uitloggen","Pas uw account-, meldings- en privacyvoorkeuren aan.","Voorkeuren","Website taal","Licht","Donker","Lettergrootte","Voorkeuren opslaan","Favorieten","Krijg snel toegang tot uw favoriete rekenmachines, schalen en materialen.","Mijn favorieten","Favorieten zoeken…","Geschiedenis","Bekijk en open al uw eerdere berekeningen en rapporten opnieuw.","Mijn geschiedenis","Geschiedenis zoeken…","Geschiedenis verwijderen","← Vorige","Volgende →","Alle categorieën","Alle typen","Alle talen","Alle","Filteren op categorie","Filteren op type","Filteren op taal","Favorieten sorteren","Premium abonnement","Kies het ideale plan: Gratis, Junior, Senior of Expert.","Kies uw plan","Uw abonnement","Plan:","Status:","Activeren (simuleer betaling)","Pauzeren","Annuleren","Hervatten","Abonnement annuleren?","Abonnement afronden","Controleer het gekozen plan en voltooi de betaling.","Betaling","Pagina","van","record(s)","Geschiedenis volledig verwijderen? Deze actie kan niet ongedaan worden gemaakt.","probeer het opnieuw.","Fout bij opslaan:","Fout bij laden:","Fout bij verwijderen:"],
    pl: ["Podaj prawidłowy adres e-mail.","Wypełnij wszystkie wymagane pola.","Hasło musi mieć co najmniej 6 znaków.","Uwierzytelnienie zakończone sukcesem.","Wysłaliśmy instrukcje odzyskiwania na Twój adres e-mail.","Mój profil","Zarządzaj swoimi danymi osobowymi i preferencjami konta.","Ładowanie profilu…","Wyświetlana nazwa","Zapisz nazwę","Ustawienia","Wyloguj się","Dostosuj preferencje konta, powiadomienia i prywatność.","Preferencje","Język strony","Jasny","Ciemny","Rozmiar czcionki","Zapisz preferencje","Ulubione","Szybki dostęp do ulubionych kalkulatorów, skal i materiałów.","Moje ulubione","Szukaj w ulubionych…","Historia","Przeglądaj i ponownie uzyskuj dostęp do wszystkich poprzednich obliczeń i raportów.","Moja historia","Szukaj w historii…","Usuń historię","← Poprzednia","Następna →","Wszystkie kategorie","Wszystkie typy","Wszystkie języki","Wszystkie","Filtruj według kategorii","Filtruj według typu","Filtruj według języka","Sortuj ulubione","Subskrypcja Premium","Wybierz idealny plan: Bezpłatny, Junior, Pełny lub Senior.","Wybierz swój plan","Twoja subskrypcja","Plan:","Status:","Aktywuj (symuluj płatność)","Wstrzymaj","Anuluj","Wznów","Anulować subskrypcję?","Sfinalizuj subskrypcję","Sprawdź wybrany plan i dokonaj płatności.","Płatność","Strona","z","rekord(y)","Usunąć całą historię? Tej operacji nie można cofnąć.","spróbuj ponownie.","Błąd podczas zapisywania:","Błąd podczas ładowania:","Błąd podczas usuwania:"],
    sv: ["Ange en giltig e-postadress.","Fyll i alla obligatoriska fält.","Lösenordet måste vara minst 6 tecken långt.","Autentisering lyckades.","Vi har skickat återställningsinstruktioner till din e-post.","Min profil","Hantera dina personuppgifter och kontoinställningar.","Laddar din profil...","Visningsnamn","Spara namn","Inställningar","Logga ut","Justera dina konto-, aviserings- och sekretessinställningar.","Inställningar","Webbplatsens språk","Ljust","Mörkt","Teckenstorlek","Spara inställningar","Favoriter","Få snabb åtkomst till dina favoritkalkylatorer, skalor och material.","Mina favoriter","Sök favoriter...","Historik","Visa och kom åt alla dina tidigare beräkningar och rapporter.","Min historik","Sök historik...","Radera historik","← Föregående","Nästa →","Alla kategorier","Alla typer","Alla språk","Alla","Filtrera efter kategori","Filtrera efter typ","Filtrera efter språk","Sortera favoriter","Premiumprenumeration","Välj den plan som passar dig: Gratis, Junior, Full eller Senior.","Välj din plan","Din prenumeration","Plan:","Status:","Aktivera (simulera betalning)","Pausa","Avbryt","Återuppta","Avbryta prenumerationen?","Slutför prenumeration","Granska den valda planen och genomför betalningen.","Betalning","Sida","av","post(er)","Radera hela historiken? Denna åtgärd kan inte ångras.","försök igen.","Fel vid sparande:","Fel vid inläsning:","Fel vid radering:"],
    id: ["Masukkan email yang valid.","Lengkapi semua kolom wajib.","Kata sandi harus memiliki minimal 6 karakter.","Autentikasi berhasil.","Kami telah mengirimkan instruksi pemulihan ke email Anda.","Profil Saya","Kelola informasi pribadi dan preferensi akun Anda.","Memuat profil Anda…","Nama tampilan","Simpan nama","Pengaturan","Keluar","Sesuaikan preferensi akun, notifikasi, dan privasi Anda.","Preferensi","Bahasa situs","Terang","Gelap","Ukuran font","Simpan preferensi","Favorit","Akses cepat kalkulator, skala, dan materi favorit Anda.","Favorit Saya","Cari favorit…","Riwayat","Lihat dan akses kembali semua perhitungan dan laporan Anda sebelumnya.","Riwayat Saya","Cari riwayat…","Hapus riwayat","← Sebelumnya","Berikutnya →","Semua kategori","Semua jenis","Semua bahasa","Semua","Filter berdasarkan kategori","Filter berdasarkan jenis","Filter berdasarkan bahasa","Urutkan favorit","Langganan Premium","Pilih paket yang ideal: Gratis, Junior, Madya, atau Senior.","Pilih paket Anda","Langganan Anda","Paket:","Status:","Aktifkan (simulasi pembayaran)","Jeda","Batalkan","Lanjutkan","Batalkan langganan?","Selesaikan langganan","Periksa paket yang dipilih dan lakukan pembayaran.","Pembayaran","Halaman","dari","catatan","Hapus semua riwayat? Tindakan ini tidak dapat dibatalkan.","coba lagi.","Kesalahan saat menyimpan:","Kesalahan saat memuat:","Kesalahan saat menghapus:"],
    vi: ["Vui lòng nhập email hợp lệ.","Vui lòng điền tất cả các trường bắt buộc.","Mật khẩu phải có ít nhất 6 ký tự.","Xác thực thành công.","Chúng tôi đã gửi hướng dẫn khôi phục đến email của bạn.","Hồ sơ của tôi","Quản lý thông tin cá nhân và tùy chọn tài khoản của bạn.","Đang tải hồ sơ của bạn…","Tên hiển thị","Lưu tên","Cài đặt","Đăng xuất","Điều chỉnh tùy chọn tài khoản, thông báo và quyền riêng tư của bạn.","Tùy chọn","Ngôn ngữ trang web","Sáng","Tối","Cỡ chữ","Lưu tùy chọn","Yêu thích","Truy cập nhanh vào máy tính, thang điểm và tài liệu yêu thích của bạn.","Yêu thích của tôi","Tìm kiếm yêu thích…","Lịch sử","Xem và truy cập lại tất cả các phép tính và báo cáo trước đây của bạn.","Lịch sử của tôi","Tìm kiếm lịch sử…","Xóa lịch sử","← Trước","Tiếp →","Tất cả danh mục","Tất cả loại","Tất cả ngôn ngữ","Tất cả","Lọc theo danh mục","Lọc theo loại","Lọc theo ngôn ngữ","Sắp xếp yêu thích","Gói Premium","Chọn gói phù hợp: Miễn phí, Junior, Pleno hoặc Senior.","Chọn gói của bạn","Gói của bạn","Gói:","Trạng thái:","Kích hoạt (mô phỏng thanh toán)","Tạm dừng","Hủy","Tiếp tục","Hủy gói?","Hoàn tất đăng ký","Xem lại gói đã chọn và thực hiện thanh toán.","Thanh toán","Trang","của","bản ghi","Xóa toàn bộ lịch sử? Hành động này không thể hoàn tác.","vui lòng thử lại.","Lỗi khi lưu:","Lỗi khi tải:","Lỗi khi xóa:"],
    uk: ["Вкажіть дійсну електронну пошту.","Заповніть усі обов'язкові поля.","Пароль має містити щонайменше 6 символів.","Автентифікацію виконано успішно.","Ми надіслали інструкції з відновлення на вашу електронну пошту.","Мій профіль","Керуйте своєю особистою інформацією та налаштуваннями облікового запису.","Завантаження вашого профілю…","Відображуване ім'я","Зберегти ім'я","Налаштування","Вийти з облікового запису","Налаштуйте параметри облікового запису, сповіщення та конфіденційність.","Уподобання","Мова сайту","Світла","Темна","Розмір шрифту","Зберегти уподобання","Обране","Швидкий доступ до ваших улюблених калькуляторів, шкал і матеріалів.","Моє обране","Пошук в обраному…","Історія","Переглядайте та повторно відкривайте всі свої попередні розрахунки та звіти.","Моя історія","Пошук в історії…","Видалити історію","← Попередня","Наступна →","Усі категорії","Усі типи","Усі мови","Усі","Фільтрувати за категорією","Фільтрувати за типом","Фільтрувати за мовою","Сортувати обране","Преміум-підписка","Виберіть ідеальний план: Безкоштовний, Молодший, Повний або Старший.","Виберіть свій план","Ваша підписка","План:","Статус:","Активувати (імітувати оплату)","Призупинити","Скасувати","Відновити","Скасувати підписку?","Оформити підписку","Перевірте вибраний план і здійсніть оплату.","Оплата","Сторінка","з","запис(ів)","Видалити всю історію? Цю дію не можна скасувати.","спробуйте ще раз.","Помилка збереження:","Помилка завантаження:","Помилка видалення:"]
  };
  Object.keys(auth).forEach(function (code) {
    translations[code] = auth[code];
    Array.prototype.push.apply(translations[code], secondaryTranslations[code]);
  });

  var dynamicTranslations = {
    en: ["PLANS","Plans and Subscription","Loading...","Start free","Subscribe","/month","PAYMENT","Plan {label}","Free calculators and scales","Unlimited favorites","Browsing history","Ad display","Ad-free browsing","All scales and calculators","All mock exams","Everything in the Pleno plan","Blank scale forms to print and fill in","Semi-automatic time-off and vacation schedules in Excel","Fugulin, Braden, Morse, and Staffing semi-automatic in Excel","Handouts and surgical map","APK apps for assistance","Free","Junior","Pleno","Senior","Free","Pending","Trial period","Active","Grace period","Paused","Cancellation requested","Cancelled","Expired","Blocked","Failed","The payment integration (credit card, PIX, and bank slip) is not yet available. This billing screen is a placeholder and will be finalized in the next phase of the project.","Nurse illustration","Plans and Subscription - Nursing Calculators","Payment - Nursing Calculators"],
    es: ["PLANES","Planes y Suscripción","Cargando...","Empezar gratis","Suscribirse","/mes","PAGO","Plan {label}","Calculadoras y escalas gratuitas","Favoritos ilimitados","Historial de navegación","Visualización de anuncios","Navegación sin anuncios","Todas las escalas y calculadoras","Todos los simulacros","Todo del plan Pleno","Formularios de escalas en blanco para imprimir y completar","Escalas de descanso y vacaciones semiautomáticas en Excel","Fugulin, Braden, Morse y Dimensionamiento semiautomáticos en Excel","Apuntes y mapa quirúrgico","Aplicaciones APK para asistencia","Gratuito","Junior","Pleno","Senior","Gratis","Pendiente","Período de prueba","Activa","Período de gracia","Pausada","Cancelación solicitada","Cancelada","Expirada","Bloqueada","Fallida","La integración de pago (tarjeta de crédito, PIX y boleto) aún no está disponible. Esta pantalla de cobro es un marcador de posición y se finalizará en la próxima fase del proyecto.","Ilustración de enfermera","Planes y Suscripción - Calculadoras de Enfermería","Pago - Calculadoras de Enfermería"],
    fr: ["PLANS","Plans et abonnement","Chargement...","Commencer gratuitement","S'abonner","/mois","PAIEMENT","Plan {label}","Calculatrices et échelles gratuites","Favoris illimités","Historique de navigation","Affichage de publicités","Navigation sans publicités","Toutes les échelles et calculatrices","Tous les examens blancs","Tout du plan Pleno","Formulaires d'échelles vierges à imprimer et à remplir","Échelles de congés et de vacances semi-automatiques dans Excel","Fugulin, Braden, Morse et Dimensionnement semi-automatiques dans Excel","Supports de cours et carte chirurgicale","Applications APK pour les soins","Gratuit","Junior","Pleno","Senior","Gratuit","En attente","Période d'essai","Active","Période de grâce","En pause","Annulation demandée","Annulée","Expirée","Bloquée","Échec","L'intégration du paiement (carte de crédit, PIX et billet) n'est pas encore disponible. Cet écran de facturation est un espace réservé et sera finalisé dans la prochaine phase du projet.","Illustration d'infirmière","Plans et abonnement - Calculatrices de soins infirmiers","Paiement - Calculatrices de soins infirmiers"],
    de: ["TARIFE","Tarife und Abonnement","Wird geladen...","Kostenlos starten","Abonnieren","/Monat","ZAHLUNG","Tarif {label}","Kostenlose Rechner und Skalen","Unbegrenzte Favoriten","Browserverlauf","Anzeigen einblenden","Werbefreies Surfen","Alle Skalen und Rechner","Alle Übungstests","Alles aus dem Pleno-Tarif","Leere Skalenformulare zum Ausdrucken und Ausfüllen","Halbautomatische Dienst- und Urlaubspläne in Excel","Fugulin, Braden, Morse und Dimensionierung halbautomatisch in Excel","Skripte und chirurgische Karte","APK-Apps für die Pflege","Kostenlos","Junior","Pleno","Senior","Kostenlos","Ausstehend","Testzeitraum","Aktiv","Nachfrist","Pausiert","Kündigung beantragt","Gekündigt","Abgelaufen","Gesperrt","Fehlgeschlagen","Die Zahlungsintegration (Kreditkarte, PIX und Rechnung) ist noch nicht verfügbar. Dieser Abrechnungsbildschirm ist ein Platzhalter und wird in der nächsten Projektphase fertiggestellt.","Illustration einer Krankenschwester","Tarife und Abonnement - Pflege-Rechner","Zahlung - Pflege-Rechner"],
    it: ["PIANI","Piani e abbonamento","Caricamento...","Inizia gratis","Abbonati","/mese","PAGAMENTO","Piano {label}","Calcolatrici e scale gratuite","Preferiti illimitati","Cronologia di navigazione","Visualizzazione di annunci","Navigazione senza pubblicità","Tutte le scale e calcolatrici","Tutti i simulati","Tutto del piano Pleno","Moduli di scale in bianco da stampare e compilare","Scale di riposo e ferie semiautomatiche in Excel","Fugulin, Braden, Morse e Dimensionamento semiautomatiche in Excel","Dispense e mappa chirurgica","App APK per l'assistenza","Gratuito","Junior","Pleno","Senior","Gratis","In attesa","Periodo di prova","Attiva","Periodo di grazia","In pausa","Cancellazione richiesta","Annullata","Scaduta","Bloccata","Fallita","L'integrazione del pagamento (carta di credito, PIX e boleto) non è ancora disponibile. Questa schermata di fatturazione è un segnaposto e sarà completata nella prossima fase del progetto.","Illustrazione di infermiera","Piani e abbonamento - Calcolatrici di Infermieristica","Pagamento - Calcolatrici di Infermieristica"],
    ja: ["プラン","プランとサブスクリプション","読み込み中...","無料で始める","登録する","/月","支払い","プラン {label}","無料の計算機とスケール","無制限のお気に入り","閲覧履歴","広告の表示","広告なしのブラウジング","すべてのスケールと計算機","すべての模擬試験","Plenoプランのすべて","印刷して記入するための空白のスケールフォーム","Excelでの半自動の休暇・休日スケジュール","Excelでの半自動のFugulin、Braden、Morse、および人員配置","教材と外科用マップ","ケア用のAPKアプリ","無料","ジュニア","プレノ","シニア","無料","保留中","試用期間","アクティブ","猶予期間","一時停止","解約リクエスト済み","解約済み","期限切れ","ブロック済み","失敗","支払い統合（クレジットカード、PIX、バーコード）はまだ利用できません。この請求画面はプレースホルダーであり、プロジェクトの次のフェーズで完成予定です。","看護師のイラスト","プランとサブスクリプション - 看護計算機","支払い - 看護計算機"],
    zh: ["计划","计划和订阅","加载中...","免费开始","订阅","/月","支付","计划 {label}","免费计算器和量表","无限收藏","浏览历史","广告展示","无广告浏览","所有量表和计算器","所有模拟测试","Pleno计划的所有内容","可打印和填写的空白量表表格","Excel中的半自动排班和休假表","Excel中的半自动Fugulin、Braden、Morse和人员配置","讲义和手术图谱","用于护理的APK应用程序","免费","初级","Pleno","高级","免费","待处理","试用期","活跃","宽限期","已暂停","已请求取消","已取消","已过期","已阻止","失败","支付集成（信用卡、PIX和银行单据）尚不可用。此计费屏幕是占位符，将在项目的下一阶段完成。","护士插图","计划和订阅 - 护理计算器","支付 - 护理计算器"],
    hi: ["योजनाएं","योजनाएं और सदस्यता","लोड हो रहा है...","मुफ्त शुरू करें","सदस्यता लें","/माह","भुगतान","योजना {label}","मुफ्त कैलकुलेटर और पैमाने","असीमित पसंदीदा","ब्राउज़िंग इतिहास","विज्ञापन प्रदर्शन","विज्ञापन-मुक्त ब्राउज़िंग","सभी पैमाने और कैलकुलेटर","सभी मॉक टेस्ट","प्लेनो योजना की सभी सुविधाएं","प्रिंट और भरने के लिए खाली पैमाने के फॉर्म","एक्सेल में अर्ध-स्वचालित अवकाश और छुट्टी पैमाने","एक्सेल में अर्ध-स्वचालित Fugulin, Braden, Morse और स्टाफिंग","अध्ययन सामग्री और सर्जिकल मानचित्र","देखभाल के लिए APK ऐप्स","मुफ्त","जूनियर","प्लेनो","सीनियर","मुफ्त","लंबित","परीक्षण अवधि","सक्रिय","अनुग्रह अवधि","रोक दिया गया","रद्द करने का अनुरोध किया गया","रद्द","समाप्त","अवरुद्ध","विफल","भुगतान एकीकरण (क्रेडिट कार्ड, PIX और बोलेटो) अभी उपलब्ध नहीं है। यह भुगतान स्क्रीन एक प्लेसहोल्डर है और परियोजना के अगले चरण में पूरा किया जाएगा।","नर्स का चित्रण","योजनाएं और सदस्यता - नर्सिंग कैलकुलेटर","भुगतान - नर्सिंग कैलकुलेटर"],
    ar: ["الخطط","الخطط والاشتراك","جارٍ التحميل...","ابدأ مجانًا","اشترك","/شهريًا","الدفع","الخطة {label}","حاسبات ومقاييس مجانية","مفضلة غير محدودة","سجل التصفح","عرض الإعلانات","تصفح بدون إعلانات","جميع المقاييس والحاسبات","جميع الاختبارات التجريبية","كل شيء من خطة Pleno","نماذج مقاييس فارغة للطباعة والتعبئة","جداول الإجازات والعطلات شبه تلقائية في Excel","Fugulin وBraden وMorse والتخطيط شبه تلقائي في Excel","الملازم والخريطة الجراحية","تطبيقات APK للمساعدة","مجاني","مبتدئ","Pleno","خبير","مجانًا","قيد الانتظار","الفترة التجريبية","نشط","فترة سماح","متوقف مؤقتًا","تم طلب الإلغاء","ملغى","منتهي الصلاحية","محظور","فشل","تكامل الدفع (بطاقة الائتمان وPIX والفاتورة) غير متاح بعد. شاشة الدفع هذه هي عنصر نائب وستكتمل في المرحلة التالية من المشروع.","رسم توضيحي لممرضة","الخطط والاشتراك - حاسبات التمريض","الدفع - حاسبات التمريض"],
    ru: ["ПЛАНЫ","Планы и подписка","Загрузка...","Начать бесплатно","Подписаться","/мес","ОПЛАТА","План {label}","Бесплатные калькуляторы и шкалы","Безлимитные избранные","История просмотров","Показ рекламы","Просмотр без рекламы","Все шкалы и калькуляторы","Все тесты","Всё из плана Pleno","Бланки шкал для печати и заполнения","Полуавтоматические графики отпусков и выходных в Excel","Fugulin, Braden, Morse и Dimensionamento полуавтоматически в Excel","Пособия и хирургическая карта","APK-приложения для ухода","Бесплатный","Младший","Pleno","Старший","Бесплатно","Ожидает","Пробный период","Активна","Льготный период","Приостановлена","Запрошена отмена","Отменена","Истекла","Заблокирована","Ошибка","Интеграция оплаты (кредитная карта, PIX и банковский счёт) пока недоступна. Этот экран оплаты является заглушкой и будет завершён на следующем этапе проекта.","Иллюстрация медсестры","Планы и подписка - Медсестринские калькуляторы","Оплата - Медсестринские калькуляторы"],
    tr: ["PLANLAR","Planlar ve Abonelik","Yükleniyor...","Ücretsiz başla","Abone ol","/ay","ÖDEME","Plan {label}","Ücretsiz hesaplayıcılar ve ölçekler","Sınırsız favoriler","Gezinme geçmişi","Reklam gösterimi","Reklamsız gezinme","Tüm ölçekler ve hesaplayıcılar","Tüm deneme sınavları","Pleno planındaki her şey","Yazdırıp doldurmak için boş ölçek formları","Excel'de yarı otomatik izin ve tatil çizelgeleri","Excel'de yarı otomatik Fugulin, Braden, Morse ve Personel Planlama","Ders notları ve cerrahi harita","Bakım için APK uygulamaları","Ücretsiz","Júnior","Pleno","Sênior","Ücretsiz","Beklemede","Deneme süresi","Aktif","Ödeme süresi","Duraklatıldı","İptal istendi","İptal edildi","Süresi doldu","Engellendi","Başarısız","Ödeme entegrasyonu (kredi kartı, PIX ve bilet) henüz mevcut değil. Bu ödeme ekranı bir yer tutucudur ve projenin bir sonraki aşamasında tamamlanacaktır.","Hemşire illüstrasyonu","Planlar ve Abonelik - Hemşirelik Hesaplayıcıları","Ödeme - Hemşirelik Hesaplayıcıları"],
    ko: ["플랜","플랜 및 구독","로딩 중...","무료로 시작하기","구독하기","/월","결제","{label} 플랜","무료 계산기 및 척도","무제한 즐겨찾기","검색 기록","광고 표시","광고 없는 탐색","모든 척도 및 계산기","모든 모의고사","Pleno 플랜의 모든 기능","인쇄 및 작성 가능한 빈 척도 양식","Excel로 제공되는 반자동 휴가 및 휴가 일정","Excel로 제공되는 반자동 Fugulin, Braden, Morse 및 인력 산정","교재 및 수술 지도","간호 지원용 APK 앱","무료","주니어","Pleno","시니어","무료","대기 중","체험 기간","활성","유예 기간","일시 중지됨","취소 요청됨","취소됨","만료됨","차단됨","실패","결제 통합(신용카드, PIX, 및 은행 송금)은 아직 제공되지 않습니다. 이 결제 화면은 자리 표시자이며 프로젝트의 다음 단계에서 완성될 예정입니다.","간호사 일러스트레이션","플랜 및 구독 - 간호 계산기","결제 - 간호 계산기"],
    nl: ["PLANNEN","Plannen en abonnement","Laden...","Gratis starten","Abonneren","/maand","BETALING","Plan {label}","Gratis rekenmachines en schalen","Onbeperkte favorieten","Navigatiegeschiedenis","Advertenties weergeven","Advertentievrij navigeren","Alle schalen en rekenmachines","Alle oefentoetsen","Alles van het Pleno-plan","Blanco schaalformulieren om af te drukken en in te vullen","Semi-automatische roosters voor vrije dagen en vakanties in Excel","Fugulin, Braden, Morse en Dimensionering semi-automatisch in Excel","Cursusmateriaal en chirurgische kaart","APK-apps voor zorg","Gratis","Junior","Pleno","Senior","Gratis","In afwachting","Proefperiode","Actief","Respijtperiode","Gepauzeerd","Annulering aangevraagd","Geannuleerd","Verlopen","Geblokkeerd","Mislukt","De betaalintegratie (creditcard, PIX en bankoverschrijving) is nog niet beschikbaar. Dit betalingsscherm is een placeholder en wordt in de volgende fase van het project afgerond.","Illustratie van verpleegkundige","Plannen en abonnement - Verpleegkundige rekenmachines","Betaling - Verpleegkundige rekenmachines"],
    pl: ["PLANY","Plany i subskrypcja","Ładowanie...","Zacznij za darmo","Subskrybuj","/miesiąc","PŁATNOŚĆ","Plan {label}","Darmowe kalkulatory i skale","Nieograniczone ulubione","Historia przeglądania","Wyświetlanie reklam","Przeglądanie bez reklam","Wszystkie skale i kalkulatory","Wszystkie testy","Wszystko z planu Pleno","Puste formularze skal do wydruku i wypełnienia","Półautomatyczne harmonogramy dni wolnych i urlopów w Excelu","Fugulin, Braden, Morse i wymiarowanie półautomatycznie w Excelu","Materiały i mapa chirurgiczna","Aplikacje APK do opieki","Bezpłatny","Junior","Pleno","Senior","Za darmo","Oczekujące","Okres próbny","Aktywna","Okres karencji","Wstrzymana","Zażądano anulowania","Anulowana","Wygasła","Zablokowana","Nieudana","Integracja płatności (karta kredytowa, PIX i bilet) nie jest jeszcze dostępna. Ten ekran płatności jest zastępczy i zostanie ukończony w następnej fazie projektu.","Ilustracja pielęgniarki","Plany i subskrypcja - Kalkulatory pielęgniarskie","Płatność - Kalkulatory pielęgniarskie"],
    sv: ["PLANER","Planer och prenumeration","Läser in...","Börja gratis","Prenumerera","/månad","BETALNING","Plan {label}","Gratis miniräknare och skalor","Obegränsade favoriter","Webbläsarhistorik","Visning av annonser","Annonsfri surfning","Alla skalor och miniräknare","Alla övningsprov","Allt i Pleno-planen","Tomma skalformulär för utskrift och ifyllning","Halvautomatiska ledighets- och semesterlistor i Excel","Fugulin, Braden, Morse och Dimensionering halvautomatiska i Excel","Kompendier och operationskarta","APK-appar för vård","Gratis","Junior","Pleno","Senior","Gratis","Väntar","Testperiod","Aktiv","Respitperiod","Pausad","Avbeställning begärd","Avbeställd","Utgången","Blockerad","Misslyckades","Betalningsintegrationen (kreditkort, PIX och faktura) är ännu inte tillgänglig. Denna faktureringsskärm är en platshållare och kommer att slutföras i nästa fas av projektet.","Illustration av sjuksköterska","Planer och prenumeration - Sjuksköterskeberäkningar","Betalning - Sjuksköterskeberäkningar"],
    id: ["PAKET","Paket dan Langganan","Memuat...","Mulai gratis","Berlangganan","/bulan","PEMBAYARAN","Paket {label}","Kalkulator dan skala gratis","Favorit tanpa batas","Riwayat penelusuran","Menampilkan iklan","Penelusuran tanpa iklan","Semua skala dan kalkulator","Semua simulasi ujian","Semua dari paket Pleno","Formulir skala kosong untuk dicetak dan diisi","Jadwal libur dan cuti semi-otomatis di Excel","Fugulin, Braden, Morse, dan Dimensionamento semi-otomatis di Excel","Modul dan peta bedah","Aplikasi APK untuk asuhan","Gratis","Junior","Pleno","Senior","Gratis","Tertunda","Masa percobaan","Aktif","Masa tenggang","Dijeda","Pembatalan diminta","Dibatalkan","Kedaluwarsa","Diblokir","Gagal","Integrasi pembayaran (kartu kredit, PIX, dan boleto) belum tersedia. Layar penagihan ini adalah placeholder dan akan diselesaikan pada fase proyek berikutnya.","Ilustrasi perawat","Paket dan Langganan - Kalkulator Keperawatan","Pembayaran - Kalkulator Keperawatan"],
    vi: ["KẾ HOẠCH","Gói và Đăng ký","Đang tải...","Bắt đầu miễn phí","Đăng ký","/tháng","THANH TOÁN","Gói {label}","Máy tính và thang điểm miễn phí","Mục yêu thích không giới hạn","Lịch sử duyệt web","Hiển thị quảng cáo","Duyệt web không quảng cáo","Tất cả thang điểm và máy tính","Tất cả bài thi thử","Mọi thứ trong gói Pleno","Biểu mẫu thang điểm trống để in và điền","Bảng nghỉ và phép bán tự động trong Excel","Fugulin, Braden, Morse và Dimensionamento bán tự động trong Excel","Tài liệu và bản đồ phẫu thuật","Ứng dụng APK hỗ trợ điều dưỡng","Miễn phí","Junior","Pleno","Senior","Miễn phí","Đang chờ","Thời gian dùng thử","Hoạt động","Thời gian gia hạn","Tạm dừng","Đã yêu cầu hủy","Đã hủy","Hết hạn","Bị khóa","Thất bại","Tích hợp thanh toán (thẻ tín dụng, PIX và boleto) chưa khả dụng. Màn hình thanh toán này chỉ là chỗ giữ chỗ và sẽ được hoàn thiện trong giai đoạn tiếp theo của dự án.","Minh họa y tá","Gói và Đăng ký - Máy tính Điều dưỡng","Thanh toán - Máy tính Điều dưỡng"],
    uk: ["ПЛАНИ","Плани та підписка","Завантаження...","Почати безкоштовно","Підписатися","/міс","ОПЛАТА","План {label}","Безкоштовні калькулятори та шкали","Необмежені вибране","Історія переглядів","Показ реклами","Перегляд без реклами","Усі шкали та калькулятори","Усі тести","Все з плану Pleno","Бланки шкал для друку та заповнення","Напівавтоматичні графіки відпусток та вихідних в Excel","Fugulin, Braden, Morse та Dimensionamento напівавтоматично в Excel","Конспекти та хірургічна карта","APK-додатки для догляду","Безкоштовний","Júnior","Pleno","Sênior","Безкоштовно","Очікує","Пробний період","Активна","Пільговий період","Призупинена","Запит на скасування","Скасована","Термін дії минув","Заблокована","Помилка","Інтеграція оплати (кредитна картка, PIX та банківський сліп) ще недоступна. Цей екран оплати є заглушкою і буде завершений на наступному етапі проєкту.","Ілюстрація медсестри","Плани та підписка - Calculadoras de Enfermagem","Оплата - Calculadoras de Enfermagem"]
  };
  Object.keys(dynamicTranslations).forEach(function (code) {
    Array.prototype.push.apply(translations[code], dynamicTranslations[code]);
  });

  var errorKeys = ["invalid-credential", "wrong-password", "user-not-found", "user-disabled", "invalid-email", "too-many-requests", "email-already-in-use", "weak-password", "operation-not-allowed", "network-request-failed", "generic"];
  var errorMessages = {
    "pt-BR": ["E-mail ou senha inválidos.","Senha incorreta.","Usuário não encontrado.","Esta conta foi desativada.","Informe um e-mail válido.","Muitas tentativas. Aguarde e tente novamente.","Este e-mail já está em uso.","Escolha uma senha mais forte.","Esta forma de acesso não está habilitada.","Falha de conexão. Verifique sua internet.","Não foi possível concluir. Tente novamente."],
    en: ["Invalid email or password.","Incorrect password.","User not found.","This account has been disabled.","Enter a valid email.","Too many attempts. Wait and try again.","This email is already in use.","Choose a stronger password.","This sign-in method is not enabled.","Connection failed. Check your internet.","Unable to complete. Try again."],
    es: ["Correo o contraseña no válidos.","Contraseña incorrecta.","Usuario no encontrado.","Esta cuenta está desactivada.","Introduce un correo válido.","Demasiados intentos. Espera y vuelve a intentarlo.","Este correo ya está en uso.","Elige una contraseña más segura.","Este método de acceso no está habilitado.","Error de conexión. Comprueba tu conexión.","No se pudo completar. Inténtalo de nuevo."],
    fr: ["E-mail ou mot de passe incorrect.","Mot de passe incorrect.","Utilisateur introuvable.","Ce compte a été désactivé.","Saisissez un e-mail valide.","Trop de tentatives. Patientez puis réessayez.","Cet e-mail est déjà utilisé.","Choisissez un mot de passe plus fort.","Cette méthode de connexion n’est pas activée.","Échec de connexion. Vérifiez votre accès Internet.","Impossible de terminer. Réessayez."],
    de: ["E-Mail oder Passwort ungültig.","Falsches Passwort.","Benutzer nicht gefunden.","Dieses Konto wurde deaktiviert.","Geben Sie eine gültige E-Mail ein.","Zu viele Versuche. Warten Sie und versuchen Sie es erneut.","Diese E-Mail wird bereits verwendet.","Wählen Sie ein stärkeres Passwort.","Diese Anmeldemethode ist nicht aktiviert.","Verbindungsfehler. Prüfen Sie Ihre Internetverbindung.","Vorgang nicht möglich. Versuchen Sie es erneut."],
    it: ["E-mail o password non valide.","Password errata.","Utente non trovato.","Questo account è stato disattivato.","Inserisci un’e-mail valida.","Troppi tentativi. Attendi e riprova.","Questa e-mail è già in uso.","Scegli una password più sicura.","Questo metodo di accesso non è abilitato.","Connessione non riuscita. Controlla Internet.","Impossibile completare. Riprova."],
    ja: ["メールアドレスまたはパスワードが無効です。","パスワードが正しくありません。","ユーザーが見つかりません。","このアカウントは無効です。","有効なメールアドレスを入力してください。","試行回数が多すぎます。しばらくしてから再試行してください。","このメールアドレスは既に使用されています。","より強力なパスワードを設定してください。","このログイン方法は有効ではありません。","接続できません。インターネットをご確認ください。","完了できませんでした。再試行してください。"],
    zh: ["电子邮件或密码无效。","密码错误。","未找到用户。","此账户已被停用。","请输入有效的电子邮件。","尝试次数过多，请稍后重试。","此电子邮件已被使用。","请选择更强的密码。","此登录方式未启用。","连接失败，请检查网络。","无法完成，请重试。"],
    hi: ["ईमेल या पासवर्ड अमान्य है।","पासवर्ड गलत है।","उपयोगकर्ता नहीं मिला।","यह खाता अक्षम कर दिया गया है।","मान्य ईमेल दर्ज करें।","बहुत अधिक प्रयास हुए। प्रतीक्षा कर फिर प्रयास करें।","यह ईमेल पहले से उपयोग में है।","अधिक मजबूत पासवर्ड चुनें।","यह साइन-इन विधि सक्षम नहीं है।","कनेक्शन विफल। अपना इंटरनेट जाँचें।","पूरा नहीं हो सका। फिर प्रयास करें।"],
    ar: ["البريد الإلكتروني أو كلمة المرور غير صحيحة.","كلمة المرور غير صحيحة.","المستخدم غير موجود.","تم تعطيل هذا الحساب.","أدخل بريدًا إلكترونيًا صالحًا.","محاولات كثيرة. انتظر ثم حاول مجددًا.","هذا البريد مستخدم بالفعل.","اختر كلمة مرور أقوى.","طريقة تسجيل الدخول هذه غير مفعلة.","فشل الاتصال. تحقق من الإنترنت.","تعذر الإكمال. حاول مجددًا."],
    ru: ["Неверный адрес электронной почты или пароль.","Неверный пароль.","Пользователь не найден.","Эта учётная запись отключена.","Введите действительный адрес электронной почты.","Слишком много попыток. Подождите и повторите.","Этот адрес уже используется.","Выберите более надёжный пароль.","Этот способ входа не включён.","Ошибка подключения. Проверьте интернет.","Не удалось завершить. Повторите попытку."],
    tr: ["E-posta veya şifre geçersiz.","Şifre yanlış.","Kullanıcı bulunamadı.","Bu hesap devre dışı bırakılmış.","Geçerli bir e-posta girin.","Çok fazla deneme. Bekleyip tekrar deneyin.","Bu e-posta zaten kullanımda.","Daha güçlü bir şifre seçin.","Bu giriş yöntemi etkin değil.","Bağlantı başarısız. İnternetinizi kontrol edin.","İşlem tamamlanamadı. Tekrar deneyin."],
    ko: ["이메일 또는 비밀번호가 올바르지 않습니다.","비밀번호가 올바르지 않습니다.","사용자를 찾을 수 없습니다.","이 계정은 비활성화되었습니다.","올바른 이메일을 입력하세요.","시도 횟수가 너무 많습니다. 잠시 후 다시 시도하세요.","이미 사용 중인 이메일입니다.","더 강력한 비밀번호를 선택하세요.","이 로그인 방법은 활성화되지 않았습니다.","연결에 실패했습니다. 인터넷을 확인하세요.","완료할 수 없습니다. 다시 시도하세요."],
    nl: ["E-mail of wachtwoord is ongeldig.","Onjuist wachtwoord.","Gebruiker niet gevonden.","Dit account is uitgeschakeld.","Voer een geldig e-mailadres in.","Te veel pogingen. Wacht en probeer opnieuw.","Dit e-mailadres is al in gebruik.","Kies een sterker wachtwoord.","Deze aanmeldmethode is niet ingeschakeld.","Verbinding mislukt. Controleer uw internet.","Kan niet worden voltooid. Probeer opnieuw."],
    pl: ["Nieprawidłowy e-mail lub hasło.","Nieprawidłowe hasło.","Nie znaleziono użytkownika.","To konto zostało wyłączone.","Wprowadź prawidłowy e-mail.","Zbyt wiele prób. Poczekaj i spróbuj ponownie.","Ten e-mail jest już używany.","Wybierz silniejsze hasło.","Ta metoda logowania nie jest włączona.","Błąd połączenia. Sprawdź internet.","Nie udało się ukończyć. Spróbuj ponownie."],
    sv: ["Ogiltig e-postadress eller lösenord.","Felaktigt lösenord.","Användaren hittades inte.","Det här kontot har inaktiverats.","Ange en giltig e-postadress.","För många försök. Vänta och försök igen.","E-postadressen används redan.","Välj ett starkare lösenord.","Inloggningsmetoden är inte aktiverad.","Anslutningen misslyckades. Kontrollera internet.","Det gick inte att slutföra. Försök igen."],
    id: ["Email atau kata sandi tidak valid.","Kata sandi salah.","Pengguna tidak ditemukan.","Akun ini telah dinonaktifkan.","Masukkan email yang valid.","Terlalu banyak percobaan. Tunggu lalu coba lagi.","Email ini sudah digunakan.","Pilih kata sandi yang lebih kuat.","Metode masuk ini belum diaktifkan.","Koneksi gagal. Periksa internet Anda.","Tidak dapat menyelesaikan. Coba lagi."],
    vi: ["Email hoặc mật khẩu không hợp lệ.","Mật khẩu không đúng.","Không tìm thấy người dùng.","Tài khoản này đã bị vô hiệu hóa.","Nhập email hợp lệ.","Quá nhiều lần thử. Hãy chờ rồi thử lại.","Email này đã được sử dụng.","Chọn mật khẩu mạnh hơn.","Phương thức đăng nhập này chưa được bật.","Kết nối thất bại. Hãy kiểm tra Internet.","Không thể hoàn tất. Hãy thử lại."],
    uk: ["Неправильна електронна адреса або пароль.","Неправильний пароль.","Користувача не знайдено.","Цей обліковий запис вимкнено.","Введіть дійсну електронну адресу.","Забагато спроб. Зачекайте та повторіть.","Ця електронна адреса вже використовується.","Виберіть надійніший пароль.","Цей спосіб входу не ввімкнено.","Помилка з’єднання. Перевірте Інтернет.","Не вдалося завершити. Спробуйте ще раз."]
  };

  function normalize(value) { return LANGUAGE_ALIASES[String(value || "").trim().toLowerCase()] || null; }
  function languageFromPath(value) {
    try {
      var path = new URL(value, global.location && global.location.origin || "https://local.invalid").pathname;
      var segment = path.split("/").filter(Boolean)[0];
      return LANGUAGE_PREFIXES[segment] ? segment : (segment === "pt-br" ? "pt-BR" : null);
    } catch (_) { return null; }
  }
  function storedLanguage() { try { return normalize(global.localStorage.getItem(STORAGE_KEY)); } catch (_) { return null; } }
  function detectLanguage() {
    var params = new URLSearchParams(global.location ? global.location.search : "");
    return normalize(params.get("lang")) || languageFromPath(params.get("returnUrl")) || storedLanguage() ||
      languageFromPath(global.location && global.location.pathname) || normalize(global.navigator && global.navigator.language) || DEFAULT_LANGUAGE;
  }
  var currentLanguage = detectLanguage();
  function dictionary(code) {
    var values = translations[code];
    if (!values || values.length !== keys.length) throw new Error("Catálogo i18n incompleto: " + code);
    var result = {};
    keys.forEach(function (key, index) { result[key] = values[index]; });
    return result;
  }
  function t(key, vars) {
    var value = (currentLanguage === DEFAULT_LANGUAGE ? pt : dictionary(currentLanguage))[key] || pt[key] || key;
    Object.keys(vars || {}).forEach(function (name) { value = value.replace(new RegExp("\\{" + name + "\\}", "g"), String(vars[name])); });
    return value;
  }
  function authError(code, fallback) {
    var normalized = String(code || "generic").toLowerCase().replace(/^auth\//, "").replace(/^.*\//, "");
    if (normalized === "invalid-login-credentials" || normalized === "invalid-password") normalized = "invalid-credential";
    var index = errorKeys.indexOf(normalized);
    if (index < 0) index = errorKeys.indexOf("generic");
    var messages = errorMessages[currentLanguage] || errorMessages[DEFAULT_LANGUAGE];
    return messages[index] || errorMessages[DEFAULT_LANGUAGE][errorKeys.indexOf("generic")];
  }
  function escapeRegex(value) { return value.replace(/[.*+?^$()|[\]\\]/g, "\\$&"); }
  function translatePattern(value) {
    var translated = null;
    keys.some(function (candidate) {
      var template = pt[candidate];
      if (template.indexOf("{") === -1) return false;
      var names = [];
      var expression = "";
      var lastIndex = 0;
      template.replace(/\{(\w+)\}/g, function (token, name, index) {
        expression += escapeRegex(template.slice(lastIndex, index)) + "(.+?)";
        names.push(name);
        lastIndex = index + token.length;
        return token;
      });
      expression += escapeRegex(template.slice(lastIndex));
      var match = value.match(new RegExp("^" + expression + "$"));
      if (!match) return false;
      var vars = {};
      names.forEach(function (name, index) {
        var captured = match[index + 1];
        var capturedKey = keys.filter(function (key) { return pt[key] === captured; })[0];
        vars[name] = capturedKey ? t(capturedKey) : captured;
      });
      translated = t(candidate, vars);
      return true;
    });
    return translated;
  }
  function translateText(value) {
    var source = String(value == null ? "" : value);
    var trimmed = source.trim();
    var key = keys.filter(function (candidate) { return pt[candidate] === trimmed; })[0];
    if (key) return source.replace(trimmed, t(key));
    var patterned = translatePattern(trimmed);
    if (patterned !== null) return source.replace(trimmed, patterned);
    keys.slice().sort(function (a, b) { return pt[b].length - pt[a].length; }).some(function (candidate) {
      if (pt[candidate].length < 4 || source.indexOf(pt[candidate]) === -1) return false;
      source = source.replace(pt[candidate], t(candidate));
      return true;
    });
    return source;
  }
  function applyDirection() {
    if (!global.document) return;
    global.document.documentElement.lang = currentLanguage;
    global.document.documentElement.dir = currentLanguage === "ar" ? "rtl" : "ltr";
  }
  function syncFirebaseLanguage() {
    try {
      if (!global.firebase || typeof global.firebase.auth !== "function") return false;
      var authInstance = global.firebase.auth();
      if (!authInstance) return false;
      authInstance.languageCode = currentLanguage;
      return true;
    } catch (_) { return false; }
  }
  function translateElement(element) {
    if (!element || element.nodeType !== 1) return;
    ["placeholder", "title", "aria-label", "alt"].forEach(function (attribute) {
      if (element.hasAttribute(attribute)) element.setAttribute(attribute, translateText(element.getAttribute(attribute)));
    });
    var explicit = element.getAttribute("data-conta-i18n");
    if (explicit) element.textContent = t(explicit);
    Array.prototype.forEach.call(element.childNodes, function (node) {
      if (node.nodeType === 3 && node.nodeValue.trim()) node.nodeValue = translateText(node.nodeValue);
    });
  }
  function translateDom(root) {
    if (!global.document) return;
    root = root || global.document;
    if (root === global.document && global.document.title) global.document.title = translateText(global.document.title);
    if (root.nodeType === 1) translateElement(root);
    Array.prototype.forEach.call(root.querySelectorAll("[data-conta-i18n],[placeholder],[title],[aria-label],[alt],#billing-container div,h1,h2,h3,h4,label,button,a,option,p,span,strong"), translateElement);
  }
  function setLanguage(code, options) {
    var normalized = normalize(code);
    if (!normalized) return false;
    currentLanguage = normalized;
    try { global.localStorage.setItem(STORAGE_KEY, currentLanguage); } catch (_) {}
    applyDirection();
    syncFirebaseLanguage();
    if (!options || options.translate !== false) translateDom();
    if (options && options.preserveUrl && global.history && global.location) {
      var currentUrl = new URL(global.location.href);
      currentUrl.searchParams.set("lang", currentLanguage);
      global.history.replaceState(global.history.state, "", currentUrl.pathname + currentUrl.search + currentUrl.hash);
    }
    if (global.document) global.document.dispatchEvent(new CustomEvent("conta:languagechange", { detail: { language: currentLanguage } }));
    return true;
  }
  function withLanguage(url, returnUrl) {
    var target = new URL(url || "/conta/login.html", global.location && global.location.origin || "https://local.invalid");
    target.searchParams.set("lang", currentLanguage);
    if (returnUrl) target.searchParams.set("returnUrl", returnUrl);
    return target.pathname + target.search + target.hash;
  }
  var observerStarted = false;
  function observe() {
    if (!global.MutationObserver || !global.document || !global.document.body) return;
    if (observerStarted) return;
    observerStarted = true;
    new MutationObserver(function (mutations) {
      mutations.forEach(function (mutation) { Array.prototype.forEach.call(mutation.addedNodes, function (node) { if (node.nodeType === 1) translateDom(node); }); });
    }).observe(global.document.body, { childList: true, subtree: true });
  }

  var subscribers = [];
  if (global.document) global.document.addEventListener("conta:languagechange", function (event) {
    subscribers.slice().forEach(function (callback) { try { callback(event.detail.language); } catch (_) {} });
  });
  function localizedHome() { return currentLanguage === DEFAULT_LANGUAGE ? "/" : "/" + currentLanguage + "/"; }
  function buildLoginUrl(returnUrl) { return withLanguage("/conta/login.html", returnUrl || localizedHome()); }
  function subscribe(callback) {
    if (typeof callback !== "function") return function () {};
    subscribers.push(callback);
    return function () { subscribers = subscribers.filter(function (item) { return item !== callback; }); };
  }
  function init() { applyDirection(); syncFirebaseLanguage(); translateDom(); observe(); return api; }
  var api = {
    languages: languages, init: init, t: t, error: authError, translate: translateText, translateDom: translateDom, setLanguage: setLanguage,
    getLanguage: function () { return currentLanguage; }, detectLanguage: detectLanguage, normalizeLanguage: normalize,
    localizedHome: localizedHome, buildLoginUrl: buildLoginUrl, subscribe: subscribe,
    withLanguage: withLanguage, getLanguageFromReturnUrl: languageFromPath
  };
  global.AccountI18n = api;
  global.ContaI18n = api;
  languages.forEach(function (language) {
    if (language.code !== DEFAULT_LANGUAGE) dictionary(language.code);
    if (!errorMessages[language.code] || errorMessages[language.code].length !== errorKeys.length) throw new Error("Catálogo de erros incompleto: " + language.code);
  });
  applyDirection();
  if (global.document) {
    if (global.document.readyState === "loading") global.document.addEventListener("DOMContentLoaded", init);
    else init();
  }
})(typeof window !== "undefined" ? window : globalThis);
