/**
 * conta/perfil.html controller
 * Runtime isolado: Firebase identifica a sessão; Supabase hidrata dados.
 * Nenhuma chamada remota de billing/perfil pode bloquear a interface inicial.
 */
(function(window,document){
"use strict";
var ACCOUNT_DATA_URL="https://asjkftjfbkuuhilnqonx.supabase.co/functions/v1/account-data";
var BILLING_ACCESS_URL="https://asjkftjfbkuuhilnqonx.supabase.co/functions/v1/billing-access";
var state={user:null,profile:null,billing:null,booted:false,signingOut:false};
function el(id){return document.getElementById(id);}
function text(id,value){var n=el(id);if(n)n.textContent=value==null||value===""?"—":String(value);}
function lang(){try{return window.AccountI18n&&typeof window.AccountI18n.getLanguage==="function"?window.AccountI18n.getLanguage():"pt-BR";}catch(_){return"pt-BR";}}
function t(key,fallback){try{if(window.AccountI18n&&typeof window.AccountI18n.t==="function"){var v=window.AccountI18n.t(key);if(v&&v!==key)return v;}}catch(_){}return fallback||key;}
function accountUrl(path){try{if(window.AccountRoutes&&typeof window.AccountRoutes.accountUrl==="function")return window.AccountRoutes.accountUrl(path,lang());if(window.__ACCOUNT_PAGE_URL)return window.__ACCOUNT_PAGE_URL("/conta/"+String(path).replace(/^\/+/, ""));}catch(_){}return"/conta/"+String(path).replace(/^\/+/, "")+"?lang="+encodeURIComponent(lang());}
function showMessage(message,error){var box=el("profile-message");if(!box)return;box.textContent=message;box.style.display="block";box.className="mb-4 px-4 py-3 rounded-xl text-sm font-semibold "+(error?"bg-red-50 text-red-700 border border-red-200":"bg-green-50 text-green-700 border border-green-200");}
function hideLoading(){var l=el("profile-loading"),c=el("profile-content");if(l)l.style.display="none";if(c)c.style.display="block";}
function timeout(promise,ms,label){return Promise.race([promise,new Promise(function(_,reject){setTimeout(function(){reject(new Error(label||"timeout"));},ms);})]);}
function providerLabel(p){p=String(p||"");if(p.indexOf("google")!==-1)return"Google";if(p.indexOf("microsoft")!==-1)return"Microsoft";if(p.indexOf("apple")!==-1)return"Apple";if(p==="password"||p==="email")return"E-mail/Password";return p||"—";}
function planLabel(p){if(p==="premium")return"Premium";if(p==="free")return t("planFree","Free");return"Verificando plano…";}
function formatDate(v){if(!v)return"—";var d=new Date(v);if(isNaN(d.getTime()))return"—";var l=lang()==="pt"||lang()==="pt-BR"?"pt-BR":lang();try{return d.toLocaleDateString(l,{day:"2-digit",month:"2-digit",year:"numeric"})+" "+d.toLocaleTimeString(l,{hour:"2-digit",minute:"2-digit"});}catch(_){return d.toLocaleString();}}
function renderAvatar(name,url){var box=el("profile-avatar");if(!box)return;box.textContent="";if(url){var img=document.createElement("img");img.src=url;img.alt=name||"";img.className="w-16 h-16 rounded-full border-2 border-[#1A3E74] object-cover";img.referrerPolicy="no-referrer";img.decoding="async";img.loading="lazy";img.onerror=function(){renderAvatar(name,"");};box.appendChild(img);return;}var a=document.createElement("div");a.className="w-16 h-16 rounded-full bg-[#1A3E74] flex items-center justify-center text-white font-black text-2xl";a.textContent=(name||"U").charAt(0).toUpperCase();box.appendChild(a);}
function render(){var u=state.user||{},p=state.profile||{},b=state.billing||{};var name=p.displayName||u.displayName||t("fullName","Usuário"),email=p.email||u.email||"",photo=p.photoURL||u.photoURL||"",language=p.language||lang(),country=p.country||"—",provider=p.provider||((u.providerData&&u.providerData[0]&&u.providerData[0].providerId)||""),plan=b.plan||p.plan||"verifying";renderAvatar(name,photo);text("profile-name",name);text("profile-email",email);text("profile-plan",planLabel(plan));text("profile-language",String(language).toUpperCase());text("profile-country",country);text("profile-provider",providerLabel(provider));text("profile-created",formatDate(p.createdAt));text("profile-lastlogin",formatDate(p.lastLoginAt));var input=el("edit-name-input");if(input&&!input.dataset.touched)input.value=name;hideLoading();}
function bindRoutes(){var s=el("profile-settings-link"),c=el("account-breadcrumb");if(s)s.href=accountUrl("configuracoes.html");if(c)c.href=accountUrl("login.html");}
async function getFirebaseUser(){if(!window.FirebaseInit||typeof window.FirebaseInit.init!=="function")throw new Error("firebase_init_unavailable");var fb=await timeout(window.FirebaseInit.init(),8000,"firebase_init_timeout"),auth=fb&&fb.auth?fb.auth:(window.FirebaseInit.getAuthSync&&window.FirebaseInit.getAuthSync());if(!auth)throw new Error("firebase_auth_unavailable");if(auth.currentUser)return{auth:auth,user:auth.currentUser};var user=await timeout(new Promise(function(resolve){var done=false,unsub=auth.onAuthStateChanged(function(v){if(done)return;done=true;try{if(unsub)unsub();}catch(_){}resolve(v||null);});}),8000,"auth_state_timeout");return{auth:auth,user:user};}
async function request(url,method,user,body){if(!user||typeof user.getIdToken!=="function")throw new Error("not_authenticated");var token=await timeout(user.getIdToken(false),5000,"id_token_timeout"),controller=new AbortController(),timer=setTimeout(function(){controller.abort();},7000);try{var o={method:method||"GET",headers:{Authorization:"Bearer "+token,Accept:"application/json"}};if(body!==undefined){o.headers["Content-Type"]="application/json";o.body=JSON.stringify(body);}var r=await fetch(url,o),d=await r.json().catch(function(){return{};});if(!r.ok)throw new Error(d.error||("request_"+r.status));return d;}catch(e){if(e&&e.name==="AbortError")throw new Error("request_timeout");throw e;}finally{clearTimeout(timer);}}
async function hydrate(){var u=state.user;if(!u)return;var results=await Promise.allSettled([request(BILLING_ACCESS_URL,"GET",u),request(ACCOUNT_DATA_URL+"?resource=profile","GET",u)]),br=results[0],pr=results[1];if(br.status==="fulfilled"&&br.value){var b=br.value;state.billing={plan:b.plan==="premium"?"premium":"free",premium_expires_at:b.premium_expires_at||null,provider:b.provider||null,provider_customer_id:b.provider_customer_id||null,provider_subscription_id:b.provider_subscription_id||null};}else{state.billing={plan:"verifying"};console.warn("[Profile] Billing ainda não disponível.",br.reason);}if(pr.status==="fulfilled"&&pr.value&&pr.value.profile)state.profile=pr.value.profile;else{state.profile={uid:u.uid,email:u.email||"",displayName:u.displayName||"",photoURL:u.photoURL||"",provider:u.providerData&&u.providerData[0]?u.providerData[0].providerId:"",language:lang(),country:"BR"};console.warn("[Profile] Dados detalhados indisponíveis.",pr.reason);}render();}
async function saveName(){var input=el("edit-name-input"),button=el("btn-save-name"),name=input?input.value.trim():"";if(name.length<2){showMessage(t("invalidName","Informe um nome válido (mínimo de 2 caracteres)."),true);return;}if(!state.user){showMessage("Sua sessão ainda não está disponível. Aguarde um instante e tente novamente.",true);return;}if(button)button.disabled=true;try{var d=await request(ACCOUNT_DATA_URL+"?resource=profile","PATCH",state.user,{displayName:name});state.profile=d&&d.profile?d.profile:Object.assign({},state.profile,{displayName:name});if(input)input.dataset.touched="1";render();showMessage(t("saveNameSuccess","Nome atualizado com sucesso!"),false);}catch(e){console.error("[Profile] Falha ao salvar nome:",e);showMessage(t("saveError","Erro ao salvar.")+" "+t("tryAgain","Tente novamente."),true);}finally{if(button)button.disabled=false;}}
async function signOut(){if(state.signingOut)return;state.signingOut=true;var button=el("btn-sair");if(button)button.disabled=true;try{var auth=window.FirebaseInit&&window.FirebaseInit.getAuthSync?window.FirebaseInit.getAuthSync():null;if(auth)await timeout(auth.signOut(),6000,"signout_timeout");}catch(e){console.warn("[Profile] Logout:",e);}var home="/";try{home=window.AccountI18n&&typeof window.AccountI18n.localizedHome==="function"?window.AccountI18n.localizedHome():"/";}catch(_){}window.location.href=home;}
async function boot(){bindRoutes();try{var session=await getFirebaseUser();state.user=session.user;if(!state.user){var login=window.AccountI18n&&typeof window.AccountI18n.buildLoginUrl==="function"?window.AccountI18n.buildLoginUrl(window.location.pathname+window.location.search):"/conta/login.html";window.location.replace(login);return;}state.profile={uid:state.user.uid,email:state.user.email||"",displayName:state.user.displayName||"",photoURL:state.user.photoURL||"",provider:state.user.providerData&&state.user.providerData[0]?state.user.providerData[0].providerId:"",language:lang(),country:"BR"};state.billing={plan:"verifying"};render();hydrate().catch(function(e){console.warn("[Profile] Hidratação secundária:",e);});}catch(e){console.error("[Profile] Bootstrap:",e);var auth=window.FirebaseInit&&window.FirebaseInit.getAuthSync?window.FirebaseInit.getAuthSync():null,user=auth&&auth.currentUser?auth.currentUser:null;if(user){state.user=user;state.profile={uid:user.uid,email:user.email||"",displayName:user.displayName||"",photoURL:user.photoURL||"",provider:user.providerData&&user.providerData[0]?user.providerData[0].providerId:"",language:lang(),country:"BR"};state.billing={plan:"verifying"};render();showMessage("A sessão foi identificada. Alguns dados da conta ainda estão sendo sincronizados.",true);}else{var fallback="/conta/login.html";try{if(window.AccountI18n&&typeof window.AccountI18n.buildLoginUrl==="function")fallback=window.AccountI18n.buildLoginUrl(window.location.pathname+window.location.search);}catch(_){}window.location.replace(fallback);}}finally{state.booted=true;}}
function init(){var save=el("btn-save-name"),out=el("btn-sair");if(save)save.addEventListener("click",saveName);if(out)out.addEventListener("click",signOut);document.addEventListener("conta:languagechange",bindRoutes);bindRoutes();boot();}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
window.ProfilePage={getState:function(){return state;}};
})(window,document);
