// Stripe Sandbox webhook — isolado da produção.
// Aceita somente eventos assinados com STRIPE_TEST_WEBHOOK_SECRET e marcados environment=test.
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const SECRET=Deno.env.get("STRIPE_TEST_WEBHOOK_SECRET")??"";
const STRIPE_KEY=Deno.env.get("STRIPE_TEST_SECRET_KEY")??"";
const FIREBASE_PROJECT_ID=Deno.env.get("FIREBASE_PROJECT_ID")??"calculadoras-enfermagem";
const FIREBASE_SERVICE_ACCOUNT=Deno.env.get("FIREBASE_SERVICE_ACCOUNT")??"";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")??"";
const SUPABASE_SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
const STRIPE_API="https://api.stripe.com/v1";
function b64(s:string){const x=s.replace(/-/g,"+").replace(/_/g,"/");const bin=atob(x+"=".repeat((4-x.length%4)%4));const a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return a;}
function pem(s:string){const bin=atob(s.replace(/-----BEGIN PRIVATE KEY-----/,"").replace(/-----END PRIVATE KEY-----/,"").replace(/\s+/g,""));const a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return a.buffer;}
function enc(v:string){const a=new TextEncoder().encode(v);let b="";a.forEach(x=>b+=String.fromCharCode(x));return btoa(b).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");}
async function token(){const sa=JSON.parse(FIREBASE_SERVICE_ACCOUNT);const now=Math.floor(Date.now()/1000);const h=enc(JSON.stringify({alg:"RS256",typ:"JWT"}));const p=enc(JSON.stringify({iss:sa.client_email,scope:"https://www.googleapis.com/auth/datastore",aud:sa.token_uri,iat:now,exp:now+3600}));const k=await crypto.subtle.importKey("pkcs8",pem(sa.private_key),{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]);const sig=await crypto.subtle.sign("RSASSA-PKCS1-v1_5",k,new TextEncoder().encode(`${h}.${p}`));const r=await fetch(sa.token_uri,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion:`${h}.${p}.${enc(sig)}`})});const d=await r.json();if(!r.ok||!d.access_token)throw Error("firebase_token_error");return d.access_token;}
function firestoreUrl(path:string,fields?:string[]){let u=`https://firestore.googleapis.com/v1/projects/${FIREBASE_PROJECT_ID}/databases/(default)/documents/${path}`;if(fields?.length)u+="?"+fields.map(f=>`updateMask.fieldPaths=${encodeURIComponent(f)}`).join("&");return u;}
function sv(v:string){return{stringValue:v}}function tv(v:string){return{timestampValue:v}};
async function patch(path:string,fields:any,t:string){const r=await fetch(firestoreUrl(path,Object.keys(fields)),{method:"PATCH",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify({fields})});if(!r.ok)throw Error(`firestore_${r.status}`);}
async function verify(raw:string,sig:string){let ts="";const vals:string[]=[];for(const x of sig.split(",")){if(x.startsWith("t="))ts=x.slice(2);if(x.startsWith("v1="))vals.push(x.slice(3));}if(!ts||!vals.length)return false;const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(SECRET),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const mac=await crypto.subtle.sign("HMAC",k,new TextEncoder().encode(`${ts}.${raw}`));const expected=Array.from(new Uint8Array(mac)).map(x=>x.toString(16).padStart(2,"0")).join("");return vals.includes(expected);}
function admin(){if(!SUPABASE_URL||!SUPABASE_SERVICE_ROLE_KEY)throw Error("supabase_not_configured");return createClient(SUPABASE_URL,SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}})}
async function claim(id:string){const {data,error}=await admin().rpc("claim_billing_webhook",{p_provider:"stripe_test",p_event_id:id,p_lease_seconds:300});if(error)throw Error(`claim:${error.message}`);return data===true;}
async function done(id:string){await admin().rpc("complete_billing_webhook",{p_provider:"stripe_test",p_event_id:id});}
async function fail(id:string,e:string){await admin().rpc("fail_billing_webhook",{p_provider:"stripe_test",p_event_id:id,p_error:e.slice(0,2000)});}
async function subMeta(id:string){if(!STRIPE_KEY)return{};const r=await fetch(`${STRIPE_API}/subscriptions/${encodeURIComponent(id)}`,{headers:{Authorization:`Bearer ${STRIPE_KEY}`}});if(!r.ok)return{};const s=await r.json();return{uid:String(s?.metadata?.uid||""),end:s?.current_period_end?new Date(Number(s.current_period_end)*1000).toISOString():undefined};}
async function setJunior(uid:string,subId:string,expires?:string){const t=await token();const now=new Date().toISOString();await patch(`users/${uid}`,{plan:sv("junior"),planUpdatedAt:tv(now),planExpiresAt:tv(expires||new Date(Date.now()+30*86400000).toISOString()),metadata:{mapValue:{fields:{stripeEnvironment:sv("test")}}}},t);if(subId)await patch(`users/${uid}/subscriptions/${subId}`,{planId:sv("junior"),status:sv("active"),userId:sv(uid),provider:sv("stripe_test"),providerSubscriptionId:sv(subId),updatedAt:tv(now)},t);}
async function setFree(uid:string,subId:string){const t=await token();const now=new Date().toISOString();await patch(`users/${uid}`,{plan:sv("free"),planUpdatedAt:tv(now),planExpiresAt:tv(now)},t);if(subId)await patch(`users/${uid}/subscriptions/${subId}`,{planId:sv("free"),status:sv("cancelled"),userId:sv(uid),provider:sv("stripe_test"),providerSubscriptionId:sv(subId),updatedAt:tv(now)},t);}
serve(async(req)=>{if(req.method!=="POST")return new Response("method_not_allowed",{status:405});if(!SECRET||!STRIPE_KEY||!FIREBASE_SERVICE_ACCOUNT||!SUPABASE_URL||!SUPABASE_SERVICE_ROLE_KEY)return new Response("not_configured",{status:500});const raw=await req.text();if(!(await verify(raw,req.headers.get("stripe-signature")||"")))return new Response("invalid_signature",{status:400});let id="";try{const e=JSON.parse(raw);id=String(e?.id||"");const o=e?.data?.object||{};if(!id)return new Response("invalid_event",{status:400});if(!await claim(id))return new Response(JSON.stringify({ok:true,duplicate:true}),{status:200});const env=String(o?.metadata?.environment||o?.subscription_details?.metadata?.environment||"");const provider=String(o?.metadata?.payment_provider||"");if(env!=="test"||provider!=="stripe_test"){await done(id);return new Response("ignored",{status:200});}const t=await token();await patch(`stripeTestEvents/${id}`,{eventId:sv(id),type:sv(String(e?.type||"")),status:sv("processing"),receivedAt:tv(new Date().toISOString())},t);if(e.type==="checkout.session.completed"){const uid=String(o?.client_reference_id||o?.metadata?.uid||"");if(!uid)throw Error("test_uid_missing");await setJunior(uid,String(o?.subscription||""));}else if(e.type==="invoice.paid"){const m=await subMeta(String(o?.subscription||""));if(m.uid)await setJunior(m.uid,String(o?.subscription||""),m.end);}else if(e.type==="invoice.payment_failed"){const m=await subMeta(String(o?.subscription||""));if(m.uid)await setFree(m.uid,String(o?.subscription||""));}else if(e.type==="customer.subscription.deleted"){const uid=String(o?.metadata?.uid||"");if(uid)await setFree(uid,String(o?.id||""));}await patch(`stripeTestEvents/${id}`,{status:sv("processed"),processedAt:tv(new Date().toISOString())},t);await done(id);return new Response("ok",{status:200});}catch(e){console.error("[stripe-webhook-test]",e);if(id)try{await fail(id,String(e))}catch{}return new Response("error",{status:500});}});