import re
orig = open('waterlow.html','r',encoding='utf-8').read()
trad = open('en/waterlow.html','r',encoding='utf-8').read()
print('Tags  orig:', len(re.findall(r'<\w+', orig)))
print('Tags  trad:', len(re.findall(r'<\w+', trad)))
print('${    orig:', orig.count('${'))
print('${    trad:', trad.count('${'))
print('<script orig:', orig.count('<script'))
print('<script trad:', trad.count('<script'))
print('</script> orig:', orig.count('</script>'))
print('</script> trad:', trad.count('</script>'))
print('OK!' if orig.count('<script') == trad.count('<script') else 'CORROMPIDO!')
