module.exports = {
  ci: {
    collect: {
      url: [
        // === CALCULADORAS CLÍNICAS PRINCIPAIS ===
        'http://localhost:8080/saps.html',
        'http://localhost:8080/sofa.html',
        'http://localhost:8080/qsofa.html',
        'http://localhost:8080/apache.html',
        'http://localhost:8080/waterlow.html',
        'http://localhost:8080/braden.html',
        'http://localhost:8080/norton.html',
        'http://localhost:8080/glasgow.html',
        'http://localhost:8080/richmond.html',
        'http://localhost:8080/ramsay.html',
        'http://localhost:8080/cam.html',
        'http://localhost:8080/fast.html',
        'http://localhost:8080/curb-65.html',
        'http://localhost:8080/manchester.html',
        'http://localhost:8080/tinetti.html',
        'http://localhost:8080/silverman.html',
        'http://localhost:8080/downes.html',
        'http://localhost:8080/ballard.html',
        'http://localhost:8080/capurro.html',
        'http://localhost:8080/apgar.html',
        'http://localhost:8080/bishop.html',
        'http://localhost:8080/aldrete.html',
        'http://localhost:8080/meows.html',
        'http://localhost:8080/pews.html',
        'http://localhost:8080/news.html',
        'http://localhost:8080/prism.html',
        'http://localhost:8080/meem.html',
        'http://localhost:8080/moca.html',
        'http://localhost:8080/zarit.html',
        'http://localhost:8080/katz.html',
        'http://localhost:8080/lawton.html',
        'http://localhost:8080/barthel.html',
        'http://localhost:8080/berg.html',
        'http://localhost:8080/morse.html',
        'http://localhost:8080/humpty.html',
        'http://localhost:8080/bps.html',
        'http://localhost:8080/flacc.html',
        'http://localhost:8080/cries.html',
        'http://localhost:8080/elpo.html',
        'http://localhost:8080/downton.html',
        'http://localhost:8080/gosnell.html',
        'http://localhost:8080/johns.html',
        'http://localhost:8080/hamilton.html',
        'http://localhost:8080/four.html',
        'http://localhost:8080/nihss.html',
        'http://localhost:8080/cincinnati.html',
        'http://localhost:8080/rancholosamigos.html',
        'http://localhost:8080/lanss.html',
        'http://localhost:8080/painad.html',
        'http://localhost:8080/cornell.html',
        'http://localhost:8080/gds.html',
        'http://localhost:8080/hendrich.html',
        'http://localhost:8080/lachs.html',
        'http://localhost:8080/fugulin.html',
        'http://localhost:8080/perroca.html',
        'http://localhost:8080/jouvet.html',
        'http://localhost:8080/ofras.html',
        'http://localhost:8080/pelod.html',
        'http://localhost:8080/nips.html',
        'http://localhost:8080/asa.html',
        'http://localhost:8080/dimensionamento.html',
        'http://localhost:8080/imc.html',
        'http://localhost:8080/gestacional.html',
        'http://localhost:8080/balancohidrico.html',
        'http://localhost:8080/gasometria.html',
        'http://localhost:8080/diagnosticosnanda.html',
        'http://localhost:8080/medicamentos.html',
        'http://localhost:8080/instrumentais-cirurgicos.html',
        'http://localhost:8080/genogramaeecomapa.html',
        // === AMOSTRA MULTILÍNGUE (1 por idioma) ===
        'http://localhost:8080/en/saps.html',
        'http://localhost:8080/es/saps.html',
        'http://localhost:8080/de/waterlow.html',
        'http://localhost:8080/fr/braden.html',
        'http://localhost:8080/it/glasgow.html',
        'http://localhost:8080/ar/sofa.html',
        'http://localhost:8080/zh/tinetti.html',
        'http://localhost:8080/ja/richmond.html',
        'http://localhost:8080/ko/apache.html',
        'http://localhost:8080/ru/meem.html',
        'http://localhost:8080/hi/zarit.html',
        'http://localhost:8080/tr/barthel.html',
        'http://localhost:8080/nl/curb-65.html',
        'http://localhost:8080/pl/news.html',
        'http://localhost:8080/sv/ramsay.html',
        'http://localhost:8080/id/manchester.html',
        'http://localhost:8080/vi/aldrete.html',
        'http://localhost:8080/uk/waterlow.html',
      ],
      staticDistDir: './', // Onde o servidor local do Lighthouse deve rodar
      numberOfRuns: 2,     // 88 páginas × 2 runs = ~1.5h no CI
    },
    assert: {
      assertions: {
        // Core Web Vitals — todos com severidade "warn" para não bloquear o merge
        'first-contentful-paint': ['warn', { maxNumericValue: 1800 }],
        'largest-contentful-paint': ['warn', { maxNumericValue: 2500 }],
        'total-blocking-time': ['warn', { maxNumericValue: 200 }],
        'cumulative-layout-shift': ['warn', { maxNumericValue: 0.1 }],
        'speed-index': ['warn', { maxNumericValue: 3400 }],
        'interactive': ['warn', { maxNumericValue: 3800 }],
        'categories:performance': ['warn', { minScore: 0.75 }],
        'categories:accessibility': ['warn', { minScore: 0.90 }],
      },
    },
    upload: {
      target: 'temporary-public-storage',
    },
  },
};