const portals = [
  { title: 'Vagas.com.br', icon: 'briefcase', description: 'Portal de Empregos com milhares de vagas disponíveis em todo o Brasil.', url: 'https://www.vagas.com.br/vagas-de-enfermeiro', type: 'Vaga' },
  { title: 'Catho', icon: 'briefcase', description: 'Encontre milhares de oportunidades de emprego para enfermeiros em todo o país.', url: 'https://www.catho.com.br/vagas/enfermeiro/', type: 'Vaga' },
  { title: 'Coren-SP Oportunidades', icon: 'briefcase', description: 'Portal do Conselho Regional de Enfermagem de São Paulo com vagas e concursos.', url: 'https://portal.coren-sp.gov.br/oportunidades/', type: 'Vaga' },
  { title: 'Infojobs', icon: 'briefcase', description: 'Centenas de vagas para enfermagem, principalmente em São Paulo, SP.', url: 'https://www.infojobs.com.br/empregos-enfermagem-em-sao-paulo,-sp.aspx', type: 'Vaga' },
  { title: 'Gupy', icon: 'briefcase', description: 'Plataforma de recrutamento com vagas de enfermagem em diversas grandes empresas.', url: 'https://portal.gupy.io/job-search/term=enfermeiro', type: 'Vaga' },
  { title: 'LinkedIn Jobs', icon: 'briefcase', description: 'Rede profissional para encontrar vagas em todos os níveis de carreira.', url: 'https://br.linkedin.com/jobs/search?keywords=Enfermeiro&location=Brasil', type: 'Vaga' },
  { title: 'IBAM SP', icon: 'award', description: 'Instituto Brasileiro de Administração Municipal, com concursos em São Paulo.', url: 'https://www.ibamsp-concursos.org.br/', type: 'Concurso' },
  { title: 'Hospital Albert Einstein', icon: 'briefcase', description: 'Vagas de emprego para o Hospital Albert Einstein.', url: 'https://www.einstein.br/n/o-einstein/carreiras', type: 'Vaga' },
  { title: 'Hospitais UHG', icon: 'briefcase', description: 'Vagas de emprego para os Hospitais UHG.', url: 'https://careers.unitedhealthgroup.com/?sc_lang=pt-br&sc_camp=AB816290AF154FF68469563915E38BDE', type: 'Vaga' },
  { title: 'Hospital Sírio Libanês', icon: 'briefcase', description: 'Vagas de emprego para o Hospital Sírio Libanês.', url: 'https://hospitalsiriolibanes.org.br/trabalhe-conosco', type: 'Vaga' },
  { title: 'AC Camargo', icon: 'briefcase', description: 'Vagas de emprego para o AC Camargo.', url: 'https://accamargo.org.br/busca?search_api_fulltext=trabalhe%20conosco', type: 'Vaga' },
  { title: 'Rede D\'OR - São Luiz', icon: 'briefcase', description: 'Vagas de emprego para a Rede D’OR São Luiz.', url: 'https://www.rededorsaoluiz.com.br/trabalhe-conosco', type: 'Vaga' },
  { title: 'Hospital InCor', icon: 'briefcase', description: 'Vagas de emprego para o Hospital InCor.', url: 'https://www.incor.usp.br/sites/incor2024/trabalhe-conosco', type: 'Vaga' },
  { title: 'Hospital HCor', icon: 'briefcase', description: 'Vagas de emprego para o Hospital HCor.', url: 'https://www.hcor.com.br/sobre-o-hcor/trabalhe-conosco/', type: 'Vaga' },
  { title: 'Santa Casa de São Paulo', icon: 'briefcase', description: 'Vagas de emprego para a Santa Casa de São Paulo.', url: 'https://santacasasp.org.br/trabalhe-conosco/', type: 'Vaga' },
  { title: 'Instituto Social Hospital Alemão Oswaldo Cruz', icon: 'briefcase', description: 'Vagas de emprego para o Instituto Social Hospital Alemão Oswaldo Cruz.', url: 'https://ishaoc.org.br/trabalheconosco/', type: 'Vaga' },
  { title: 'SPDM PAIS', icon: 'briefcase', description: 'Vagas de emprego para a SPDM PAIS.', url: 'https://www.spdmpais.org.br/trabalheconosco', type: 'Vaga' },
  { title: 'Hospital São Camilo', icon: 'briefcase', description: 'Vagas de emprego para o Hospital São Camilo.', url: 'https://saocamilo-sp.br/trabalhe-conosco/?utm_source=google_ads&utm_medium=cpc&utm_campaign=20328254077&utm_term=&utm_content=&gad_source=1&gad_campaignid=20318887374&gbraid=0AAAAADkHLtUTpMKMKyQJR-6xFWyiQgy0C&gclid=CjwKCAjw7_DEBhAeEiwAWKiCC6K27HtJ1Qjj4td6koozO1x7UboEYsRbafHkhrYgSgxra_Mj_buUvxoCzeAQAvD_BwE', type: 'Vaga' },
  { title: 'Hospital Santo Amaro - Guarujá', icon: 'briefcase', description: 'Vagas de emprego para o Hospital Santo Amaro - Guarujá.', url: 'https://hsamaro.org.br/trabalhe-conosco?page=1', type: 'Vaga' },
  { title: 'APAS - Santos', icon: 'briefcase', description: 'Vagas de emprego para a APAS - Santos.', url: 'https://www.apassantos.com.br/trabalhe-conosco', type: 'Vaga' },
  { title: 'Grupo Fleury', icon: 'briefcase', description: 'Vagas de emprego para o Grupo Fleury.', url: 'https://trabalheconosco.vagas.com.br/grupo-fleury', type: 'Vaga' },
  { title: 'Seconci SP', icon: 'briefcase', description: 'Vagas de emprego para a Seconci SP.', url: 'https://www.seconci-sp.org.br/trabalhe-conosco', type: 'Vaga' },
  { title: 'Kenoby Empregos', icon: 'briefcase', description: 'Vagas de emprego para a área da saúde e outros setores.', url: 'https://jobs.kenoby.com/dasahospitais/', type: 'Vaga' },
  { title: 'Curriculum', icon: 'briefcase', description: 'Ampla plataforma de currículos e vagas de emprego.', url: 'https://www.curriculum.com.br/candidatos/vagas-emprego/', type: 'Vaga' },
  { title: 'Netvagas', icon: 'briefcase', description: 'Portal de empregos com foco em diversas áreas.', url: 'https://www.netvagas.com.br/', type: 'Vaga' },
  { title: 'Empregare', icon: 'briefcase', description: 'Vagas para a área da saúde e outras áreas.', url: 'https://www.empregare.com/pt-br/login?tipo=candidato&ReturnUrl=/candidato/curriculo', type: 'Vaga' },
  { title: 'CEJAM', icon: 'briefcase', description: 'Processos seletivos para a área da saúde no CEJAM.', url: 'https://cejam.org.br/processo-seletivos', type: 'Vaga' },
  { title: 'Fundação ABC', icon: 'briefcase', description: 'Oportunidades de emprego na área da saúde na Fundação ABC.', url: 'https://fuabc.org.br/trabalhe-conosco/', type: 'Vaga' },
  { title: 'Hapvida - Notredame', icon: 'briefcase', description: 'Vagas de emprego para a Hapvida e Notredame.', url: 'https://www.gndi.com.br/institucional/trabalhe-conosco', type: 'Vaga' },
  { title: 'Rede Lucy Montoro', icon: 'briefcase', description: 'Vagas de emprego para a Rede Lucy Montoro.', url: 'https://redelucymontoro.org.br/site/trabalhe-conosco/', type: 'Vaga' },
  { title: 'Hospital Moriah', icon: 'briefcase', description: 'Vagas de emprego para o Hospital Moriah.', url: 'https://www.hospitalmoriah.com.br/atendimento/trabalhe-conosco/', type: 'Vaga' },
  { title: 'Caminho de Damasco', icon: 'briefcase', description: 'Vagas de emprego para o Caminho de Damasco.', url: 'https://sbcdsaude.org.br/editais-de-processo-seletivo/', type: 'Vaga' },
  { title: 'Santa Casa de Santos', icon: 'briefcase', description: 'Vagas de emprego para a Santa Casa de Santos.', url: 'https://rh.scsantos.com.br/framehtml/RM/Rhu-BancoTalentos/#/RM/Rhu-BancoTalentos/painelVagas/lista', type: 'Vaga' },
  { title: 'Strattner', icon: 'briefcase', description: 'Vagas de emprego para a Strattner.', url: 'https://www.strattner.com.br/carreira/', type: 'Vaga' },
  { title: 'Fundação São Francisco Xavier', icon: 'briefcase', description: 'Vagas de emprego para a Fundação São Francisco Xavier.', url: 'https://trabalheconosco.vagas.com.br/fsfx', type: 'Vaga' },
  { title: 'Hospital Beneficência Portuguesa de São Paulo', icon: 'briefcase', description: 'Vagas de emprego para o Hospital Beneficência Portuguesa de São Paulo.', url: 'https://www.bp.org.br/institucional/trabalhe-conosco', type: 'Vaga' },
  { title: 'In Saúde', icon: 'briefcase', description: 'Vagas de emprego para a In Saúde.', url: 'https://www.insaude.org.br/trabalhe-conosco', type: 'Vaga' },
  { title: 'Médicos Sem Fronteiras', icon: 'heart-pulse', description: 'Oportunidades para enfermeiros em projetos humanitários ao redor do mundo.', url: 'https://www.msf.org.br/profissao/enfermeiro/', type: 'Vaga' },
  { title: 'BNE', icon: 'briefcase', description: 'Banco Nacional de Empregos com vagas de enfermagem em todo o Brasil.', url: 'https://www.bne.com.br/vagas-de-emprego-para-enfermeiro', type: 'Vaga' },
  { title: 'Só Enfermagem Vagas', icon: 'briefcase', description: 'Portal especializado com vagas e notícias exclusivas para a área de enfermagem.', url: 'https://www.soenfermagem.net/empregos/', type: 'Vaga' },
  { title: 'Indeed', icon: 'briefcase', description: 'Agregador de vagas que reúne oportunidades de diversos sites em um só lugar.', url: 'https://br.indeed.com/q-enfermeiro-l-s%C3%A3o-paulo,-sp-vagas.html', type: 'Vaga' },
  { title: 'Enfermagem Vagas', icon: 'briefcase', description: 'Site com foco total em vagas para técnicos, auxiliares e enfermeiros.', url: 'https://www.enfermagemvagas.com.br/', type: 'Vaga' },
  { title: 'Prepara Enfermagem', icon: 'award', description: 'Portal especializado em concursos públicos para a área de enfermagem.', url: 'https://preparaenfermagem.com.br/concursos', type: 'Concurso' },
  { title: 'Fundatec Concursos', icon: 'award', description: 'Banca organizadora que realiza diversos concursos na área da saúde.', url: 'https://www.fundatec.org.br/portal/concursos/', type: 'Concurso' },
  { title: 'PCI Concursos', icon: 'award', description: 'Agregador com notícias e vagas de concursos para enfermeiros em todo o Brasil.', url: 'https://www.pciconcursos.com.br/cargos/enfermeiro', type: 'Concurso' },
  { title: 'Estratégia Concursos', icon: 'award', description: 'Cursos preparatórios e notícias sobre os principais editais da área da saúde.', url: 'https://www.estrategiaconcursos.com.br/blog/concursos-area-da-saude/', type: 'Concurso' }
];

