(function(root,factory){const mod=factory();if(typeof module==='object'&&module.exports)module.exports=mod;else{root.NursingModules||={};root.NursingModules.dimensioning=mod;}})(typeof globalThis==='object'?globalThis:this,()=>{
'use strict';
const SECTORS=Object.freeze({internacao:'Unidade de internação',centro_cirurgico:'Centro cirúrgico',hemodialise:'Hemodiálise',oncologia:'Oncologia / hematologia',urgencia:'Urgência / emergência (UAE)',cme:'Central de Material e Esterilização (CME)',cdi:'Centro de Diagnóstico por Imagem (CDI)',saude_mental:'Saúde mental / psiquiatria',caps:'CAPS / serviço sem SCP (ESP)',aps:'Atenção Primária à Saúde (WISN)'});
const SOURCES=Object.freeze([{title:'COFEN — Parecer Normativo nº 1/2024',url:'https://www.cofen.gov.br/parecer-normativo-no-1-2024-cofen/'},{title:'Perroca (2011)',url:'https://doi.org/10.1590/S0104-11692011000100009'},{title:'Santos et al. (2007) — Fugulin complementado',url:'https://doi.org/10.1590/S0104-11692007000500015'}]);
function n(value,name,min=0,max=Number.POSITIVE_INFINITY){const x=Number(value);if(!Number.isFinite(x)||x<min||x>max)throw new Error(name+' inválido.');return x;}
const r2=x=>Math.round((Number(x)+Number.EPSILON)*100)/100;
function team(raw,nursePct=null){const rounded=Math.round(n(raw,'Quadro calculado'));if(nursePct==null)return {raw:r2(raw),rounded};const pct=n(nursePct,'Percentual de enfermeiros',0,100),nurses=Math.round(rounded*pct/100);return {raw:r2(raw),rounded,nursePct:pct,nurses,technicians:Math.max(0,rounded-nurses)};}
function workloadToStaff(hours,{ds=7,ist=15,chs=40}={}){hours=n(hours,'Horas de trabalho',0);ds=n(ds,'Dias de funcionamento',1,7);ist=n(ist,'IST',0,300);chs=n(chs,'CHS',1,168);return team(hours*ds*(1+ist/100)/chs);}
function classPct(name){const s=String(name||'').toLowerCase();if(s.includes('intensiv')&&!s.includes('semi'))return 52;if(s.includes('semi'))return 42;if(s.includes('alta'))return 36;return 33;}
function dates(from,to){if(!/^\d{4}-\d{2}-\d{2}$/.test(from||'')||!/^\d{4}-\d{2}-\d{2}$/.test(to||'')||from>to)throw new Error('Período inválido.');const out=[];for(let d=new Date(from+'T12:00:00Z'),end=new Date(to+'T12:00:00Z');d<=end;d.setUTCDate(d.getUTCDate()+1))out.push(d.toISOString().slice(0,10));if(out.length>366)throw new Error('O período máximo é de 366 dias.');return out;}
function latestDaily(assessments,{instrument,unit='',from,to}={}){const map=new Map();for(const a of assessments||[]){if(a.module_id!==instrument||a.module_version==='legacy-prototype'||a.eval_date<from||a.eval_date>to)continue;const snap=a.snapshot||{};if(unit&&snap.unit!==unit)continue;const key=a.patient_id+'|'+a.eval_date,old=map.get(key),stamp=(a.eval_date||'')+'T'+(a.eval_time||'00:00')+'|'+String(a.id||0).padStart(12,'0'),oldStamp=old?((old.eval_date||'')+'T'+(old.eval_time||'00:00')+'|'+String(old.id||0).padStart(12,'0')):'';if(!old||stamp>oldStamp)map.set(key,a);}return [...map.values()];}
function inpatientDatabase({assessments,instrument='fugulin',unit='',from,to,chs=40,ist=15}={}){if(!['fugulin','perroca'].includes(instrument))throw new Error('Escolha Fugulin ou Perroca.');if(!unit)throw new Error('Escolha o setor para usar as avaliações salvas.');const period=dates(from,to),rows=latestDaily(assessments,{instrument,unit,from,to});if(!rows.length)throw new Error('Não há classificações compatíveis no período e setor selecionados.');const byDay=new Map(),loadByClass=new Map();for(const a of rows){const h=n(a.hours,'Horas da avaliação',0,24),d=byDay.get(a.eval_date)||{date:a.eval_date,hours:0,patients:0};d.hours+=h;d.patients++;byDay.set(a.eval_date,d);loadByClass.set(a.classification,(loadByClass.get(a.classification)||0)+h);}const observed=[...byDay.values()].sort((a,b)=>a.date.localeCompare(b.date)),avgHours=observed.reduce((s,d)=>s+d.hours,0)/observed.length,avgPatients=observed.reduce((s,d)=>s+d.patients,0)/observed.length,prevalent=[...loadByClass.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]||'',q=workloadToStaff(avgHours,{ds:7,ist,chs}),dist=team(q.raw,classPct(prevalent));return {method:'SCP com avaliações salvas',instrument,unit,from,to,records:rows.length,observedDays:observed.length,totalDays:period.length,missingDates:period.filter(d=>!byDay.has(d)),averageDailyHours:r2(avgHours),averagePatients:r2(avgPatients),prevalentClass:prevalent,...dist,daily:observed,note:'Foi usada somente a última classificação de cada paciente em cada dia. A taxa de ocupação não é reaplicada ao censo observado.'};}
function inpatientManual({classes,occupancy=100,chs=40,ist=15}={}){if(!Array.isArray(classes)||!classes.length)throw new Error('Informe as classes de pacientes.');occupancy=n(occupancy,'Taxa de ocupação',0,100);let hours=0,patients=0;const loads=[];for(const c of classes){const count=n(c.count||0,'Quantidade de pacientes',0,100000)*occupancy/100,h=n(c.hours,'Horas por paciente',0,24),load=count*h;hours+=load;patients+=count;loads.push({...c,considered:r2(count),workload:r2(load)});}const prevalent=loads.slice().sort((a,b)=>b.workload-a.workload)[0]?.name||'',q=workloadToStaff(hours,{ds:7,ist,chs});return {method:'SCP com contagem manual',occupancy,consideredPatients:r2(patients),dailyHours:r2(hours),prevalentClass:prevalent,classes:loads,...team(q.raw,classPct(prevalent)),note:'A taxa de ocupação foi aplicada à contagem planejada. Não use este modo para reaplicar TO a um censo diário já observado.'};}
function operatingRoom({p1=0,p2=0,p3=0,p4=0,ds=5,ist=15,chs=30}={}){const counts=[p1,p2,p3,p4].map((x,i)=>n(x,'Cirurgias porte '+(i+1),0,100000)),times=[2.1,3.6,5.6,9.1],hours=counts.reduce((s,x,i)=>s+x*times[i],0);return {method:'Portes cirúrgicos eletivos',dailyHours:r2(hours),counts,times,...workloadToStaff(hours,{ds,ist,chs}),note:'Inclui 0,5 h de preparo/organização e 0,2 h de espera por cirurgia eletiva. Urgência/emergência deve ser dimensionada por UAE/ESP.'};}
function hemodialysis({patients=0,ds=6,ist=15,chs=30}={}){patients=n(patients,'Pacientes por turno',0,100000);const hours=patients*4,q=workloadToStaff(hours,{ds,ist,chs});return {method:'Hemodiálise — 4 h/paciente/sessão',patients,dailyHours:r2(hours),...team(q.raw,25),note:'Além do quadro assistencial: 1 enfermeiro especialista em Nefrologia exclusivo para coordenação e, quando houver reprocessamento, 1 técnico por turno.'};}
function oncology({patients=0,ds=5,chs=30}={}){patients=n(patients,'Média diária de pacientes',0,100000);ds=n(ds,'Dias de funcionamento',1,7);chs=n(chs,'CHS',1,168);const C=3.31*(patients+4.4),t=chs/ds,enf=C*.8*1.15/t,tec=C*.2/t;return {method:'Oncologia/hematologia — reconstrução didática',patients,workload:r2(C),nurseRaw:r2(enf),nurses:Math.round(enf),technicianRaw:r2(tec),technicians:Math.round(tec),rounded:Math.round(enf)+Math.round(tec),reconstructed:true,note:'h=3,31 h; Sn=4,4; 80% Enfermeiro e 20% Técnico. A equação foi reconstruída a partir das variáveis do Parecer e deve ser conferida no documento oficial antes de uso institucional.'};}
function activity({activities=[],ds=5,ist=15,chs=30}={}){if(!Array.isArray(activities)||!activities.length)throw new Error('Informe pelo menos uma atividade.');let dailyHours=0;const rows=activities.map(a=>{const volume=n(a.volume,'Volume médio diário',0,1e9),minutes=n(a.minutes,'Tempo médio',0,1440),hours=volume*minutes/60;dailyHours+=hours;return {name:String(a.name||'Atividade').slice(0,120),volume,minutes,hours:r2(hours)};});return {method:'Tempo por atividade',dailyHours:r2(dailyHours),activities:rows,...workloadToStaff(dailyHours,{ds,ist,chs})};}
function cdi({nurseActivities=[],technicianActivities=[],ds=5,ist=15,chs=30}={}){const nurse=activity({activities:nurseActivities,ds,ist,chs}),technician=activity({activities:technicianActivities,ds,ist,chs});return {method:'CDI — cálculo separado por categoria',nurse,technician,rounded:nurse.rounded+technician.rounded,note:'Use os tempos de participação de cada categoria conforme o procedimento; o serviço deve manter ao menos um Enfermeiro durante a assistência de Enfermagem.'};}
function weeklyMirror({weeklyHours=0,ist=15,chs=40}={}){weeklyHours=n(weeklyHours,'Horas semanais do espelho',0,1e9);ist=n(ist,'IST',0,300);chs=n(chs,'CHS',1,168);return {method:'Sítio Funcional + Espelho Semanal Padrão',weeklyHours,...team(weeklyHours*(1+ist/100)/chs),note:'Informe a soma das horas semanais dos postos/sítios funcionais necessários, baseada no espelho de 4 a 6 semanas e na realidade do serviço.'};}
function mentalHealth({gdd=0,gdi=0,gdp=0,occupancy=100,chs=40,ist=15}={}){occupancy=n(occupancy,'Taxa de ocupação',0,100);const groups=[{name:'GDD',count:n(gdd,'GDD',0)*occupancy/100,hours:4,nursePct:33},{name:'GDI',count:n(gdi,'GDI',0)*occupancy/100,hours:6,nursePct:36},{name:'GDP',count:n(gdp,'GDP',0)*occupancy/100,hours:10,nursePct:42}],dailyHours=groups.reduce((s,g)=>s+g.count*g.hours,0),prevalent=groups.slice().sort((a,b)=>(b.count*b.hours)-(a.count*a.hours))[0],q=workloadToStaff(dailyHours,{ds:7,ist,chs});return {method:'SCP Saúde Mental — Martins/Vieira',groups:groups.map(g=>({...g,count:r2(g.count)})),dailyHours:r2(dailyHours),prevalentClass:prevalent.name,...team(q.raw,prevalent.nursePct),note:'GDD 4 h/33%; GDI 6 h/36%; GDP 10 h/42%. Confira o SCP adotado pela instituição.'};}
function wisn({weeks=52,daysWeek=5,holidays=10,vacation=20,legal=5,other=3,hoursDay=8,activities=[],indirectPct=0}={}){weeks=n(weeks,'Semanas',1,53);daysWeek=n(daysWeek,'Dias por semana',1,7);holidays=n(holidays,'Feriados',0,366);vacation=n(vacation,'Férias',0,366);legal=n(legal,'Ausências legais',0,366);other=n(other,'Outras licenças',0,366);hoursDay=n(hoursDay,'Horas por dia',.1,24);indirectPct=n(indirectPct,'Cuidado indireto',0,500);const A=weeks*daysWeek,available=A-(holidays+vacation+legal+other);if(available<=0)throw new Error('O TTD precisa ser maior que zero.');const ttd=available*hoursDay;let qdir=0;const rows=(activities||[]).map(a=>{const production=n(a.production,'Produção anual',0,1e12),hours=n(a.hours,'Tempo médio da atividade',0,24),q=production*hours/ttd;qdir+=q;return {name:String(a.name||'Atividade').slice(0,120),production,hours,q:r2(q)};});if(!rows.length)throw new Error('Informe pelo menos uma atividade de cuidado direto.');const total=qdir*(1+indirectPct/100);return {method:'APS — WISN adaptado',availableDays:r2(available),ttd:r2(ttd),activities:rows,qdir:r2(qdir),indirectPct,totalRaw:r2(total),rounded:Math.round(total),note:'O Qind% deve refletir as atividades indiretas efetivamente realizadas pela categoria no último ano; calcule cada categoria separadamente.'};}
return Object.freeze({sectors:SECTORS,sources:SOURCES,team,workloadToStaff,latestDaily,inpatientDatabase,inpatientManual,operatingRoom,hemodialysis,oncology,activity,cdi,weeklyMirror,mentalHealth,wisn});
});
