'use strict';
const fs=require('node:fs'),path=require('node:path');const {seal,open}=require('./crypto');const {getModule}=require('../modules/registry');
function text(value,max=180){if(value==null)return '';if(typeof value!=='string'||value.length>max)throw new Error('Campo de texto inválido ou muito longo.');return value.trim();}
function validId(v){if(!Number.isSafeInteger(v)||v<1)throw new Error('Registro inválido.');return v;}
function date(value){const v=text(value,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(v)||Number.isNaN(Date.parse(v+'T12:00:00Z'))||new Date(v+'T12:00:00Z').toISOString().slice(0,10)!==v)throw new Error('Data inválida.');return v;}
function patient(p){const name=text(p.name);if(!name)throw new Error('Informe o nome do paciente.');const birthdate=p.birthdate?date(p.birthdate):'';if(birthdate&&birthdate>new Date().toISOString().slice(0,10))throw new Error('Nascimento não pode estar no futuro.');return {name,prontuario:text(p.prontuario,80),birthdate,unit:text(p.unit,120),bed:text(p.bed,50)};}
function validatePopulation(p,a){if(p.birthdate){let years=Number(a.eval_date.slice(0,4))-Number(p.birthdate.slice(0,4));if(a.eval_date.slice(5)<p.birthdate.slice(5))years--;if(years<18)throw new Error('Este módulo de Fugulin é destinado a pacientes adultos.');}}
function prepareAssessment(a){const mod=getModule(a.module_id||'fugulin'),result=mod.calculate(a.scores);const professional=text(a.professional);if(!professional)throw new Error('Informe o profissional responsável.');return {module_id:mod.id,module_version:mod.version,professional,eval_date:date(a.eval_date),eval_time:(()=>{const value=a.eval_time||'00:00';if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(value))throw new Error('Hora da avaliação inválida.');return value;})(),scores:JSON.stringify(a.scores),total:result.total,classification:result.name,hours:result.hours,notes:text(a.notes,12000),diagnosis:text(a.diagnosis,6000)};}
class Store{
 constructor(SQL,file,key){this.SQL=SQL;this.file=file;this.key=key;this.db=fs.existsSync(file)?new SQL.Database(open(fs.readFileSync(file),key)):new SQL.Database();this.migrate();this.persist();}
 query(sql,params=[]){const st=this.db.prepare(sql);try{st.bind(params);const out=[];while(st.step())out.push(st.getAsObject());return out;}finally{st.free();}}
 run(sql,params=[]){this.db.run(sql,params);}
 migrate(){this.db.run(`PRAGMA foreign_keys=ON; CREATE TABLE IF NOT EXISTS patients(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,prontuario TEXT,birthdate TEXT,unit TEXT,bed TEXT,archived INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS assessments(id INTEGER PRIMARY KEY AUTOINCREMENT,patient_id INTEGER NOT NULL REFERENCES patients(id) ON DELETE CASCADE,professional TEXT,eval_date TEXT,eval_time TEXT DEFAULT '00:00',scores TEXT NOT NULL,total INTEGER NOT NULL,classification TEXT NOT NULL,hours REAL,module_id TEXT DEFAULT 'fugulin',module_version TEXT DEFAULT '2.0.0',snapshot TEXT,notes TEXT DEFAULT '',diagnosis TEXT DEFAULT '',revision INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL); CREATE TABLE IF NOT EXISTS drafts(key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY AUTOINCREMENT,action TEXT NOT NULL,record_id INTEGER,previous TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
 const additions={patients:{archived:'INTEGER DEFAULT 0'},assessments:{eval_time:"TEXT DEFAULT '00:00'",module_id:"TEXT DEFAULT 'fugulin'",module_version:"TEXT DEFAULT 'legacy-prototype'",snapshot:'TEXT',notes:"TEXT DEFAULT ''",diagnosis:"TEXT DEFAULT ''",revision:'INTEGER DEFAULT 1'}};
 for(const [table,cols]of Object.entries(additions)){const names=this.query(`PRAGMA table_info(${table})`).map(r=>r.name);for(const [name,type]of Object.entries(cols))if(!names.includes(name))this.run(`ALTER TABLE ${table} ADD COLUMN ${name} ${type}`);}
 this.run('CREATE INDEX IF NOT EXISTS assessments_patient_date ON assessments(patient_id,eval_date,eval_time)');this.run('PRAGMA user_version=2');}
 exportBytes(){const bytes=this.db.export();this.db.run("PRAGMA foreign_keys=ON");return bytes;}
 persist(){fs.mkdirSync(path.dirname(this.file),{recursive:true});const tmp=this.file+'.tmp';const data=seal(Buffer.from(this.exportBytes()),this.key);const fd=fs.openSync(tmp,'w',0o600);try{fs.writeFileSync(fd,data);fs.fsyncSync(fd);}finally{fs.closeSync(fd);}if(fs.existsSync(this.file))fs.copyFileSync(this.file,this.file+'.previous');fs.renameSync(tmp,this.file);}
 tx(fn){const before=this.exportBytes();this.run('BEGIN IMMEDIATE');try{const result=fn();this.run('COMMIT');this.persist();return result;}catch(e){try{this.run('ROLLBACK');}catch{}this.db.close();this.db=new this.SQL.Database(before);this.db.run('PRAGMA foreign_keys=ON');throw e;}}
 audit(action,id,previous=null){this.run('INSERT INTO audit(action,record_id,previous) VALUES(?,?,?)',[action,id,previous?JSON.stringify(previous):null]);}
 list(){return this.query(`SELECT p.*, (SELECT COUNT(*) FROM assessments a WHERE a.patient_id=p.id) AS assessment_count FROM patients p ORDER BY p.name COLLATE NOCASE`);}
 history(id){return this.query('SELECT * FROM assessments WHERE patient_id=? ORDER BY eval_date DESC,eval_time DESC,id DESC',[validId(id)]).map(r=>({...r,scores:JSON.parse(r.scores),snapshot:r.snapshot?JSON.parse(r.snapshot):null}));}
 save(input){if(!input||typeof input!=='object')throw new Error('Avaliação inválida.');const p=patient(input.patient),a=prepareAssessment(input.assessment);validatePopulation(p,a);return this.tx(()=>{
 let pid=input.patient.id?validId(input.patient.id):null; if(pid&&!this.query('SELECT id FROM patients WHERE id=?',[pid]).length)throw new Error('Paciente não encontrado.');
 let old=null;if(input.assessment.id){old=this.query('SELECT * FROM assessments WHERE id=? AND patient_id=?',[validId(input.assessment.id),pid])[0];if(!old)throw new Error('A avaliação pertence a outro paciente ou não existe.');}
 if(pid&&!old)this.run('UPDATE patients SET name=?,prontuario=?,birthdate=?,unit=?,bed=? WHERE id=?',[...Object.values(p),pid]);else if(!pid){this.run('INSERT INTO patients(name,prontuario,birthdate,unit,bed) VALUES(?,?,?,?,?)',Object.values(p));pid=this.query('SELECT last_insert_rowid() AS id')[0].id;}
 const snapshot=JSON.stringify({...p,id:pid});let id;
 if(old){id=old.id;this.audit('assessment:corrected',id,old);this.run('UPDATE assessments SET professional=?,eval_date=?,eval_time=?,scores=?,total=?,classification=?,hours=?,module_id=?,module_version=?,snapshot=?,notes=?,diagnosis=?,revision=revision+1,updated_at=CURRENT_TIMESTAMP WHERE id=?',[a.professional,a.eval_date,a.eval_time,a.scores,a.total,a.classification,a.hours,a.module_id,a.module_version,snapshot,a.notes,a.diagnosis,id]);}
 else{this.run('INSERT INTO assessments(patient_id,professional,eval_date,eval_time,scores,total,classification,hours,module_id,module_version,snapshot,notes,diagnosis) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',[pid,a.professional,a.eval_date,a.eval_time,a.scores,a.total,a.classification,a.hours,a.module_id,a.module_version,snapshot,a.notes,a.diagnosis]);id=this.query('SELECT last_insert_rowid() AS id')[0].id;this.audit('assessment:created',id);}
 this.run("DELETE FROM drafts WHERE key='current'");return {patient:this.query('SELECT * FROM patients WHERE id=?',[pid])[0],assessment:this.history(pid).find(r=>r.id===id)};});}
 archive(id,value){id=validId(id);return this.tx(()=>{this.run('UPDATE patients SET archived=? WHERE id=?',[value?1:0,id]);this.audit(value?'patient:archived':'patient:reactivated',id);return true;});}
 deletePatient(id){id=validId(id);return this.tx(()=>{this.audit('patient:deleted',id,{patient:this.query('SELECT * FROM patients WHERE id=?',[id])[0],assessments:this.history(id)});this.run('DELETE FROM assessments WHERE patient_id=?',[id]);this.run('DELETE FROM patients WHERE id=?',[id]);return true;});}
 deleteAssessment(id){id=validId(id);return this.tx(()=>{const old=this.query('SELECT * FROM assessments WHERE id=?',[id])[0];if(!old)throw new Error('Avaliação não encontrada.');this.audit('assessment:deleted',id,old);this.run('DELETE FROM assessments WHERE id=?',[id]);return true;});}
 settings(value){if(value===undefined){return Object.fromEntries(this.query('SELECT * FROM settings').map(r=>[r.key,JSON.parse(r.value)]));}const clean={institution:text(value.institution,200),professional:text(value.professional),unit:text(value.unit,120),fontScale:[100,110,125].includes(value.fontScale)?value.fontScale:100,highContrast:!!value.highContrast};return this.tx(()=>{for(const [k,v]of Object.entries(clean))this.run('INSERT OR REPLACE INTO settings(key,value) VALUES(?,?)',[k,JSON.stringify(v)]);return clean;});}
 draft(value){if(value===undefined){const r=this.query("SELECT value FROM drafts WHERE key='current'")[0];return r?JSON.parse(r.value):null;}if(value===null)return this.tx(()=>{this.run("DELETE FROM drafts WHERE key='current'");return true;});const str=JSON.stringify(value);if(str.length>40000)throw new Error('Rascunho muito grande.');return this.tx(()=>{this.run("INSERT OR REPLACE INTO drafts(key,value) VALUES('current',?)",[str]);return true;});}
 bytes(){return Buffer.from(this.exportBytes());}
 validateImport(bytes){if(bytes.length>100*1024*1024)throw new Error('Backup excede 100 MB.');let candidate;try{candidate=new this.SQL.Database(bytes);const check=candidate.exec('PRAGMA integrity_check');if(check[0]?.values[0]?.[0]!=='ok')throw new Error();for(const table of ['patients','assessments']){const cols=candidate.exec(`PRAGMA table_info(${table})`);if(!cols[0]?.values?.length)throw new Error();}const schema=candidate.exec("SELECT type,name FROM sqlite_master WHERE name NOT LIKE 'sqlite_%'");
 const allowed=['patients','assessments','settings','drafts','audit'];
 if(schema[0]?.values.some(([type,name])=>type==='trigger'||type==='view'||(type==='table'&&!allowed.includes(name))))throw new Error();
 candidate.exec('SELECT id,name,prontuario,birthdate,unit,bed FROM patients');candidate.exec('SELECT id,patient_id,professional,eval_date,scores,total,classification,hours,created_at,updated_at FROM assessments');const orphan=candidate.exec('SELECT count(*) FROM assessments a LEFT JOIN patients p ON a.patient_id=p.id WHERE p.id IS NULL');if(orphan[0].values[0][0]!==0)throw new Error();
 const version=candidate.exec('PRAGMA user_version')[0].values[0][0];if(version>2)throw new Error();
 const read=sql=>{const st=candidate.prepare(sql),rows=[];try{while(st.step()){rows.push(st.getAsObject());if(rows.length>200000)throw new Error();}return rows;}finally{st.free();}};
 for(const row of read('SELECT * FROM patients')){validId(row.id);patient(row);}
 for(const row of read('SELECT * FROM assessments')){
  validId(row.id);validId(row.patient_id);date(row.eval_date);
  const scores=JSON.parse(row.scores);if(!scores||Array.isArray(scores)||typeof scores!=='object')throw new Error();
  if(Object.keys(scores).some(id=>!getModule('fugulin').criteria.some(c=>c.id===id)))throw new Error();
  for(const score of Object.values(scores))if(!Number.isInteger(score)||score<0||score>4)throw new Error();
  if(Object.keys(scores).length!==12||!Number.isInteger(row.total)||row.total<12||row.total>48||row.total!==Object.values(scores).reduce((n,v)=>n+v,0))throw new Error();
  if(row.snapshot){const snapshot=JSON.parse(row.snapshot);patient(snapshot);}
  if(row.module_version&&row.module_version!=='legacy-prototype'){
   const mod=getModule(row.module_id);if(row.module_version!==mod.version)throw new Error();
   const computed=mod.calculate(scores);if(row.total!==computed.total||row.hours!==computed.hours||row.classification!==computed.name)throw new Error();
   prepareAssessment({...row,scores});
  }
 }
 if(schema[0]?.values.some(([type,name])=>type==='table'&&name==='settings'))for(const row of read('SELECT * FROM settings')){const val=JSON.parse(row.value);if(!['institution','professional','unit','fontScale','highContrast'].includes(row.key))throw new Error();if(['institution','professional','unit'].includes(row.key))text(val,200);if(row.key==='fontScale'&&![100,110,125].includes(val))throw new Error();if(row.key==='highContrast'&&typeof val!=='boolean')throw new Error();}
 if(schema[0]?.values.some(([type,name])=>type==='table'&&name==='drafts'))for(const row of read('SELECT * FROM drafts')){if(row.key!=='current')throw new Error();const draft=JSON.parse(row.value);if(!draft?.patient||!draft?.assessment||typeof draft.patient.name!=='string'||JSON.stringify(draft).length>40000)throw new Error();for(const score of Object.values(draft.assessment.scores||{}))if(!Number.isInteger(score)||score<0||score>4)throw new Error();}
 return true;}catch{throw new Error('O backup não é um banco de dados compatível e íntegro.');}finally{candidate?.close();}}
 replace(bytes){this.validateImport(bytes);const previous=this.exportBytes();try{this.db.close();this.db=new this.SQL.Database(bytes);this.migrate();this.audit('backup:restored',null);this.persist();}catch(e){this.db.close();this.db=new this.SQL.Database(previous);this.db.run('PRAGMA foreign_keys=ON');throw e;}}
 allAssessments(){return this.query('SELECT * FROM assessments ORDER BY eval_date DESC,eval_time DESC,id DESC').map(r=>({...r,scores:JSON.parse(r.scores),snapshot:r.snapshot?JSON.parse(r.snapshot):null}));}
 close(){this.db.close();}
}
module.exports={Store,patient,prepareAssessment,date,validatePopulation};
