'use strict';
const fs=require('node:fs'),path=require('node:path');const {seal,open}=require('./crypto');const {getModule}=require('../modules/registry');const {prepare:prepareClinical,bindIdentity}=require('../modules/anamnesis');
function text(value,max=180){if(value==null)return '';if(typeof value!=='string'||value.length>max)throw new Error('Campo de texto inválido ou muito longo.');return value.trim();}
function validId(v){if(!Number.isSafeInteger(v)||v<1)throw new Error('Registro inválido.');return v;}
function date(value){const v=text(value,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(v)||Number.isNaN(Date.parse(v+'T12:00:00Z'))||new Date(v+'T12:00:00Z').toISOString().slice(0,10)!==v)throw new Error('Data inválida.');return v;}
function patient(p){const name=text(p.name);if(!name)throw new Error('Informe o nome do paciente.');const birthdate=p.birthdate?date(p.birthdate):'';if(birthdate&&birthdate>new Date().toISOString().slice(0,10))throw new Error('Nascimento não pode estar no futuro.');return {name,prontuario:text(p.prontuario,80),birthdate,unit:text(p.unit,120),bed:text(p.bed,50)};}
function validatePopulation(p,a){if(p.birthdate){let years=Number(a.eval_date.slice(0,4))-Number(p.birthdate.slice(0,4));if(a.eval_date.slice(5)<p.birthdate.slice(5))years--;if(years<18)throw new Error('Este instrumento é destinado a pacientes adultos.');}}
function prepareAssessment(a){const mod=getModule(a.module_id||'fugulin'),result=mod.calculate(a.scores);const professional=text(a.professional);if(!professional)throw new Error('Informe o profissional responsável.');return {module_id:mod.id,module_version:mod.version,professional,eval_date:date(a.eval_date),eval_time:(()=>{const value=a.eval_time||'00:00';if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(value))throw new Error('Hora da avaliação inválida.');return value;})(),scores:JSON.stringify(a.scores),total:result.total,classification:result.name,hours:result.hours,notes:text(a.notes,12000),diagnosis:text(a.diagnosis,6000)};}
class Store{
 constructor(SQL,file,key){this.SQL=SQL;this.file=file;this.key=key;this.db=fs.existsSync(file)?new SQL.Database(open(fs.readFileSync(file),key)):new SQL.Database();if(this.db.exec('PRAGMA user_version')[0].values[0][0]>4){this.db.close();throw new Error('Este banco foi criado por uma versão mais recente do programa.');}this.migrate();this.persist();}
 query(sql,params=[]){const st=this.db.prepare(sql);try{st.bind(params);const out=[];while(st.step())out.push(st.getAsObject());return out;}finally{st.free();}}
 run(sql,params=[]){this.db.run(sql,params);}
 migrate(){this.db.run(`PRAGMA foreign_keys=ON; CREATE TABLE IF NOT EXISTS patients(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,prontuario TEXT,birthdate TEXT,unit TEXT,bed TEXT,archived INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS assessments(id INTEGER PRIMARY KEY AUTOINCREMENT,patient_id INTEGER NOT NULL REFERENCES patients(id) ON DELETE CASCADE,professional TEXT,eval_date TEXT,eval_time TEXT DEFAULT '00:00',scores TEXT NOT NULL,total INTEGER NOT NULL,classification TEXT NOT NULL,hours REAL,module_id TEXT DEFAULT 'fugulin',module_version TEXT DEFAULT '2.0.0',snapshot TEXT,notes TEXT DEFAULT '',diagnosis TEXT DEFAULT '',revision INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL); CREATE TABLE IF NOT EXISTS drafts(key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS clinical_records(id INTEGER PRIMARY KEY AUTOINCREMENT,patient_id INTEGER NOT NULL REFERENCES patients(id) ON DELETE CASCADE,method_id TEXT NOT NULL,template_version TEXT NOT NULL,professional TEXT,coren TEXT,record_type TEXT,eval_date TEXT,eval_time TEXT,values_json TEXT NOT NULL,snapshot TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS clinical_drafts(patient_id INTEGER NOT NULL REFERENCES patients(id) ON DELETE CASCADE,method_id TEXT NOT NULL,value TEXT NOT NULL,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(patient_id,method_id)); CREATE TABLE IF NOT EXISTS dimensioning_records(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,sector_type TEXT NOT NULL,unit TEXT,instrument TEXT,reference_date TEXT NOT NULL,params_json TEXT NOT NULL,result_json TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY AUTOINCREMENT,action TEXT NOT NULL,record_id INTEGER,previous TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
 const additions={patients:{archived:'INTEGER DEFAULT 0'},assessments:{eval_time:"TEXT DEFAULT '00:00'",module_id:"TEXT DEFAULT 'fugulin'",module_version:"TEXT DEFAULT 'legacy-prototype'",snapshot:'TEXT',notes:"TEXT DEFAULT ''",diagnosis:"TEXT DEFAULT ''",revision:'INTEGER DEFAULT 1'}};
 for(const [table,cols]of Object.entries(additions)){const names=this.query(`PRAGMA table_info(${table})`).map(r=>r.name);for(const [name,type]of Object.entries(cols))if(!names.includes(name))this.run(`ALTER TABLE ${table} ADD COLUMN ${name} ${type}`);}
 this.run('CREATE INDEX IF NOT EXISTS assessments_patient_date ON assessments(patient_id,eval_date,eval_time)');this.run('CREATE INDEX IF NOT EXISTS clinical_patient_date ON clinical_records(patient_id,eval_date,eval_time)');this.run('CREATE INDEX IF NOT EXISTS dimensioning_sector_date ON dimensioning_records(sector_type,reference_date)');this.run('PRAGMA user_version=4');}
 exportBytes(){const bytes=this.db.export();this.db.run("PRAGMA foreign_keys=ON");return bytes;}
 persist(){fs.mkdirSync(path.dirname(this.file),{recursive:true});const tmp=this.file+'.tmp';const data=seal(Buffer.from(this.exportBytes()),this.key);const fd=fs.openSync(tmp,'w',0o600);try{fs.writeFileSync(fd,data);fs.fsyncSync(fd);}finally{fs.closeSync(fd);}if(fs.existsSync(this.file))fs.copyFileSync(this.file,this.file+'.previous');fs.renameSync(tmp,this.file);}
 tx(fn){const before=this.exportBytes();this.run('BEGIN IMMEDIATE');try{const result=fn();this.run('COMMIT');this.persist();return result;}catch(e){try{this.run('ROLLBACK');}catch{}this.db.close();this.db=new this.SQL.Database(before);this.db.run('PRAGMA foreign_keys=ON');throw e;}}
 audit(action,id,previous=null){this.run('INSERT INTO audit(action,record_id,previous) VALUES(?,?,?)',[action,id,previous?JSON.stringify(previous):null]);}
 list(){return this.query(`SELECT p.*, (SELECT COUNT(*) FROM assessments a WHERE a.patient_id=p.id) AS assessment_count, (SELECT COUNT(*) FROM clinical_records c WHERE c.patient_id=p.id) AS clinical_count FROM patients p ORDER BY p.name COLLATE NOCASE`);}
 history(id){return this.query('SELECT * FROM assessments WHERE patient_id=? ORDER BY eval_date DESC,eval_time DESC,id DESC',[validId(id)]).map(r=>({...r,scores:JSON.parse(r.scores),snapshot:r.snapshot?JSON.parse(r.snapshot):null}));}
 save(input){if(!input||typeof input!=='object')throw new Error('Avaliação inválida.');const p=patient(input.patient),a=prepareAssessment(input.assessment);validatePopulation(p,a);return this.tx(()=>{
 let pid=input.patient.id?validId(input.patient.id):null; if(pid&&!this.query('SELECT id FROM patients WHERE id=?',[pid]).length)throw new Error('Paciente não encontrado.');
 let old=null;if(input.assessment.id){old=this.query('SELECT * FROM assessments WHERE id=? AND patient_id=?',[validId(input.assessment.id),pid])[0];if(!old)throw new Error('A avaliação pertence a outro paciente ou não existe.');}
 if(pid&&!old)this.run('UPDATE patients SET name=?,prontuario=?,birthdate=?,unit=?,bed=? WHERE id=?',[...Object.values(p),pid]);else if(!pid){this.run('INSERT INTO patients(name,prontuario,birthdate,unit,bed) VALUES(?,?,?,?,?)',Object.values(p));pid=this.query('SELECT last_insert_rowid() AS id')[0].id;}
 const snapshot=JSON.stringify({...p,id:pid});let id;
 if(old){id=old.id;this.audit('assessment:corrected',id,old);this.run('UPDATE assessments SET professional=?,eval_date=?,eval_time=?,scores=?,total=?,classification=?,hours=?,module_id=?,module_version=?,snapshot=?,notes=?,diagnosis=?,revision=revision+1,updated_at=CURRENT_TIMESTAMP WHERE id=?',[a.professional,a.eval_date,a.eval_time,a.scores,a.total,a.classification,a.hours,a.module_id,a.module_version,snapshot,a.notes,a.diagnosis,id]);}
 else{this.run('INSERT INTO assessments(patient_id,professional,eval_date,eval_time,scores,total,classification,hours,module_id,module_version,snapshot,notes,diagnosis) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',[pid,a.professional,a.eval_date,a.eval_time,a.scores,a.total,a.classification,a.hours,a.module_id,a.module_version,snapshot,a.notes,a.diagnosis]);id=this.query('SELECT last_insert_rowid() AS id')[0].id;this.audit('assessment:created',id);}
 this.run("DELETE FROM drafts WHERE key='current'");return {patient:this.query('SELECT * FROM patients WHERE id=?',[pid])[0],assessment:this.history(pid).find(r=>r.id===id)};});}
 archive(id,value){id=validId(id);return this.tx(()=>{this.run('UPDATE patients SET archived=? WHERE id=?',[value?1:0,id]);this.audit(value?'patient:archived':'patient:reactivated',id);return true;});}
 deletePatient(id){id=validId(id);return this.tx(()=>{this.audit('patient:deleted',id,{patient:this.query('SELECT * FROM patients WHERE id=?',[id])[0],assessments:this.history(id),clinical_records:this.clinicalHistory(id)});this.run('DELETE FROM assessments WHERE patient_id=?',[id]);this.run('DELETE FROM clinical_drafts WHERE patient_id=?',[id]);this.run('DELETE FROM clinical_records WHERE patient_id=?',[id]);this.run('DELETE FROM patients WHERE id=?',[id]);return true;});}
 deleteAssessment(id){id=validId(id);return this.tx(()=>{const old=this.query('SELECT * FROM assessments WHERE id=?',[id])[0];if(!old)throw new Error('Avaliação não encontrada.');this.audit('assessment:deleted',id,old);this.run('DELETE FROM assessments WHERE id=?',[id]);return true;});}
 savePatient(input){const p=patient(input);const id=input.id?validId(input.id):null;return this.tx(()=>{if(id){const old=this.query('SELECT * FROM patients WHERE id=?',[id])[0];if(!old)throw new Error('Paciente não encontrado.');this.audit('patient:updated',id,old);this.run('UPDATE patients SET name=?,prontuario=?,birthdate=?,unit=?,bed=? WHERE id=?',[...Object.values(p),id]);return this.query('SELECT * FROM patients WHERE id=?',[id])[0];}this.run('INSERT INTO patients(name,prontuario,birthdate,unit,bed) VALUES(?,?,?,?,?)',Object.values(p));const created=this.query('SELECT last_insert_rowid() AS id')[0].id;this.audit('patient:created',created);return this.query('SELECT * FROM patients WHERE id=?',[created])[0];});}
 clinicalHistory(id){return this.query('SELECT * FROM clinical_records WHERE patient_id=? ORDER BY eval_date DESC,eval_time DESC,id DESC',[validId(id)]).map(r=>({...r,values:JSON.parse(r.values_json),snapshot:JSON.parse(r.snapshot)}));}
 clinicalRecord(id){const row=this.query('SELECT * FROM clinical_records WHERE id=?',[validId(id)])[0];if(!row)throw new Error('Ficha não encontrada.');return {...row,values:JSON.parse(row.values_json),snapshot:JSON.parse(row.snapshot)};}
 clinicalContext(r){const p=this.query('SELECT * FROM patients WHERE id=?',[r.patient_id])[0];if(!p)throw new Error('Paciente não encontrado.');validatePopulation(p,r);if(r.id){const old=this.clinicalRecord(r.id);if(old.patient_id!==p.id||old.method_id!==r.method_id)throw new Error('A ficha pertence a outro paciente ou método.');if(old.revision!==r.revision)throw new Error('A ficha foi atualizada. Reabra o registro antes de alterar.');return old.snapshot;}return {...patient(p),id:p.id};}
 saveClinical(input){const r=prepareClinical(input),snapshot=this.clinicalContext(r);bindIdentity(r,snapshot);return this.tx(()=>{let id=r.id;const values=JSON.stringify(r.values),snap=JSON.stringify(snapshot);if(id){this.audit('clinical:corrected',id,this.clinicalRecord(id));this.run('UPDATE clinical_records SET professional=?,coren=?,record_type=?,eval_date=?,eval_time=?,values_json=?,revision=revision+1,updated_at=CURRENT_TIMESTAMP WHERE id=?',[r.professional,r.coren,r.record_type,r.eval_date,r.eval_time,values,id]);}else{this.run('INSERT INTO clinical_records(patient_id,method_id,template_version,professional,coren,record_type,eval_date,eval_time,values_json,snapshot) VALUES(?,?,?,?,?,?,?,?,?,?)',[r.patient_id,r.method_id,r.template_version,r.professional,r.coren,r.record_type,r.eval_date,r.eval_time,values,snap]);id=this.query('SELECT last_insert_rowid() AS id')[0].id;this.audit('clinical:created',id);}this.run('DELETE FROM clinical_drafts WHERE patient_id=? AND method_id=?',[r.patient_id,r.method_id]);return this.clinicalRecord(id);});}
 clinicalDraft(patientId,methodId,value){validId(patientId);require('../modules/anamnesis').model(methodId);if(value===undefined){const row=this.query('SELECT value FROM clinical_drafts WHERE patient_id=? AND method_id=?',[patientId,methodId])[0];return row?JSON.parse(row.value):null;}if(value===null)return this.tx(()=>{this.run('DELETE FROM clinical_drafts WHERE patient_id=? AND method_id=?',[patientId,methodId]);return true;});const r=prepareClinical(value,true);if(r.patient_id!==patientId||r.method_id!==methodId)throw new Error('Rascunho pertence a outro paciente ou método.');const snapshot=this.clinicalContext(r);bindIdentity(r,snapshot);return this.tx(()=>{this.run('INSERT OR REPLACE INTO clinical_drafts(patient_id,method_id,value) VALUES(?,?,?)',[patientId,methodId,JSON.stringify({...r,snapshot})]);return true;});}
 deleteClinical(id){const old=this.clinicalRecord(id);return this.tx(()=>{this.audit('clinical:deleted',id,old);this.run('DELETE FROM clinical_records WHERE id=?',[id]);const d=this.clinicalDraft(old.patient_id,old.method_id);if(d?.id===id)this.run('DELETE FROM clinical_drafts WHERE patient_id=? AND method_id=?',[old.patient_id,old.method_id]);return true;});}
 clinicalDrafts(){return this.query('SELECT patient_id,method_id,updated_at FROM clinical_drafts ORDER BY updated_at DESC');}
 settings(value){if(value===undefined){return Object.fromEntries(this.query('SELECT * FROM settings').map(r=>[r.key,JSON.parse(r.value)]));}const clean={institution:text(value.institution,200),professional:text(value.professional),unit:text(value.unit,120),fontScale:[100,110,125].includes(value.fontScale)?value.fontScale:100,highContrast:!!value.highContrast};return this.tx(()=>{for(const [k,v]of Object.entries(clean))this.run('INSERT OR REPLACE INTO settings(key,value) VALUES(?,?)',[k,JSON.stringify(v)]);return clean;});}
 draft(value){if(value===undefined){const r=this.query("SELECT value FROM drafts WHERE key='current'")[0];return r?JSON.parse(r.value):null;}if(value===null)return this.tx(()=>{this.run("DELETE FROM drafts WHERE key='current'");return true;});const str=JSON.stringify(value);if(str.length>40000)throw new Error('Rascunho muito grande.');return this.tx(()=>{this.run("INSERT OR REPLACE INTO drafts(key,value) VALUES('current',?)",[str]);return true;});}
 dimensioningList(){return this.query('SELECT * FROM dimensioning_records ORDER BY reference_date DESC,updated_at DESC,id DESC').map(r=>({...r,params:JSON.parse(r.params_json),result:JSON.parse(r.result_json)}));}
 dimensioningSave(input){if(!input||typeof input!=='object')throw new Error('Cenário inválido.');const sectors=['internacao','centro_cirurgico','hemodialise','oncologia','urgencia','cme','cdi','saude_mental','caps','aps'],sector=text(input.sector_type,40);if(!sectors.includes(sector))throw new Error('Serviço de dimensionamento inválido.');const name=text(input.name,180);if(!name)throw new Error('Informe o nome do cenário.');const unit=text(input.unit,120),instrument=text(input.instrument,20);if(instrument&&!['fugulin','perroca'].includes(instrument))throw new Error('Instrumento inválido.');const reference=date(input.reference_date),params=JSON.stringify(input.params||{}),result=JSON.stringify(input.result||{});if(params.length>50000||result.length>100000)throw new Error('Cenário excede o limite de armazenamento.');JSON.parse(params);JSON.parse(result);return this.tx(()=>{let id=input.id?validId(input.id):null;if(id){const old=this.query('SELECT * FROM dimensioning_records WHERE id=?',[id])[0];if(!old)throw new Error('Cenário não encontrado.');this.audit('dimensioning:corrected',id,old);this.run('UPDATE dimensioning_records SET name=?,sector_type=?,unit=?,instrument=?,reference_date=?,params_json=?,result_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=?',[name,sector,unit,instrument,reference,params,result,id]);}else{this.run('INSERT INTO dimensioning_records(name,sector_type,unit,instrument,reference_date,params_json,result_json) VALUES(?,?,?,?,?,?,?)',[name,sector,unit,instrument,reference,params,result]);id=this.query('SELECT last_insert_rowid() AS id')[0].id;this.audit('dimensioning:created',id);}const row=this.query('SELECT * FROM dimensioning_records WHERE id=?',[id])[0];return {...row,params:JSON.parse(row.params_json),result:JSON.parse(row.result_json)};});}
 dimensioningDelete(id){id=validId(id);return this.tx(()=>{const old=this.query('SELECT * FROM dimensioning_records WHERE id=?',[id])[0];if(!old)throw new Error('Cenário não encontrado.');this.audit('dimensioning:deleted',id,old);this.run('DELETE FROM dimensioning_records WHERE id=?',[id]);return true;});}
 bytes(){return Buffer.from(this.exportBytes());}
 validateImport(bytes){if(bytes.length>100*1024*1024)throw new Error('Backup excede 100 MB.');let candidate;try{candidate=new this.SQL.Database(bytes);const check=candidate.exec('PRAGMA integrity_check');if(check[0]?.values[0]?.[0]!=='ok')throw new Error();for(const table of ['patients','assessments']){const cols=candidate.exec(`PRAGMA table_info(${table})`);if(!cols[0]?.values?.length)throw new Error();}const schema=candidate.exec("SELECT type,name FROM sqlite_master WHERE name NOT LIKE 'sqlite_%'");
 const allowed=['patients','assessments','settings','drafts','audit','clinical_records','clinical_drafts','dimensioning_records'];
 if(schema[0]?.values.some(([type,name])=>type==='trigger'||type==='view'||(type==='table'&&!allowed.includes(name))))throw new Error();
 candidate.exec('SELECT id,name,prontuario,birthdate,unit,bed FROM patients');candidate.exec('SELECT id,patient_id,professional,eval_date,scores,total,classification,hours,created_at,updated_at FROM assessments');const orphan=candidate.exec('SELECT count(*) FROM assessments a LEFT JOIN patients p ON a.patient_id=p.id WHERE p.id IS NULL');if(orphan[0].values[0][0]!==0)throw new Error();
 const version=candidate.exec('PRAGMA user_version')[0].values[0][0];if(version>4)throw new Error();
 const read=sql=>{const st=candidate.prepare(sql),rows=[];try{while(st.step()){rows.push(st.getAsObject());if(rows.length>200000)throw new Error();}return rows;}finally{st.free();}};
 const importPatients=new Map(read('SELECT * FROM patients').map(p=>[p.id,p]));for(const row of importPatients.values()){validId(row.id);patient(row);}
 for(const row of read('SELECT * FROM assessments')){
  validId(row.id);validId(row.patient_id);date(row.eval_date);
  const scores=JSON.parse(row.scores);if(!scores||Array.isArray(scores)||typeof scores!=='object')throw new Error();
  if(!row.module_version||row.module_version==='legacy-prototype'){
   const legacy=getModule('fugulin');if(Object.keys(scores).some(id=>!legacy.criteria.some(c=>c.id===id)))throw new Error();
   for(const score of Object.values(scores))if(!Number.isInteger(score)||score<0||score>4)throw new Error();
   if(Object.keys(scores).length!==12||!Number.isInteger(row.total)||row.total<12||row.total>48||row.total!==Object.values(scores).reduce((n,v)=>n+v,0))throw new Error();
  }else{
   const mod=getModule(row.module_id||'fugulin');if(row.module_version!==mod.version)throw new Error();
   const computed=mod.calculate(scores);if(row.total!==computed.total||row.hours!==computed.hours||row.classification!==computed.name)throw new Error();
   prepareAssessment({...row,scores});
  }
  if(row.snapshot){const snapshot=JSON.parse(row.snapshot);patient(snapshot);}
 }
 if(schema[0]?.values.some(([type,name])=>type==='table'&&name==='settings'))for(const row of read('SELECT * FROM settings')){const val=JSON.parse(row.value);if(!['institution','professional','unit','fontScale','highContrast'].includes(row.key))throw new Error();if(['institution','professional','unit'].includes(row.key))text(val,200);if(row.key==='fontScale'&&![100,110,125].includes(val))throw new Error();if(row.key==='highContrast'&&typeof val!=='boolean')throw new Error();}
 if(schema[0]?.values.some(([type,name])=>type==='table'&&name==='drafts'))for(const row of read('SELECT * FROM drafts')){if(row.key!=='current')throw new Error();const draft=JSON.parse(row.value);if(!draft?.patient||!draft?.assessment||typeof draft.patient.name!=='string'||JSON.stringify(draft).length>40000)throw new Error();for(const score of Object.values(draft.assessment.scores||{}))if(!Number.isInteger(score)||score<0||score>4)throw new Error();}
 const hasTable=name=>schema[0]?.values.some(([type,n])=>type==='table'&&n===name);
 const importClinical=new Map((hasTable('clinical_records')?read('SELECT * FROM clinical_records'):[]).map(r=>[r.id,r]));if(hasTable('clinical_records'))for(const row of importClinical.values()){validId(row.id);const p=importPatients.get(row.patient_id);if(!p)throw new Error();const r=prepareClinical({...row,values:JSON.parse(row.values_json)});validatePopulation(p,r);const snap=JSON.parse(row.snapshot);patient(snap);if(snap.id!==row.patient_id||row.revision<1)throw new Error();}
 if(hasTable('clinical_drafts'))for(const row of read('SELECT * FROM clinical_drafts')){const r=prepareClinical(JSON.parse(row.value),true);if(row.patient_id!==r.patient_id||row.method_id!==r.method_id)throw new Error();const p=importPatients.get(row.patient_id);if(!p)throw new Error();validatePopulation(p,r);if(r.id){const old=importClinical.get(r.id);if(!old||old.patient_id!==r.patient_id||old.method_id!==r.method_id||old.revision!==r.revision)throw new Error();}const snap=JSON.parse(row.value).snapshot;patient(snap);if(snap.id!==r.patient_id)throw new Error();}
 if(hasTable('dimensioning_records'))for(const row of read('SELECT * FROM dimensioning_records')){validId(row.id);text(row.name,180);if(!['internacao','centro_cirurgico','hemodialise','oncologia','urgencia','cme','cdi','saude_mental','caps','aps'].includes(row.sector_type))throw new Error();text(row.unit,120);if(row.instrument&&!['','fugulin','perroca'].includes(row.instrument))throw new Error();date(row.reference_date);const params=JSON.parse(row.params_json),result=JSON.parse(row.result_json);if(!params||Array.isArray(params)||typeof params!=='object'||!result||Array.isArray(result)||typeof result!=='object'||row.params_json.length>50000||row.result_json.length>100000)throw new Error();}
 return true;}catch{throw new Error('O backup não é um banco de dados compatível e íntegro.');}finally{candidate?.close();}}
 replace(bytes){this.validateImport(bytes);const previous=this.exportBytes();try{this.db.close();this.db=new this.SQL.Database(bytes);this.migrate();this.audit('backup:restored',null);this.persist();}catch(e){this.db.close();this.db=new this.SQL.Database(previous);this.db.run('PRAGMA foreign_keys=ON');throw e;}}
 allAssessments(){return this.query('SELECT * FROM assessments ORDER BY eval_date DESC,eval_time DESC,id DESC').map(r=>({...r,scores:JSON.parse(r.scores),snapshot:r.snapshot?JSON.parse(r.snapshot):null}));}
 close(){this.db.close();}
}
module.exports={Store,patient,prepareAssessment,date,validatePopulation};
