'use strict';
const {app,BrowserWindow,ipcMain,dialog,Menu,shell,safeStorage}=require('electron');
const path=require('node:path'),fs=require('node:fs'),crypto=require('node:crypto'),{pathToFileURL}=require('node:url');
const initSQL=require('sql.js'),{Store}=require('./src/services/store'),{backup,restore}=require('./src/services/crypto'),{report,csv}=require('./src/services/report'),{listModules}=require('./src/modules/registry');
const {clinicalReport}=require('./src/services/anamnesis-report');const {prepare:prepareClinical}=require('./src/modules/anamnesis');
const HOME=pathToFileURL(path.join(__dirname,'renderer.html')).href;
const references=require('./src/modules/fugulin').sources.map(s=>s.url).concat(['https://www.calculadorasdeenfermagem.com.br/',...require('./src/modules/anamnesis/templates').map(t=>t.source)]);
let win,store,dirty=false,closing=false;
if(!app.isPackaged&&process.env.NURSING_TEST_USER_DATA)app.setPath('userData',process.env.NURSING_TEST_USER_DATA);
const primaryInstance=app.requestSingleInstanceLock();
if(!primaryInstance)app.quit();
app.on('second-instance',()=>{if(win){if(win.isMinimized())win.restore();win.focus();}});
function key(){const location=path.join(app.getPath('userData'),'local-key.dpapi');if(!safeStorage.isEncryptionAvailable())throw new Error('A proteção de dados do sistema operacional não está disponível. O aplicativo não abrirá o banco sem essa proteção.');if(fs.existsSync(location)){const k=Buffer.from(safeStorage.decryptString(fs.readFileSync(location)),'base64');if(k.length!==32)throw new Error('Chave local inválida.');return k;}const k=crypto.randomBytes(32);fs.mkdirSync(path.dirname(location),{recursive:true});fs.writeFileSync(location,safeStorage.encryptString(k.toString('base64')),{mode:0o600});return k;}
function secure(window){window.webContents.setWindowOpenHandler(()=>({action:'deny'}));window.webContents.on('will-navigate',event=>event.preventDefault());window.webContents.session.setPermissionRequestHandler((_w,_p,cb)=>cb(false));window.webContents.session.setPermissionCheckHandler(()=>false);}
function action(name){win?.webContents.send('app:action',name);}
function handle(name,fn){ipcMain.handle(name,async(event,...args)=>{if(!win||event.sender!==win.webContents||event.senderFrame?.url!==HOME)throw new Error('Origem não autorizada.');try{return await fn(...args);}catch(error){throw new Error(error.message||'Não foi possível concluir a operação.');}});}
async function confirm(message,detail){const r=await dialog.showMessageBox(win,{type:'warning',message,detail,buttons:['Cancelar','Confirmar'],defaultId:0,cancelId:0,noLink:true});return r.response===1;}
function write(file,bytes){const tmp=file+'.tmp';fs.writeFileSync(tmp,bytes,{mode:0o600});fs.renameSync(tmp,file);}
async function outputReport(input,pdf,clinical=false){let target;if(pdf){const choice=await dialog.showSaveDialog(win,{title:'Salvar avaliação em PDF',defaultPath:clinical?'Anamnese-Exame-Fisico.pdf':'Avaliacao-Fugulin.pdf',filters:[{name:'PDF',extensions:['pdf']}]});if(choice.canceled)return {canceled:true};target=choice.filePath;}const view=new BrowserWindow({show:false,parent:win,width:900,height:1000,webPreferences:{sandbox:true,contextIsolation:true,nodeIntegration:false}});secure(view);try{await view.loadURL('data:text/html;charset=utf-8,'+encodeURIComponent(clinical?clinicalReport({...prepareClinical(input),snapshot:store.clinicalContext(prepareClinical(input))},store.settings()):report(input,store.settings())));if(pdf){const bytes=await view.webContents.printToPDF({printBackground:true,preferCSSPageSize:true});write(target,bytes);return {ok:true};}await new Promise((resolve,reject)=>view.webContents.print({silent:false,printBackground:true},(success,reason)=>success?resolve():reason==='cancelled'?resolve():reject(new Error(reason||'Impressão não concluída.'))));return {ok:true};}finally{view.destroy();}}
handle('app:init',()=>({patients:store.list(),settings:store.settings(),draft:store.draft(),modules:listModules(),clinicalDrafts:store.clinicalDrafts(),version:app.getVersion(),protected:process.platform==='win32'}));
handle('patient:save',input=>store.savePatient(input));
handle('clinical:history',id=>store.clinicalHistory(id));handle('clinical:record',id=>store.clinicalRecord(id));handle('clinical:save',input=>store.saveClinical(input));handle('clinical:draft',(id,method,value)=>store.clinicalDraft(id,method,value));handle('clinical:drafts',()=>store.clinicalDrafts());
handle('clinical:delete',async id=>{if(!await confirm('Excluir esta ficha de anamnese?','A ficha e suas informações anteriores permanecerão no registro local de alterações.'))return {canceled:true};store.deleteClinical(id);return {ok:true};});
handle('clinical:pdf',input=>outputReport(input,true,true));handle('clinical:print',input=>outputReport(input,false,true));
handle('data:patients',()=>store.list());handle('data:history',id=>store.history(id));handle('data:save',input=>store.save(input));
handle('data:archive',(id,value)=>store.archive(id,value));
handle('data:deletePatient',async id=>{if(!await confirm('Excluir este paciente e suas avaliações?','O histórico de exclusão é mantido no registro local de alterações. Exporte um backup antes de excluir.'))return {canceled:true};store.deletePatient(id);return {ok:true};});
handle('data:deleteAssessment',async id=>{if(!await confirm('Excluir esta avaliação?','A exclusão ficará registrada localmente.'))return {canceled:true};store.deleteAssessment(id);return {ok:true};});
handle('data:draft',value=>store.draft(value));handle('data:settings',value=>store.settings(value));handle('data:assessments',()=>store.allAssessments());
handle('app:dirty',value=>{dirty=!!value;});handle('app:closeReady',()=>{closing=true;win.close();});
handle('app:reference',url=>{if(!references.includes(url))throw new Error('Referência não autorizada.');return shell.openExternal(url);});
handle('report:pdf',input=>outputReport(input,true));handle('report:print',input=>outputReport(input,false));
handle('backup:export',async password=>{const bytes=backup(store.bytes(),password);const choice=await dialog.showSaveDialog(win,{title:'Criar backup protegido por senha',defaultPath:`Enfermagem-backup-${new Date().toISOString().slice(0,10)}.enfbackup`,filters:[{name:'Backup protegido',extensions:['enfbackup']}]});if(choice.canceled)return {canceled:true};write(choice.filePath,bytes);return {ok:true};});
handle('backup:restore',async password=>{const choice=await dialog.showOpenDialog(win,{title:'Restaurar backup',properties:['openFile'],filters:[{name:'Backup de enfermagem',extensions:['enfbackup','db']}]});if(choice.canceled)return {canceled:true};const file=choice.filePaths[0];if(fs.statSync(file).size>100*1024*1024)throw new Error('Backup excede 100 MB.');const bytes=fs.readFileSync(file);const legacy=bytes.subarray(0,16).toString()==='SQLite format 3\u0000';const data=legacy?bytes:restore(bytes,password);store.validateImport(data);if(!await confirm('Substituir os dados locais pelo backup?',legacy?'Este é um banco antigo sem criptografia. As avaliações importadas do protótipo serão identificadas como versão legada. Será criada uma cópia protegida dos dados atuais.':'Uma cópia protegida dos dados atuais será mantida antes da restauração.'))return {canceled:true};const recovery=path.join(app.getPath('userData'),'recovery');fs.mkdirSync(recovery,{recursive:true});fs.copyFileSync(store.file,path.join(recovery,`antes-restauracao-${Date.now()}.enfdb`));store.replace(data);dirty=false;return {ok:true};});
handle('export:csv',async filters=>{const from=filters?.from||'',to=filters?.to||'',unit=filters?.unit||'';let rows=store.allAssessments().filter(a=>(!from||a.eval_date>=from)&&(!to||a.eval_date<=to)&&(!unit||a.snapshot?.unit===unit));const patients=store.list();const sheet=[['Paciente','Prontuário','Setor','Leito','Data','Hora','Profissional','Escore','Classificação','Horas/paciente/dia','Módulo','Versão','Revisão'],...rows.map(a=>{const p=a.snapshot||patients.find(p=>p.id===a.patient_id)||{};return [p.name,p.prontuario,p.unit,p.bed,a.eval_date,a.eval_time,a.professional,a.total,a.classification,a.hours,a.module_id,a.module_version,a.revision];})];const choice=await dialog.showSaveDialog(win,{title:'Exportar tabela para Excel',defaultPath:'Avaliacoes-Fugulin.csv',filters:[{name:'Tabela CSV',extensions:['csv']}]});if(choice.canceled)return {canceled:true};write(choice.filePath,csv(sheet));return {ok:true,count:rows.length};});
function createWindow(){win=new BrowserWindow({width:1440,height:950,minWidth:900,minHeight:640,title:'Estação de Enfermagem',backgroundColor:'#F8FAFC',icon:path.join(__dirname,'assets','icon.png'),show:false,webPreferences:{preload:path.join(__dirname,'preload.js'),sandbox:true,contextIsolation:true,nodeIntegration:false,webSecurity:true,spellcheck:false}});secure(win);win.once('ready-to-show',()=>win.show());win.loadFile(path.join(__dirname,'renderer.html'));win.on('close',event=>{if(dirty&&!closing){event.preventDefault();const response=dialog.showMessageBoxSync(win,{type:'question',message:'Há um registro em andamento.',detail:'Você pode guardar o rascunho e continuar na próxima abertura.',buttons:['Continuar editando','Guardar rascunho e sair'],defaultId:0,cancelId:0});if(response===1)action('close-draft');}});}
function menu(){Menu.setApplicationMenu(Menu.buildFromTemplate([{label:'Arquivo',submenu:[{label:'Nova avaliação',accelerator:'CmdOrCtrl+N',click:()=>action('new')},{label:'Salvar avaliação',accelerator:'CmdOrCtrl+S',click:()=>action('save')},{type:'separator'},{label:'Salvar PDF',accelerator:'CmdOrCtrl+Shift+P',click:()=>action('pdf')},{label:'Imprimir',accelerator:'CmdOrCtrl+P',click:()=>action('print')},{type:'separator'},{label:'Criar backup',click:()=>action('backup')},{label:'Restaurar backup',click:()=>action('restore')},{role:'quit',label:'Sair'}]},{label:'Editar',submenu:[{role:'undo',label:'Desfazer'},{role:'redo',label:'Refazer'},{type:'separator'},{role:'cut',label:'Recortar'},{role:'copy',label:'Copiar'},{role:'paste',label:'Colar'},{role:'selectAll',label:'Selecionar tudo'}]},{label:'Exibir',submenu:[{label:'Painel do setor',click:()=>action('dashboard')},{label:'Pacientes',click:()=>action('patients')},{label:'Configurações',click:()=>action('settings')},{type:'separator'},{role:'resetZoom',label:'Tamanho original'},{role:'zoomIn',label:'Ampliar'},{role:'zoomOut',label:'Reduzir'},{role:'togglefullscreen',label:'Tela cheia'}]},{label:'Ajuda',submenu:[{label:'Guia e referências',accelerator:'F1',click:()=>action('help')},{label:'Sobre',click:()=>dialog.showMessageBox(win,{message:'Estação de Enfermagem',detail:`Calculadoras de Enfermagem\nVersão ${app.getVersion()}\nAplicação local para adultos.\nEsta versão inicial não possui sincronização nem assinatura digital de documentos.`})}]}]));}
app.whenReady().then(async()=>{if(!primaryInstance)return;const SQL=await initSQL({locateFile:f=>path.join(__dirname,'node_modules/sql.js/dist',f)});store=new Store(SQL,path.join(app.getPath('userData'),'enfermagem.enfdb'),key());createWindow();menu();app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)createWindow();});}).catch(error=>{dialog.showErrorBox('Não foi possível abrir a Estação de Enfermagem',error.message);app.quit();});
app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit();});app.on('will-quit',()=>store?.close());
