'use strict';
const {test,before}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const initSQL=require('sql.js'),{Store}=require('../src/services/store'),{seal}=require('../src/services/crypto'),{clinicalReport}=require('../src/services/anamnesis-report'),{prepare,model}=require('../src/modules/anamnesis'),templates=require('../src/modules/anamnesis/templates');let SQL;
before(async()=>SQL=await initSQL());
function setup(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'anamnese-unit-')),file=path.join(dir,'data.enfdb'),key=crypto.randomBytes(32),store=new Store(SQL,file,key);const p=store.savePatient({name:'PACIENTE FICTÍCIO A',prontuario:'DEMO-A',birthdate:'1980-05-10',bed:'10',unit:'Clínica'});return {store,p,file,key};}
function input(p,method='brasileiro'){return {patient_id:p.id,method_id:method,template_version:'1.0.0',professional:'ENFERMEIRO FICTÍCIO',coren:'DEMO-123',record_type:'Admissão',eval_date:'2026-10-01',eval_time:'12:30',values:{}};}
test('all source controls have unique stable UI and printable keys',()=>{assert.deepEqual(templates.map(t=>t.fields.length),[198,165]);assert.deepEqual(templates.map(t=>t.sections.length),[6,10]);for(const t of templates){assert.equal(new Set(t.fields.map(f=>f.id)).size,t.fields.length);assert.equal((t.html.match(/data-field=/g)||[]).length,t.fields.length);assert.equal((t.printHtml.match(/\{\{(field|check):/g)||[]).length,t.fields.length);assert(!/<script|onchange=|onclick=|https?:/.test(t.html));}});
test('patient registration does not require a Fugulin assessment',()=>{const {store}=setup();assert.equal(store.list()[0].assessment_count,0);assert.equal(store.list()[0].clinical_count,0);store.close();});
test('both models persist every checkbox and text in encrypted records and survive reopening',()=>{const {store,p,file,key}=setup();for(const t of templates){const a=input(p,t.id);for(const f of t.fields)a.values[f.id]=f.type==='boolean'?true:'TEXTO_'+t.id+'_'+f.id+' á & < >';const saved=store.saveClinical(a);assert.equal(saved.values.f001,p.name);assert.equal(saved.method_id,t.id);assert.equal(saved.snapshot.prontuario,'DEMO-A');for(const f of t.fields)if(f.type==='boolean')assert.equal(saved.values[f.id],true);assert.equal(saved.professional,a.professional);}store.close();const bytes=fs.readFileSync(file);assert.equal(bytes.subarray(0,8).toString(),'ENFDB001');assert(!bytes.includes(Buffer.from('DEMO-A')));const reopened=new Store(SQL,file,key);assert.equal(reopened.clinicalHistory(p.id).length,2);reopened.close();});
test('drafts stay isolated across patients and methods, and clear only on their own save',()=>{const {store,p}=setup(),q=store.savePatient({name:'PACIENTE FICTÍCIO B'});for(const [pat,m]of [[p,'brasileiro'],[p,'americano'],[q,'brasileiro']]){const a=input(pat,m);a.values.f007=pat.name+' '+m;store.clinicalDraft(pat.id,m,a);}assert.equal(store.clinicalDrafts().length,3);assert.equal(store.clinicalDraft(q.id,'americano'),null);store.saveClinical(store.clinicalDraft(p.id,'brasileiro'));assert.equal(store.clinicalDrafts().length,2);assert.match(store.clinicalDraft(q.id,'brasileiro').values.f007,/FICTÍCIO B/);store.close();});
test('record retification preserves snapshot, audit and revision and rejects crossing or stale edits',()=>{const {store,p}=setup();const first=store.saveClinical(input(p));store.savePatient({...p,name:'NOME ATUAL',bed:'99'});const change={...first,values:{...first.values,f007:'Alteração clínica'}};const revised=store.saveClinical(change);assert.equal(revised.revision,2);assert.equal(revised.snapshot.name,p.name);assert.equal(revised.values.f001,p.name);assert.equal(store.list()[0].name,'NOME ATUAL');assert.equal(JSON.parse(store.query("SELECT previous FROM audit WHERE action='clinical:corrected'")[0].previous).values.f007,'');assert.throws(()=>store.saveClinical(change),/atualizada/);const other=store.savePatient({name:'Outro'});assert.throws(()=>store.saveClinical({...revised,patient_id:other.id}),/outro paciente/);assert.throws(()=>store.saveClinical({...revised,method_id:'americano',values:{}}),/outro paciente/);store.close();});
test('invalid values, dates, methods, versions and pediatric records cannot save',()=>{const {store,p}=setup();const a=input(p);for(const patch of [{method_id:'x'},{template_version:'0'},{eval_time:'25:00'},{eval_date:'2026-02-30'},{professional:''},{values:{fake:'x'}},{values:{f003:'true'}},{values:{f001:'x'.repeat(4001)}}])assert.throws(()=>store.saveClinical({...a,...patch}));const q=store.savePatient({name:'Menor',birthdate:'2020-01-01'});assert.throws(()=>store.saveClinical(input(q)),/adultos/);assert.equal(store.clinicalHistory(p.id).length,0);store.close();});
test('clinical transactions roll back if disk writes fail',()=>{const {store,p}=setup();const persist=store.persist;store.persist=()=>{throw new Error('disk full');};assert.throws(()=>store.saveClinical(input(p)),/disk full/);assert.equal(store.clinicalHistory(p.id).length,0);store.persist=persist;store.close();});
test('new backups validate clinical data and reject tampering before replacement',()=>{const {store,p}=setup();const saved=store.saveClinical(input(p));store.clinicalDraft(p.id,'americano',input(p,'americano'));store.replace(store.bytes());assert.equal(store.clinicalHistory(p.id).length,1);assert.equal(store.clinicalDrafts().length,1);for(const sql of ["UPDATE clinical_records SET method_id='unknown'","UPDATE clinical_records SET patient_id=987","UPDATE clinical_records SET template_version='9'","UPDATE clinical_records SET values_json='broken'","UPDATE clinical_records SET snapshot='{}'","UPDATE clinical_drafts SET method_id='brasileiro'","UPDATE clinical_drafts SET value=json_set(value,'$.snapshot.id',999)"]){const bad=new SQL.Database(store.bytes());bad.run(sql);assert.throws(()=>store.replace(bad.export()),/compatível/);assert.equal(store.clinicalRecord(saved.id).patient_id,p.id);bad.close();}store.close();});
test('0.1.0 encrypted database migration and old backup retain Fugulin and create empty clinical tables',()=>{const {store,p,file,key}=setup();store.save({patient:p,assessment:{professional:'DEMO',eval_date:'2026-10-01',eval_time:'12:00',scores:Object.fromEntries(require('../src/modules/fugulin').criteria.map(c=>[c.id,1]))}});const proto=new SQL.Database(store.bytes());proto.run('DROP TABLE clinical_drafts;DROP TABLE clinical_records;PRAGMA user_version=2');const old=proto.export();store.close();fs.writeFileSync(file,seal(Buffer.from(old),key));const migrated=new Store(SQL,file,key);assert.equal(migrated.list()[0].name,p.name);assert.equal(migrated.history(p.id)[0].total,12);assert.equal(migrated.clinicalHistory(p.id).length,0);migrated.replace(old);assert.equal(migrated.clinicalDrafts().length,0);migrated.close();proto.close();});
test('patient deletion cascades all records/drafts while leaving audit of former clinical values',()=>{const {store,p}=setup();store.saveClinical(input(p));store.clinicalDraft(p.id,'americano',input(p,'americano'));store.deletePatient(p.id);assert.equal(store.query('SELECT * FROM clinical_records').length,0);assert.equal(store.clinicalDrafts().length,0);assert.equal(JSON.parse(store.query("SELECT previous FROM audit WHERE action='patient:deleted'")[0].previous).clinical_records.length,1);store.close();});
test('printable sheets contain values, X marks, metadata, escape markup and support long text',()=>{for(const t of templates){const a=input({id:1},t.id);const text=t.fields.find(f=>f.type==='text'&&f.id!=='f001'&&f.label.includes('ALERGIAS'));const check=t.fields.find(f=>f.type==='boolean');a.values[text.id]='<img src=x onerror=alert(1)>\ntexto extenso '+ 'cuidado '.repeat(100);a.values[check.id]=true;const html=clinicalReport({...a,snapshot:{id:1,name:'Nome',prontuario:'DEMO',bed:'12'}});assert(html.includes('&lt;img'));assert(!html.includes('<img src=x'));assert(html.includes('class="checked">X'));assert(html.includes('class="long-text"'));assert(!html.includes('{{'));assert(!html.includes('<input'));assert(html.includes('ENFERMEIRO FICTÍCIO'));}});
