'use strict';
const assert=require('node:assert/strict'),path=require('node:path');
module.exports=async function clinicalFlow(page,{artifacts,pdfTarget,suffix=''}){
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 async function settled(){await page.waitForFunction(()=>!state.busy);}
 async function patient(name,record){await page.locator('#patient-register').click();await page.locator('#register-name').fill(name);await page.locator('#register-record').fill(record);await page.locator('#register-birth').fill('1980-05-10');await page.locator('#register-unit').fill('Clínica fictícia');await page.locator('#register-bed').fill('12');await page.locator('#patient-form [type=submit]').click();await page.waitForFunction(n=>document.querySelector('#history-title').textContent===n,name);await settled();}
 async function fields(prefix){const controls=await page.locator('#clinical-fields [data-field]').all();for(let i=0;i<controls.length;i++){const el=controls[i],kind=await el.getAttribute('type');if(kind==='checkbox'){if(i%2===0)await el.check();else await el.uncheck();}else if(!await el.evaluate(e=>e.readOnly)){const key=await el.getAttribute('data-field');await el.fill(prefix+'-'+key);}}await page.locator('#clinical-professional').fill('ENFERMEIRO FICTÍCIO');await page.locator('#clinical-coren').fill('DEMO-COREN');}
 async function save(){await page.locator('#clinical-save').click();await page.waitForFunction(()=>document.querySelector('#clinical-save-status').textContent==='Ficha no histórico');await settled();}
 async function pdf(file){if(pdfTarget)await pdfTarget(path.join(artifacts,file));await page.locator('#clinical-pdf').click();await settled();assert.equal(await page.locator('#toast').textContent(),'PDF da ficha salvo.');}
 await page.locator('.rail [data-view=patients]').click();await settled();await patient('PACIENTE FICTÍCIO — ANAMNESE A','DEMO-ANAM-A');await page.locator('[data-clinical-method=brasileiro]').click();await settled();assert.equal(await page.locator('#clinical-fields [data-field]').count(),198);assert.equal(await page.locator('#clinical-f001').inputValue(),'PACIENTE FICTÍCIO — ANAMNESE A');await fields('BR');
 const brBefore=await page.evaluate(()=>Object.fromEntries([...document.querySelectorAll('#clinical-fields [data-field]')].map(e=>[e.dataset.field,e.type==='checkbox'?e.checked:e.value])));
 await page.locator('#clinical-method').selectOption('americano');await settled();assert.equal(await page.locator('#clinical-fields [data-field]').count(),165);assert.equal(await page.locator('#clinical-fields input[type=checkbox]:checked').count(),0);await fields('US');await page.locator('#clinical-method').selectOption('brasileiro');await settled();const brAfter=await page.evaluate(()=>Object.fromEntries([...document.querySelectorAll('#clinical-fields [data-field]')].map(e=>[e.dataset.field,e.type==='checkbox'?e.checked:e.value])));assert.deepEqual(brAfter,brBefore);
 await save();await page.evaluate(()=>{document.activeElement.blur();window.scrollTo(0,0);});await page.screenshot({path:path.join(artifacts,'anamnese-brasileiro'+suffix+'.png'),fullPage:true});await page.screenshot({path:path.join(artifacts,'anamnese-brasileiro-resumo'+suffix+'.png')});await pdf('anamnese-brasileiro'+suffix+'.pdf');await page.locator('#clinical-method').selectOption('americano');await settled();assert.match(await page.locator('#clinical-save-status').textContent(),/recuperado/);await save();await page.evaluate(()=>{document.activeElement.blur();window.scrollTo(0,0);});await page.screenshot({path:path.join(artifacts,'anamnese-americano'+suffix+'.png'),fullPage:true});await page.screenshot({path:path.join(artifacts,'anamnese-americano-resumo'+suffix+'.png')});await pdf('anamnese-americano'+suffix+'.pdf');
 // Retification keeps historical snapshot when demographics subsequently change.
 await page.locator('#clinical-back').click();await settled();assert.equal(await page.locator('#clinical-history-list [data-clinical-record]').count(),2);await page.locator('#clinical-history-list [data-clinical-model=brasileiro][data-clinical-record]').click();await settled();const free=page.locator('#clinical-fields textarea').first();await free.fill('RETIFICAÇÃO CLÍNICA DEMO');await page.locator('#clinical-save').click();await page.locator('#confirm-accept').click();await page.waitForFunction(()=>document.querySelector('#clinical-mode').textContent.includes('revisão 2'));await settled();
 // Very long and hostile input must print all text as inert content through final sentinel.
 const long='MARCADOR-INICIO '+('Descrição clínica fictícia, cuidadosa e extensa. '.repeat(70))+' MARCADOR-FIM <img src=x onerror=alert(1)>';
 await free.fill(long);await pdf('anamnese-texto-longo'+suffix+'.pdf');await page.locator('#clinical-back').click();await settled();await patient('PACIENTE FICTÍCIO — ANAMNESE B','DEMO-ANAM-B');await page.locator('[data-clinical-method=brasileiro]').click();await settled();assert.equal(await page.locator('#clinical-f001').inputValue(),'PACIENTE FICTÍCIO — ANAMNESE B');assert.equal(await page.locator('#clinical-fields input[type=checkbox]:checked').count(),0);assert.equal(await page.locator('#clinical-fields textarea').first().inputValue(),'');await page.locator('#clinical-fields textarea').first().fill('RASCUNHO EXCLUSIVO PACIENTE B');await page.locator('#clinical-back').click();await settled();await page.locator('[data-clinical-method=brasileiro]').click();await settled();assert.equal(await page.locator('#clinical-fields textarea').first().inputValue(),'RASCUNHO EXCLUSIVO PACIENTE B');
 // Check restored drafts across reload; all values survive and remain assigned to B.
 await page.locator('#clinical-back').click();await settled();await page.reload();await page.waitForFunction(()=>document.querySelector('#save-state').textContent==='Sem alterações pendentes');await page.locator('.rail [data-view=patients]').click();await settled();await page.locator('#clinical-draft-list .history-entry').filter({hasText:'ANAMNESE B'}).locator('[data-clinical-resume]').click();await settled();assert.equal(await page.locator('#clinical-fields textarea').first().inputValue(),'RASCUNHO EXCLUSIVO PACIENTE B');
 for(const width of [1440,960,560]){await page.setViewportSize({width,height:950});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);}await page.setViewportSize({width:1440,height:950});assert.deepEqual(errors,[]);await page.locator('#clinical-back').click();await settled();return {patientsAdded:2};
};
