const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto'),initSQL=require('sql.js');const {Store}=require('../src/services/store'),fugulin=require('../src/modules/fugulin'),{backup,restore}=require('../src/services/crypto'),{csv,report}=require('../src/services/report');
let SQL,temp;before(async()=>{SQL=await initSQL();temp=fs.mkdtempSync(path.join(os.tmpdir(),'fugulin-tests-'));});after(()=>fs.rmSync(temp,{recursive:true,force:true}));
function setup(){const file=path.join(temp,crypto.randomUUID()+'.enfdb'),key=crypto.randomBytes(32);return {store:new Store(SQL,file,key),file,key};}
function input(name='Paciente de teste',id=null){return {patient:{id,name,prontuario:'FICTICIO-001',birthdate:'1980-01-01',unit:'Clínica médica',bed:'12'},assessment:{professional:'Enfermeiro teste',eval_date:'2026-10-01',eval_time:'09:00',scores:Object.fromEntries(fugulin.criteria.map(c=>[c.id,1])),notes:'Dados fictícios'}};}
test('save recomputes classification and reopens encrypted local data',()=>{const {store,file,key}=setup();const a=input();a.assessment.total=48;a.assessment.classification='Intensivos';const saved=store.save(a);assert.equal(saved.assessment.total,12);assert.equal(saved.assessment.hours,4);store.close();assert(!fs.readFileSync(file).includes(Buffer.from('Paciente de teste')));const reopened=new Store(SQL,file,key);assert.equal(reopened.history(saved.patient.id)[0].total,12);assert.equal(reopened.list()[0].name,a.patient.name);reopened.close();});
test('retification keeps previous values and prevents crossing patients',()=>{const {store}=setup();const first=store.save(input('Paciente A')),second=store.save(input('Paciente B'));const correction=input('Paciente A',first.patient.id);correction.assessment.id=first.assessment.id;correction.assessment.scores.estado_mental=4;const result=store.save(correction);assert.equal(result.assessment.revision,2);assert.equal(store.query("SELECT * FROM audit WHERE action='assessment:corrected'").length,1);const cross=input('Paciente B',second.patient.id);cross.assessment.id=first.assessment.id;assert.throws(()=>store.save(cross),/outro paciente/);assert.equal(store.history(first.patient.id)[0].total,15);store.close();});
test('historical snapshots remain unchanged when current patient demographics change',()=>{const {store}=setup();const first=store.save(input('Nome inicial'));const next=input('Nome atualizado',first.patient.id);store.save(next);assert.equal(store.history(first.patient.id).find(a=>a.id===first.assessment.id).snapshot.name,'Nome inicial');store.close();});
test('invalid saves cannot create partial patient records',()=>{const {store}=setup();const a=input();a.assessment.scores.curativo=0;assert.throws(()=>store.save(a));assert.equal(store.list().length,0);const child=input();child.patient.birthdate='2020-01-01';assert.throws(()=>store.save(child),/adultos/);assert.equal(store.list().length,0);store.close();});
test('invalid backups and wrong password preserve the original data',()=>{const {store}=setup();store.save(input());const encrypted=backup(store.bytes(),'password-test-123');assert.throws(()=>restore(encrypted,'wrong-password'),/Senha incorreta/);assert.throws(()=>store.replace(Buffer.from('not a database')),/compatível/);assert.equal(store.list().length,1);const bytes=restore(encrypted,'password-test-123');store.replace(bytes);assert.equal(store.list().length,1);store.close();});
test('draft and preferences persist and clear after a successful save',()=>{const {store,file,key}=setup();store.settings({institution:'Instituição teste',fontScale:125});store.draft(input());store.close();const reopened=new Store(SQL,file,key);assert.equal(reopened.draft().patient.name,'Paciente de teste');assert.equal(reopened.settings().fontScale,125);reopened.save(reopened.draft());assert.equal(reopened.draft(),null);reopened.close();});
test('database changes roll back when file persistence fails',()=>{const {store}=setup();const original=store.persist;store.persist=()=>{throw new Error('disk full')};assert.throws(()=>store.save(input()),/disk full/);assert.equal(store.list().length,0);store.persist=original;store.close();});
test('patient deletion cascades while preserving a local deletion audit',()=>{const {store}=setup();const result=store.save(input());store.archive(result.patient.id,true);assert.equal(store.list()[0].archived,1);store.deletePatient(result.patient.id);assert.equal(store.allAssessments().length,0);assert.equal(store.query("SELECT count(*) AS count FROM audit WHERE action='patient:deleted'")[0].count,1);store.close();});
test('report escapes patient markup and CSV protects formula cells',()=>{const a=input('<img src=x onerror=alert(1)>');const html=report(a);assert(!html.includes('<img src=x'));assert(html.includes('&lt;img'));const sheet=csv([['=HYPERLINK("x")',';quoted','line\nline']]);assert(sheet.includes("'="));assert(sheet.includes('";quoted"'));assert(sheet.startsWith('\uFEFF'));});
test('eighteenth birthday is accepted, previous day and pediatric report rejected',()=>{const {store}=setup();const birthday=input();birthday.patient.birthdate='2008-10-01';assert.doesNotThrow(()=>store.save(birthday));const younger=input();younger.patient.birthdate='2008-10-02';assert.throws(()=>store.save(younger),/adultos/);assert.throws(()=>report(younger),/adultos/);store.close();});
test('retifying historical record does not overwrite current unit or name',()=>{const {store}=setup();const old=store.save(input('Antigo'));const next=input('Atual',old.patient.id);next.patient.unit='UTI';store.save(next);const correction=input('Antigo',old.patient.id);correction.assessment.id=old.assessment.id;correction.assessment.notes='Retificação de texto';store.save(correction);assert.equal(store.list()[0].name,'Atual');assert.equal(store.list()[0].unit,'UTI');store.close();});
test('malformed JSON, unsafe schema and altered totals cannot replace data',()=>{const {store}=setup();store.save(input());for(const sql of ["UPDATE assessments SET scores='invalid'","UPDATE assessments SET total=999","PRAGMA user_version=0;UPDATE assessments SET total=13","CREATE TRIGGER bad AFTER INSERT ON patients BEGIN DELETE FROM assessments; END","PRAGMA user_version=3"]){const bad=new SQL.Database(store.bytes());bad.run(sql);assert.throws(()=>store.replace(bad.export()),/compatível/);assert.equal(store.list().length,1);bad.close();}store.close();});
test('invalid times are rejected before persistence or report',()=>{const {store}=setup();const a=input();a.assessment.eval_time='invalid';assert.throws(()=>store.save(a),/Hora/);assert.throws(()=>report(a),/Hora/);store.close();});
