// Stripe Sandbox Checkout — isolado da produção.
// Nunca usa STRIPE_SECRET_KEY nem STRIPE_PRICE_* de produção.
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
const STRIPE_SECRET_KEY = Deno.env.get("STRIPE_TEST_SECRET_KEY") ?? "";
const PRICE_ID = Deno.env.get("STRIPE_TEST_PRICE_ID") ?? "";
const STRIPE_API = "https://api.stripe.com/v1";
const SITE_URL = "https://www.calculadorasdeenfermagem.com.br";
const FIREBASE_PROJECT_ID = Deno.env.get("FIREBASE_PROJECT_ID") ?? "calculadoras-enfermagem";
const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
const JWKS_URL = "https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com";
const INTERNATIONAL_LANGS=["en","es","fr","de","it","hi","zh","ja","ru","ko","tr","nl","pl","sv","id","vi","uk","ar"];
const cors=()=>({"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Authorization, apikey, Content-Type","Content-Type":"application/json; charset=utf-8"});
function b64(s:string){const x=s.replace(/-/g,"+").replace(/_/g,"/");return atob(x+"=".repeat((4-x.length%4)%4));}
function bytes(s:string){const bin=b64(s);const a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return a;}
function pem(pem:string){const bin=atob(pem.replace(/-----BEGIN CERTIFICATE-----/,"").replace(/-----END CERTIFICATE-----/,"").replace(/\s+/g,""));const a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return a.buffer;}
async function verify(t:string){const [h,p,s]=t.split(".");if(!h||!p||!s)throw Error("invalid_token");const header=JSON.parse(new TextDecoder().decode(bytes(h)));const payload=JSON.parse(new TextDecoder().decode(bytes(p)));if(header.alg!=="RS256"||!header.kid||Number(payload.exp||0)*1000<Date.now()||payload.aud!==FIREBASE_PROJECT_ID||payload.iss!==`https://securetoken.google.com/${FIREBASE_PROJECT_ID}`)throw Error("invalid_token");const r=await fetch(JWKS_URL);if(!r.ok)throw Error("google_keys_unavailable");const certs=await r.json();const key=await crypto.subtle.importKey("spki",pem(certs[header.kid]),{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["verify"]);if(!await crypto.subtle.verify("RSASSA-PKCS1-v1_5",key,bytes(s),new TextEncoder().encode(`${h}.${p}`)))throw Error("invalid_signature");return{uid:String(payload.sub||""),email:String(payload.email||"").trim().toLowerCase()};}
async function claim(uid:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/claim_billing_checkout`,{method:"POST",headers:{apikey:SUPABASE_SERVICE_ROLE_KEY,Authorization:`Bearer ${SUPABASE_SERVICE_ROLE_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({p_provider:"stripe_test",p_user_id:uid,p_lease_seconds:900})});if(!r.ok)throw Error(`checkout_lock_failed:${r.status}`);const d=await r.json();return d===true||d==="true"||(Array.isArray(d)&&d[0]===true);}
async function release(uid:string,msg:string){try{await fetch(`${SUPABASE_URL}/rest/v1/rpc/release_billing_checkout`,{method:"POST",headers:{apikey:SUPABASE_SERVICE_ROLE_KEY,Authorization:`Bearer ${SUPABASE_SERVICE_ROLE_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({p_provider:"stripe_test",p_user_id:uid,p_error:msg.slice(0,2000)})});}catch{}}
async function complete(uid:string){await fetch(`${SUPABASE_URL}/rest/v1/rpc/complete_billing_checkout`,{method:"POST",headers:{apikey:SUPABASE_SERVICE_ROLE_KEY,Authorization:`Bearer ${SUPABASE_SERVICE_ROLE_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({p_provider:"stripe_test",p_user_id:uid})});}
serve(async(req)=>{if(req.method==="OPTIONS")return new Response("",{status:204,headers:cors()});if(req.method!=="POST")return new Response(JSON.stringify({error:"method_not_allowed"}),{status:405,headers:cors()});if(!STRIPE_SECRET_KEY||!PRICE_ID||!SUPABASE_URL||!SUPABASE_SERVICE_ROLE_KEY)return new Response(JSON.stringify({error:"stripe_test_not_configured"}),{status:503,headers:cors()});let uid="",held=false;try{const body=await req.json();uid=String(body?.uid||"");const lang=String(body?.lang||"").trim().toLowerCase();if(!uid||!INTERNATIONAL_LANGS.includes(lang))return new Response(JSON.stringify({error:"invalid_test_request"}),{status:400,headers:cors()});const auth=req.headers.get("Authorization")||"";const user=auth.startsWith("Bearer ")?await verify(auth.slice(7)):null;if(!user||user.uid!==uid)return new Response(JSON.stringify({error:"unauthorized"}),{status:401,headers:cors()});held=await claim(uid);if(!held)return new Response(JSON.stringify({error:"checkout_test_already_in_progress"}),{status:409,headers:cors()});const form=new URLSearchParams({mode:"subscription","line_items[0][price]":PRICE_ID,"line_items[0][quantity]":"1",client_reference_id:uid,"metadata[uid]":uid,"metadata[lang]":lang,"metadata[payment_provider]":"stripe_test","metadata[environment]":"test","subscription_data[metadata][uid]":uid,"subscription_data[metadata][lang]":lang,"subscription_data[metadata][payment_provider]":"stripe_test","subscription_data[metadata][environment]":"test",customer_email:user.email,locale:"auto",success_url:`${SITE_URL}/conta/assinatura.html?lang=${encodeURIComponent(lang)}&stripe=test-success`,cancel_url:`${SITE_URL}/conta/assinatura.html?lang=${encodeURIComponent(lang)}&stripe=test-cancel`});const r=await fetch(`${STRIPE_API}/checkout/sessions`,{method:"POST",headers:{Authorization:`Bearer ${STRIPE_SECRET_KEY}`,"Content-Type":"application/x-www-form-urlencoded"},body:form});const d=await r.json();if(!r.ok||!d.url)throw Error(d?.error?.message||"checkout_creation_failed");await complete(uid);held=false;return new Response(JSON.stringify({url:d.url,environment:"test"}),{status:200,headers:cors()});}catch(e){if(held&&uid)await release(uid,String(e));console.error("[stripe-checkout-test]",e);return new Response(JSON.stringify({error:String(e)}),{status:500,headers:cors()});}});