-- Reconstitutes the legacy schema objects that existed before the
-- tracked migration history began. These objects were previously created
-- outside supabase/migrations and are required by later tracked migrations.
-- All DDL is idempotent so this migration is safe on the existing project.

create extension if not exists pgcrypto;

create table if not exists public.album_fotos (
  id integer generated by default as identity primary key,
  imagem_url text,
  titulo text,
  descricao text,
  ano integer,
  instituicao text,
  localizacao text,
  data_upload timestamp without time zone not null default now(),
  likes integer default 0
);

create table if not exists public.album_comentarios (
  id bigint generated by default as identity primary key,
  foto_id integer not null references public.album_fotos(id) on delete cascade,
  author_key text not null,
  author_name text,
  comentario text not null,
  localizacao text,
  created_at timestamptz not null default now()
);

alter table public.album_fotos enable row level security;
alter table public.album_comentarios enable row level security;

create table if not exists public.payments (
  id uuid primary key,
  user_id text not null,
  plan_id text not null,
  status text not null default 'pending',
  mp_payment_id bigint,
  mp_preference_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.payments enable row level security;

create table if not exists public.user_entitlements (
  user_id uuid primary key,
  plan text not null default 'free' check (plan in ('free','premium')),
  premium_expires_at timestamptz,
  provider text check (provider in ('asaas','stripe')),
  provider_customer_id text,
  provider_subscription_id text,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint user_entitlements_user_id_fkey foreign key (user_id) references auth.users(id) on delete cascade
);

alter table public.user_entitlements enable row level security;
revoke all on public.user_entitlements from anon, authenticated;

create table if not exists public.billing_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  provider text not null check (provider in ('asaas','stripe')),
  external_id text not null,
  status text not null,
  plan text not null default 'premium' check (plan = 'premium'),
  currency text,
  current_period_start timestamptz,
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint billing_subscriptions_user_id_fkey foreign key (user_id) references auth.users(id) on delete cascade
);

alter table public.billing_subscriptions enable row level security;
revoke all on public.billing_subscriptions from anon, authenticated;

-- These legacy RPCs were already removed from production by later migrations,
-- but their existence is required so the historical revoke/drop migrations can
-- replay cleanly on a fresh Preview Branch.
create or replace function public.current_user_plan()
returns text
language plpgsql
as $$
begin
  return 'free';
end;
$$;

create or replace function public.ensure_user_entitlement()
returns void
language plpgsql
as $$
begin
  return;
end;
$$;

revoke all on function public.current_user_plan() from public, anon, authenticated;
revoke all on function public.ensure_user_entitlement() from public, anon, authenticated;
