name: Atualizar Vagas e Concursos

on:
  schedule:
    - cron: '0 6 * * *' # Executa todos os dias às 06:00 UTC (03:00 Horário de Brasília)
  workflow_dispatch: # Permite que você execute manualmente quando quiser

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Executar o Script de Scraping
        run: python scraping.py

      - name: Commitar e Enviar Alterações
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Atualizar vagas e concursos" || echo "Nenhuma alteração para commitar"
          git push
